/** Base de tribunais atendidos — usada nas páginas /tribunais e no sitemap. */
export type TipoTribunal = "estadual" | "federal" | "trabalhista" | "superior";

export interface Tribunal {
  slug: string;
  sigla: string;
  nome: string;
  tipo: TipoTribunal;
  uf?: string;
  estadoSlug?: string;
  sede: string;
  sistema: string;
  prazo: string;
  abrangencia: string;
  comarcas: string[];
  resumo: string;
}

export const TIPOS_TRIBUNAL: { tipo: TipoTribunal; titulo: string; descricao: string }[] = [
  { tipo: "estadual", titulo: "Tribunais de Justiça (estaduais)", descricao: "Processos cíveis, criminais, de família, sucessões e execuções que tramitam na Justiça Estadual." },
  { tipo: "federal", titulo: "Tribunais Regionais Federais", descricao: "Processos em que a União, autarquias e empresas públicas federais são parte, incluindo INSS, Caixa e execuções fiscais federais." },
  { tipo: "trabalhista", titulo: "Tribunais Regionais do Trabalho", descricao: "Reclamações trabalhistas, execuções e ações coletivas na Justiça do Trabalho." },
  { tipo: "superior", titulo: "Tribunais superiores e especiais", descricao: "Recursos e processos originários no STF, STJ, TST, STM e na Justiça Eleitoral." },
];

export const TRIBUNAIS: Tribunal[] = [
  {
    slug: "tjsp",
    sigla: "TJSP",
    nome: "Tribunal de Justiça de São Paulo",
    tipo: "estadual",
    uf: "SP",
    estadoSlug: "sp",
    sede: "São Paulo",
    sistema: "e-SAJ",
    prazo: "1 a 7 dias úteis",
    abrangencia: "Estado de São Paulo",
    comarcas: ["São Paulo", "Campinas", "Guarulhos", "Santos", "Ribeirão Preto", "Sorocaba", "Osasco", "São José dos Campos"],
    resumo: "Certidão de Objeto e Pé de processos que tramitam no TJSP, Tribunal de Justiça de São Paulo. Identificamos a vara e a comarca no sistema e-SAJ, protocolamos o requerimento e entregamos o documento digital.",
  },
  {
    slug: "tjrj",
    sigla: "TJRJ",
    nome: "Tribunal de Justiça de Rio de Janeiro",
    tipo: "estadual",
    uf: "RJ",
    estadoSlug: "rj",
    sede: "Rio de Janeiro",
    sistema: "PJe e Portal de Serviços",
    prazo: "2 a 8 dias úteis",
    abrangencia: "Estado do Rio de Janeiro",
    comarcas: ["Rio de Janeiro", "Niterói", "Duque de Caxias", "Nova Iguaçu", "São Gonçalo", "Campos dos Goytacazes", "Petrópolis"],
    resumo: "Certidão de Objeto e Pé de processos que tramitam no TJRJ, Tribunal de Justiça de Rio de Janeiro. Identificamos a vara e a comarca no sistema PJe e Portal de Serviços, protocolamos o requerimento e entregamos o documento digital.",
  },
  {
    slug: "tjmg",
    sigla: "TJMG",
    nome: "Tribunal de Justiça de Minas Gerais",
    tipo: "estadual",
    uf: "MG",
    estadoSlug: "mg",
    sede: "Belo Horizonte",
    sistema: "PJe e Themis",
    prazo: "2 a 8 dias úteis",
    abrangencia: "Estado de Minas Gerais",
    comarcas: ["Belo Horizonte", "Uberlândia", "Contagem", "Juiz de Fora", "Betim", "Montes Claros", "Uberaba"],
    resumo: "Certidão de Objeto e Pé de processos que tramitam no TJMG, Tribunal de Justiça de Minas Gerais. Identificamos a vara e a comarca no sistema PJe e Themis, protocolamos o requerimento e entregamos o documento digital.",
  },
  {
    slug: "tjba",
    sigla: "TJBA",
    nome: "Tribunal de Justiça de Bahia",
    tipo: "estadual",
    uf: "BA",
    estadoSlug: "ba",
    sede: "Salvador",
    sistema: "PJe",
    prazo: "3 a 10 dias úteis",
    abrangencia: "Estado de Bahia",
    comarcas: ["Salvador", "Feira de Santana", "Vitória da Conquista", "Camaçari", "Juazeiro", "Ilhéus", "Itabuna"],
    resumo: "Certidão de Objeto e Pé de processos que tramitam no TJBA, Tribunal de Justiça de Bahia. Identificamos a vara e a comarca no sistema PJe, protocolamos o requerimento e entregamos o documento digital.",
  },
  {
    slug: "tjpe",
    sigla: "TJPE",
    nome: "Tribunal de Justiça de Pernambuco",
    tipo: "estadual",
    uf: "PE",
    estadoSlug: "pe",
    sede: "Recife",
    sistema: "PJe",
    prazo: "3 a 10 dias úteis",
    abrangencia: "Estado de Pernambuco",
    comarcas: ["Recife", "Jaboatão dos Guararapes", "Olinda", "Caruaru", "Petrolina", "Paulista"],
    resumo: "Certidão de Objeto e Pé de processos que tramitam no TJPE, Tribunal de Justiça de Pernambuco. Identificamos a vara e a comarca no sistema PJe, protocolamos o requerimento e entregamos o documento digital.",
  },
  {
    slug: "tjdft",
    sigla: "TJDFT",
    nome: "Tribunal de Justiça de Distrito Federal",
    tipo: "estadual",
    uf: "DF",
    estadoSlug: "df",
    sede: "Brasília",
    sistema: "PJe",
    prazo: "2 a 7 dias úteis",
    abrangencia: "Distrito Federal e territórios",
    comarcas: ["Brasília", "Taguatinga", "Ceilândia", "Gama", "Samambaia", "Planaltina"],
    resumo: "Certidão de Objeto e Pé de processos que tramitam no TJDFT, Tribunal de Justiça de Distrito Federal. Identificamos a vara e a comarca no sistema PJe, protocolamos o requerimento e entregamos o documento digital.",
  },
  {
    slug: "tjpr",
    sigla: "TJPR",
    nome: "Tribunal de Justiça de Paraná",
    tipo: "estadual",
    uf: "PR",
    estadoSlug: "pr",
    sede: "Curitiba",
    sistema: "Projudi e PJe",
    prazo: "2 a 8 dias úteis",
    abrangencia: "Estado de Paraná",
    comarcas: ["Curitiba", "Londrina", "Maringá", "Ponta Grossa", "Cascavel", "Foz do Iguaçu", "São José dos Pinhais"],
    resumo: "Certidão de Objeto e Pé de processos que tramitam no TJPR, Tribunal de Justiça de Paraná. Identificamos a vara e a comarca no sistema Projudi e PJe, protocolamos o requerimento e entregamos o documento digital.",
  },
  {
    slug: "tjrs",
    sigla: "TJRS",
    nome: "Tribunal de Justiça de Rio Grande do Sul",
    tipo: "estadual",
    uf: "RS",
    estadoSlug: "rs",
    sede: "Porto Alegre",
    sistema: "eproc",
    prazo: "2 a 8 dias úteis",
    abrangencia: "Estado do Rio Grande do Sul",
    comarcas: ["Porto Alegre", "Caxias do Sul", "Pelotas", "Canoas", "Santa Maria", "Gravataí", "Novo Hamburgo"],
    resumo: "Certidão de Objeto e Pé de processos que tramitam no TJRS, Tribunal de Justiça de Rio Grande do Sul. Identificamos a vara e a comarca no sistema eproc, protocolamos o requerimento e entregamos o documento digital.",
  },
  {
    slug: "tjsc",
    sigla: "TJSC",
    nome: "Tribunal de Justiça de Santa Catarina",
    tipo: "estadual",
    uf: "SC",
    estadoSlug: "sc",
    sede: "Florianópolis",
    sistema: "eproc",
    prazo: "2 a 8 dias úteis",
    abrangencia: "Estado de Santa Catarina",
    comarcas: ["Florianópolis", "Joinville", "Blumenau", "São José", "Chapecó", "Criciúma", "Itajaí"],
    resumo: "Certidão de Objeto e Pé de processos que tramitam no TJSC, Tribunal de Justiça de Santa Catarina. Identificamos a vara e a comarca no sistema eproc, protocolamos o requerimento e entregamos o documento digital.",
  },
  {
    slug: "tjgo",
    sigla: "TJGO",
    nome: "Tribunal de Justiça de Goiás",
    tipo: "estadual",
    uf: "GO",
    estadoSlug: "go",
    sede: "Goiânia",
    sistema: "Projudi",
    prazo: "3 a 9 dias úteis",
    abrangencia: "Estado de Goiás",
    comarcas: ["Goiânia", "Aparecida de Goiânia", "Anápolis", "Rio Verde", "Luziânia"],
    resumo: "Certidão de Objeto e Pé de processos que tramitam no TJGO, Tribunal de Justiça de Goiás. Identificamos a vara e a comarca no sistema Projudi, protocolamos o requerimento e entregamos o documento digital.",
  },
  {
    slug: "tjce",
    sigla: "TJCE",
    nome: "Tribunal de Justiça de Ceará",
    tipo: "estadual",
    uf: "CE",
    estadoSlug: "ce",
    sede: "Fortaleza",
    sistema: "PJe",
    prazo: "3 a 10 dias úteis",
    abrangencia: "Estado do Ceará",
    comarcas: ["Fortaleza", "Caucaia", "Juazeiro do Norte", "Maracanaú", "Sobral", "Crato"],
    resumo: "Certidão de Objeto e Pé de processos que tramitam no TJCE, Tribunal de Justiça de Ceará. Identificamos a vara e a comarca no sistema PJe, protocolamos o requerimento e entregamos o documento digital.",
  },
  {
    slug: "tjmt",
    sigla: "TJMT",
    nome: "Tribunal de Justiça de Mato Grosso",
    tipo: "estadual",
    uf: "MT",
    estadoSlug: "mt",
    sede: "Cuiabá",
    sistema: "PJe",
    prazo: "3 a 9 dias úteis",
    abrangencia: "Estado de Mato Grosso",
    comarcas: ["Cuiabá", "Várzea Grande", "Rondonópolis", "Sinop", "Tangará da Serra"],
    resumo: "Certidão de Objeto e Pé de processos que tramitam no TJMT, Tribunal de Justiça de Mato Grosso. Identificamos a vara e a comarca no sistema PJe, protocolamos o requerimento e entregamos o documento digital.",
  },
  {
    slug: "tjms",
    sigla: "TJMS",
    nome: "Tribunal de Justiça de Mato Grosso do Sul",
    tipo: "estadual",
    uf: "MS",
    estadoSlug: "ms",
    sede: "Campo Grande",
    sistema: "eSAJ",
    prazo: "3 a 9 dias úteis",
    abrangencia: "Estado de Mato Grosso do Sul",
    comarcas: ["Campo Grande", "Dourados", "Três Lagoas", "Corumbá", "Ponta Porã"],
    resumo: "Certidão de Objeto e Pé de processos que tramitam no TJMS, Tribunal de Justiça de Mato Grosso do Sul. Identificamos a vara e a comarca no sistema eSAJ, protocolamos o requerimento e entregamos o documento digital.",
  },
  {
    slug: "tjes",
    sigla: "TJES",
    nome: "Tribunal de Justiça de Espírito Santo",
    tipo: "estadual",
    uf: "ES",
    estadoSlug: "es",
    sede: "Vitória",
    sistema: "PJe",
    prazo: "3 a 9 dias úteis",
    abrangencia: "Estado do Espírito Santo",
    comarcas: ["Vitória", "Vila Velha", "Serra", "Cariacica", "Linhares", "Colatina"],
    resumo: "Certidão de Objeto e Pé de processos que tramitam no TJES, Tribunal de Justiça de Espírito Santo. Identificamos a vara e a comarca no sistema PJe, protocolamos o requerimento e entregamos o documento digital.",
  },
  {
    slug: "tjpa",
    sigla: "TJPA",
    nome: "Tribunal de Justiça de Pará",
    tipo: "estadual",
    uf: "PA",
    estadoSlug: "pa",
    sede: "Belém",
    sistema: "PJe",
    prazo: "4 a 12 dias úteis",
    abrangencia: "Estado do Pará",
    comarcas: ["Belém", "Ananindeua", "Santarém", "Marabá", "Castanhal", "Parauapebas"],
    resumo: "Certidão de Objeto e Pé de processos que tramitam no TJPA, Tribunal de Justiça de Pará. Identificamos a vara e a comarca no sistema PJe, protocolamos o requerimento e entregamos o documento digital.",
  },
  {
    slug: "tjam",
    sigla: "TJAM",
    nome: "Tribunal de Justiça de Amazonas",
    tipo: "estadual",
    uf: "AM",
    estadoSlug: "am",
    sede: "Manaus",
    sistema: "PJe e Projudi",
    prazo: "4 a 12 dias úteis",
    abrangencia: "Estado do Amazonas",
    comarcas: ["Manaus", "Parintins", "Itacoatiara", "Manacapuru", "Coari"],
    resumo: "Certidão de Objeto e Pé de processos que tramitam no TJAM, Tribunal de Justiça de Amazonas. Identificamos a vara e a comarca no sistema PJe e Projudi, protocolamos o requerimento e entregamos o documento digital.",
  },
  {
    slug: "tjma",
    sigla: "TJMA",
    nome: "Tribunal de Justiça de Maranhão",
    tipo: "estadual",
    uf: "MA",
    estadoSlug: "ma",
    sede: "São Luís",
    sistema: "PJe",
    prazo: "4 a 12 dias úteis",
    abrangencia: "Estado do Maranhão",
    comarcas: ["São Luís", "Imperatriz", "Timon", "Caxias", "Codó"],
    resumo: "Certidão de Objeto e Pé de processos que tramitam no TJMA, Tribunal de Justiça de Maranhão. Identificamos a vara e a comarca no sistema PJe, protocolamos o requerimento e entregamos o documento digital.",
  },
  {
    slug: "tjpb",
    sigla: "TJPB",
    nome: "Tribunal de Justiça de Paraíba",
    tipo: "estadual",
    uf: "PB",
    estadoSlug: "pb",
    sede: "João Pessoa",
    sistema: "PJe",
    prazo: "3 a 10 dias úteis",
    abrangencia: "Estado de Paraíba",
    comarcas: ["João Pessoa", "Campina Grande", "Santa Rita", "Patos", "Bayeux"],
    resumo: "Certidão de Objeto e Pé de processos que tramitam no TJPB, Tribunal de Justiça de Paraíba. Identificamos a vara e a comarca no sistema PJe, protocolamos o requerimento e entregamos o documento digital.",
  },
  {
    slug: "tjrn",
    sigla: "TJRN",
    nome: "Tribunal de Justiça de Rio Grande do Norte",
    tipo: "estadual",
    uf: "RN",
    estadoSlug: "rn",
    sede: "Natal",
    sistema: "PJe",
    prazo: "3 a 10 dias úteis",
    abrangencia: "Estado do Rio Grande do Norte",
    comarcas: ["Natal", "Mossoró", "Parnamirim", "São Gonçalo do Amarante", "Caicó"],
    resumo: "Certidão de Objeto e Pé de processos que tramitam no TJRN, Tribunal de Justiça de Rio Grande do Norte. Identificamos a vara e a comarca no sistema PJe, protocolamos o requerimento e entregamos o documento digital.",
  },
  {
    slug: "tjal",
    sigla: "TJAL",
    nome: "Tribunal de Justiça de Alagoas",
    tipo: "estadual",
    uf: "AL",
    estadoSlug: "al",
    sede: "Maceió",
    sistema: "PJe e eSAJ",
    prazo: "3 a 10 dias úteis",
    abrangencia: "Estado de Alagoas",
    comarcas: ["Maceió", "Arapiraca", "Palmeira dos Índios", "Rio Largo", "União dos Palmares"],
    resumo: "Certidão de Objeto e Pé de processos que tramitam no TJAL, Tribunal de Justiça de Alagoas. Identificamos a vara e a comarca no sistema PJe e eSAJ, protocolamos o requerimento e entregamos o documento digital.",
  },
  {
    slug: "tjse",
    sigla: "TJSE",
    nome: "Tribunal de Justiça de Sergipe",
    tipo: "estadual",
    uf: "SE",
    estadoSlug: "se",
    sede: "Aracaju",
    sistema: "PJe",
    prazo: "3 a 10 dias úteis",
    abrangencia: "Estado de Sergipe",
    comarcas: ["Aracaju", "Nossa Senhora do Socorro", "Lagarto", "Itabaiana", "Estância"],
    resumo: "Certidão de Objeto e Pé de processos que tramitam no TJSE, Tribunal de Justiça de Sergipe. Identificamos a vara e a comarca no sistema PJe, protocolamos o requerimento e entregamos o documento digital.",
  },
  {
    slug: "tjpi",
    sigla: "TJPI",
    nome: "Tribunal de Justiça de Piauí",
    tipo: "estadual",
    uf: "PI",
    estadoSlug: "pi",
    sede: "Teresina",
    sistema: "PJe",
    prazo: "4 a 11 dias úteis",
    abrangencia: "Estado do Piauí",
    comarcas: ["Teresina", "Parnaíba", "Picos", "Floriano", "Piripiri"],
    resumo: "Certidão de Objeto e Pé de processos que tramitam no TJPI, Tribunal de Justiça de Piauí. Identificamos a vara e a comarca no sistema PJe, protocolamos o requerimento e entregamos o documento digital.",
  },
  {
    slug: "tjto",
    sigla: "TJTO",
    nome: "Tribunal de Justiça de Tocantins",
    tipo: "estadual",
    uf: "TO",
    estadoSlug: "to",
    sede: "Palmas",
    sistema: "eproc",
    prazo: "3 a 10 dias úteis",
    abrangencia: "Estado do Tocantins",
    comarcas: ["Palmas", "Araguaína", "Gurupi", "Porto Nacional", "Paraíso do Tocantins"],
    resumo: "Certidão de Objeto e Pé de processos que tramitam no TJTO, Tribunal de Justiça de Tocantins. Identificamos a vara e a comarca no sistema eproc, protocolamos o requerimento e entregamos o documento digital.",
  },
  {
    slug: "tjro",
    sigla: "TJRO",
    nome: "Tribunal de Justiça de Rondônia",
    tipo: "estadual",
    uf: "RO",
    estadoSlug: "ro",
    sede: "Porto Velho",
    sistema: "PJe",
    prazo: "4 a 11 dias úteis",
    abrangencia: "Estado de Rondônia",
    comarcas: ["Porto Velho", "Ji-Paraná", "Ariquemes", "Vilhena", "Cacoal"],
    resumo: "Certidão de Objeto e Pé de processos que tramitam no TJRO, Tribunal de Justiça de Rondônia. Identificamos a vara e a comarca no sistema PJe, protocolamos o requerimento e entregamos o documento digital.",
  },
  {
    slug: "tjac",
    sigla: "TJAC",
    nome: "Tribunal de Justiça de Acre",
    tipo: "estadual",
    uf: "AC",
    estadoSlug: "ac",
    sede: "Rio Branco",
    sistema: "eproc",
    prazo: "4 a 12 dias úteis",
    abrangencia: "Estado do Acre",
    comarcas: ["Rio Branco", "Cruzeiro do Sul", "Sena Madureira", "Tarauacá", "Feijó"],
    resumo: "Certidão de Objeto e Pé de processos que tramitam no TJAC, Tribunal de Justiça de Acre. Identificamos a vara e a comarca no sistema eproc, protocolamos o requerimento e entregamos o documento digital.",
  },
  {
    slug: "tjap",
    sigla: "TJAP",
    nome: "Tribunal de Justiça de Amapá",
    tipo: "estadual",
    uf: "AP",
    estadoSlug: "ap",
    sede: "Macapá",
    sistema: "PJe e Tucujuris",
    prazo: "4 a 12 dias úteis",
    abrangencia: "Estado do Amapá",
    comarcas: ["Macapá", "Santana", "Laranjal do Jari", "Oiapoque", "Mazagão"],
    resumo: "Certidão de Objeto e Pé de processos que tramitam no TJAP, Tribunal de Justiça de Amapá. Identificamos a vara e a comarca no sistema PJe e Tucujuris, protocolamos o requerimento e entregamos o documento digital.",
  },
  {
    slug: "tjrr",
    sigla: "TJRR",
    nome: "Tribunal de Justiça de Roraima",
    tipo: "estadual",
    uf: "RR",
    estadoSlug: "rr",
    sede: "Boa Vista",
    sistema: "PJe e Projudi",
    prazo: "4 a 12 dias úteis",
    abrangencia: "Estado de Roraima",
    comarcas: ["Boa Vista", "Rorainópolis", "Caracaraí", "Mucajaí", "Pacaraima"],
    resumo: "Certidão de Objeto e Pé de processos que tramitam no TJRR, Tribunal de Justiça de Roraima. Identificamos a vara e a comarca no sistema PJe e Projudi, protocolamos o requerimento e entregamos o documento digital.",
  },
  {
    slug: "trf1",
    sigla: "TRF1",
    nome: "Tribunal Regional Federal da 1ª Região",
    tipo: "federal",
    sede: "Brasília",
    sistema: "PJe",
    prazo: "4 a 12 dias úteis",
    abrangencia: "AC, AM, AP, BA, DF, GO, MA, MG, MT, PA, PI, RO, RR e TO",
    comarcas: ["Brasília"],
    resumo: "Certidão de Objeto e Pé de processos da Justiça Federal no TRF1, com jurisdição sobre AC, AM, AP, BA, DF, GO, MA, MG, MT, PA, PI, RO, RR e TO. Atuamos no sistema PJe e acompanhamos até a emissão.",
  },
  {
    slug: "trf2",
    sigla: "TRF2",
    nome: "Tribunal Regional Federal da 2ª Região",
    tipo: "federal",
    sede: "Rio de Janeiro",
    sistema: "eproc",
    prazo: "3 a 10 dias úteis",
    abrangencia: "Rio de Janeiro e Espírito Santo",
    comarcas: ["Rio de Janeiro"],
    resumo: "Certidão de Objeto e Pé de processos da Justiça Federal no TRF2, com jurisdição sobre Rio de Janeiro e Espírito Santo. Atuamos no sistema eproc e acompanhamos até a emissão.",
  },
  {
    slug: "trf3",
    sigla: "TRF3",
    nome: "Tribunal Regional Federal da 3ª Região",
    tipo: "federal",
    sede: "São Paulo",
    sistema: "PJe",
    prazo: "3 a 10 dias úteis",
    abrangencia: "São Paulo e Mato Grosso do Sul",
    comarcas: ["São Paulo"],
    resumo: "Certidão de Objeto e Pé de processos da Justiça Federal no TRF3, com jurisdição sobre São Paulo e Mato Grosso do Sul. Atuamos no sistema PJe e acompanhamos até a emissão.",
  },
  {
    slug: "trf4",
    sigla: "TRF4",
    nome: "Tribunal Regional Federal da 4ª Região",
    tipo: "federal",
    sede: "Porto Alegre",
    sistema: "eproc",
    prazo: "2 a 9 dias úteis",
    abrangencia: "Rio Grande do Sul, Santa Catarina e Paraná",
    comarcas: ["Porto Alegre"],
    resumo: "Certidão de Objeto e Pé de processos da Justiça Federal no TRF4, com jurisdição sobre Rio Grande do Sul, Santa Catarina e Paraná. Atuamos no sistema eproc e acompanhamos até a emissão.",
  },
  {
    slug: "trf5",
    sigla: "TRF5",
    nome: "Tribunal Regional Federal da 5ª Região",
    tipo: "federal",
    sede: "Recife",
    sistema: "PJe",
    prazo: "3 a 11 dias úteis",
    abrangencia: "AL, CE, PB, PE, RN e SE",
    comarcas: ["Recife"],
    resumo: "Certidão de Objeto e Pé de processos da Justiça Federal no TRF5, com jurisdição sobre AL, CE, PB, PE, RN e SE. Atuamos no sistema PJe e acompanhamos até a emissão.",
  },
  {
    slug: "trf6",
    sigla: "TRF6",
    nome: "Tribunal Regional Federal da 6ª Região",
    tipo: "federal",
    sede: "Belo Horizonte",
    sistema: "PJe",
    prazo: "3 a 10 dias úteis",
    abrangencia: "Minas Gerais",
    comarcas: ["Belo Horizonte"],
    resumo: "Certidão de Objeto e Pé de processos da Justiça Federal no TRF6, com jurisdição sobre Minas Gerais. Atuamos no sistema PJe e acompanhamos até a emissão.",
  },
  {
    slug: "trt1",
    sigla: "TRT1",
    nome: "Tribunal Regional do Trabalho da 1ª Região",
    tipo: "trabalhista",
    sede: "Rio de Janeiro",
    sistema: "PJe (Justiça do Trabalho)",
    prazo: "3 a 10 dias úteis",
    abrangencia: "Rio de Janeiro",
    comarcas: ["Rio de Janeiro"],
    resumo: "Certidão de Objeto e Pé de reclamações trabalhistas no TRT1, que abrange Rio de Janeiro. Os processos tramitam no PJe da Justiça do Trabalho e o pedido é feito 100% online.",
  },
  {
    slug: "trt2",
    sigla: "TRT2",
    nome: "Tribunal Regional do Trabalho da 2ª Região",
    tipo: "trabalhista",
    sede: "São Paulo",
    sistema: "PJe (Justiça do Trabalho)",
    prazo: "3 a 10 dias úteis",
    abrangencia: "São Paulo (capital e Grande SP)",
    comarcas: ["São Paulo"],
    resumo: "Certidão de Objeto e Pé de reclamações trabalhistas no TRT2, que abrange São Paulo (capital e Grande SP). Os processos tramitam no PJe da Justiça do Trabalho e o pedido é feito 100% online.",
  },
  {
    slug: "trt3",
    sigla: "TRT3",
    nome: "Tribunal Regional do Trabalho da 3ª Região",
    tipo: "trabalhista",
    sede: "Belo Horizonte",
    sistema: "PJe (Justiça do Trabalho)",
    prazo: "3 a 10 dias úteis",
    abrangencia: "Minas Gerais",
    comarcas: ["Belo Horizonte"],
    resumo: "Certidão de Objeto e Pé de reclamações trabalhistas no TRT3, que abrange Minas Gerais. Os processos tramitam no PJe da Justiça do Trabalho e o pedido é feito 100% online.",
  },
  {
    slug: "trt4",
    sigla: "TRT4",
    nome: "Tribunal Regional do Trabalho da 4ª Região",
    tipo: "trabalhista",
    sede: "Porto Alegre",
    sistema: "PJe (Justiça do Trabalho)",
    prazo: "3 a 10 dias úteis",
    abrangencia: "Rio Grande do Sul",
    comarcas: ["Porto Alegre"],
    resumo: "Certidão de Objeto e Pé de reclamações trabalhistas no TRT4, que abrange Rio Grande do Sul. Os processos tramitam no PJe da Justiça do Trabalho e o pedido é feito 100% online.",
  },
  {
    slug: "trt5",
    sigla: "TRT5",
    nome: "Tribunal Regional do Trabalho da 5ª Região",
    tipo: "trabalhista",
    sede: "Salvador",
    sistema: "PJe (Justiça do Trabalho)",
    prazo: "3 a 10 dias úteis",
    abrangencia: "Bahia",
    comarcas: ["Salvador"],
    resumo: "Certidão de Objeto e Pé de reclamações trabalhistas no TRT5, que abrange Bahia. Os processos tramitam no PJe da Justiça do Trabalho e o pedido é feito 100% online.",
  },
  {
    slug: "trt6",
    sigla: "TRT6",
    nome: "Tribunal Regional do Trabalho da 6ª Região",
    tipo: "trabalhista",
    sede: "Recife",
    sistema: "PJe (Justiça do Trabalho)",
    prazo: "3 a 10 dias úteis",
    abrangencia: "Pernambuco",
    comarcas: ["Recife"],
    resumo: "Certidão de Objeto e Pé de reclamações trabalhistas no TRT6, que abrange Pernambuco. Os processos tramitam no PJe da Justiça do Trabalho e o pedido é feito 100% online.",
  },
  {
    slug: "trt7",
    sigla: "TRT7",
    nome: "Tribunal Regional do Trabalho da 7ª Região",
    tipo: "trabalhista",
    sede: "Fortaleza",
    sistema: "PJe (Justiça do Trabalho)",
    prazo: "3 a 10 dias úteis",
    abrangencia: "Ceará",
    comarcas: ["Fortaleza"],
    resumo: "Certidão de Objeto e Pé de reclamações trabalhistas no TRT7, que abrange Ceará. Os processos tramitam no PJe da Justiça do Trabalho e o pedido é feito 100% online.",
  },
  {
    slug: "trt8",
    sigla: "TRT8",
    nome: "Tribunal Regional do Trabalho da 8ª Região",
    tipo: "trabalhista",
    sede: "Belém",
    sistema: "PJe (Justiça do Trabalho)",
    prazo: "3 a 10 dias úteis",
    abrangencia: "Pará e Amapá",
    comarcas: ["Belém"],
    resumo: "Certidão de Objeto e Pé de reclamações trabalhistas no TRT8, que abrange Pará e Amapá. Os processos tramitam no PJe da Justiça do Trabalho e o pedido é feito 100% online.",
  },
  {
    slug: "trt9",
    sigla: "TRT9",
    nome: "Tribunal Regional do Trabalho da 9ª Região",
    tipo: "trabalhista",
    sede: "Curitiba",
    sistema: "PJe (Justiça do Trabalho)",
    prazo: "3 a 10 dias úteis",
    abrangencia: "Paraná",
    comarcas: ["Curitiba"],
    resumo: "Certidão de Objeto e Pé de reclamações trabalhistas no TRT9, que abrange Paraná. Os processos tramitam no PJe da Justiça do Trabalho e o pedido é feito 100% online.",
  },
  {
    slug: "trt10",
    sigla: "TRT10",
    nome: "Tribunal Regional do Trabalho da 10ª Região",
    tipo: "trabalhista",
    sede: "Brasília",
    sistema: "PJe (Justiça do Trabalho)",
    prazo: "3 a 10 dias úteis",
    abrangencia: "Distrito Federal e Tocantins",
    comarcas: ["Brasília"],
    resumo: "Certidão de Objeto e Pé de reclamações trabalhistas no TRT10, que abrange Distrito Federal e Tocantins. Os processos tramitam no PJe da Justiça do Trabalho e o pedido é feito 100% online.",
  },
  {
    slug: "trt11",
    sigla: "TRT11",
    nome: "Tribunal Regional do Trabalho da 11ª Região",
    tipo: "trabalhista",
    sede: "Manaus",
    sistema: "PJe (Justiça do Trabalho)",
    prazo: "3 a 10 dias úteis",
    abrangencia: "Amazonas e Roraima",
    comarcas: ["Manaus"],
    resumo: "Certidão de Objeto e Pé de reclamações trabalhistas no TRT11, que abrange Amazonas e Roraima. Os processos tramitam no PJe da Justiça do Trabalho e o pedido é feito 100% online.",
  },
  {
    slug: "trt12",
    sigla: "TRT12",
    nome: "Tribunal Regional do Trabalho da 12ª Região",
    tipo: "trabalhista",
    sede: "Florianópolis",
    sistema: "PJe (Justiça do Trabalho)",
    prazo: "3 a 10 dias úteis",
    abrangencia: "Santa Catarina",
    comarcas: ["Florianópolis"],
    resumo: "Certidão de Objeto e Pé de reclamações trabalhistas no TRT12, que abrange Santa Catarina. Os processos tramitam no PJe da Justiça do Trabalho e o pedido é feito 100% online.",
  },
  {
    slug: "trt13",
    sigla: "TRT13",
    nome: "Tribunal Regional do Trabalho da 13ª Região",
    tipo: "trabalhista",
    sede: "João Pessoa",
    sistema: "PJe (Justiça do Trabalho)",
    prazo: "3 a 10 dias úteis",
    abrangencia: "Paraíba",
    comarcas: ["João Pessoa"],
    resumo: "Certidão de Objeto e Pé de reclamações trabalhistas no TRT13, que abrange Paraíba. Os processos tramitam no PJe da Justiça do Trabalho e o pedido é feito 100% online.",
  },
  {
    slug: "trt14",
    sigla: "TRT14",
    nome: "Tribunal Regional do Trabalho da 14ª Região",
    tipo: "trabalhista",
    sede: "Porto Velho",
    sistema: "PJe (Justiça do Trabalho)",
    prazo: "3 a 10 dias úteis",
    abrangencia: "Rondônia e Acre",
    comarcas: ["Porto Velho"],
    resumo: "Certidão de Objeto e Pé de reclamações trabalhistas no TRT14, que abrange Rondônia e Acre. Os processos tramitam no PJe da Justiça do Trabalho e o pedido é feito 100% online.",
  },
  {
    slug: "trt15",
    sigla: "TRT15",
    nome: "Tribunal Regional do Trabalho da 15ª Região",
    tipo: "trabalhista",
    sede: "Campinas",
    sistema: "PJe (Justiça do Trabalho)",
    prazo: "3 a 10 dias úteis",
    abrangencia: "Interior de São Paulo",
    comarcas: ["Campinas"],
    resumo: "Certidão de Objeto e Pé de reclamações trabalhistas no TRT15, que abrange Interior de São Paulo. Os processos tramitam no PJe da Justiça do Trabalho e o pedido é feito 100% online.",
  },
  {
    slug: "trt16",
    sigla: "TRT16",
    nome: "Tribunal Regional do Trabalho da 16ª Região",
    tipo: "trabalhista",
    sede: "São Luís",
    sistema: "PJe (Justiça do Trabalho)",
    prazo: "3 a 10 dias úteis",
    abrangencia: "Maranhão",
    comarcas: ["São Luís"],
    resumo: "Certidão de Objeto e Pé de reclamações trabalhistas no TRT16, que abrange Maranhão. Os processos tramitam no PJe da Justiça do Trabalho e o pedido é feito 100% online.",
  },
  {
    slug: "trt17",
    sigla: "TRT17",
    nome: "Tribunal Regional do Trabalho da 17ª Região",
    tipo: "trabalhista",
    sede: "Vitória",
    sistema: "PJe (Justiça do Trabalho)",
    prazo: "3 a 10 dias úteis",
    abrangencia: "Espírito Santo",
    comarcas: ["Vitória"],
    resumo: "Certidão de Objeto e Pé de reclamações trabalhistas no TRT17, que abrange Espírito Santo. Os processos tramitam no PJe da Justiça do Trabalho e o pedido é feito 100% online.",
  },
  {
    slug: "trt18",
    sigla: "TRT18",
    nome: "Tribunal Regional do Trabalho da 18ª Região",
    tipo: "trabalhista",
    sede: "Goiânia",
    sistema: "PJe (Justiça do Trabalho)",
    prazo: "3 a 10 dias úteis",
    abrangencia: "Goiás",
    comarcas: ["Goiânia"],
    resumo: "Certidão de Objeto e Pé de reclamações trabalhistas no TRT18, que abrange Goiás. Os processos tramitam no PJe da Justiça do Trabalho e o pedido é feito 100% online.",
  },
  {
    slug: "trt19",
    sigla: "TRT19",
    nome: "Tribunal Regional do Trabalho da 19ª Região",
    tipo: "trabalhista",
    sede: "Maceió",
    sistema: "PJe (Justiça do Trabalho)",
    prazo: "3 a 10 dias úteis",
    abrangencia: "Alagoas",
    comarcas: ["Maceió"],
    resumo: "Certidão de Objeto e Pé de reclamações trabalhistas no TRT19, que abrange Alagoas. Os processos tramitam no PJe da Justiça do Trabalho e o pedido é feito 100% online.",
  },
  {
    slug: "trt20",
    sigla: "TRT20",
    nome: "Tribunal Regional do Trabalho da 20ª Região",
    tipo: "trabalhista",
    sede: "Aracaju",
    sistema: "PJe (Justiça do Trabalho)",
    prazo: "3 a 10 dias úteis",
    abrangencia: "Sergipe",
    comarcas: ["Aracaju"],
    resumo: "Certidão de Objeto e Pé de reclamações trabalhistas no TRT20, que abrange Sergipe. Os processos tramitam no PJe da Justiça do Trabalho e o pedido é feito 100% online.",
  },
  {
    slug: "trt21",
    sigla: "TRT21",
    nome: "Tribunal Regional do Trabalho da 21ª Região",
    tipo: "trabalhista",
    sede: "Natal",
    sistema: "PJe (Justiça do Trabalho)",
    prazo: "3 a 10 dias úteis",
    abrangencia: "Rio Grande do Norte",
    comarcas: ["Natal"],
    resumo: "Certidão de Objeto e Pé de reclamações trabalhistas no TRT21, que abrange Rio Grande do Norte. Os processos tramitam no PJe da Justiça do Trabalho e o pedido é feito 100% online.",
  },
  {
    slug: "trt22",
    sigla: "TRT22",
    nome: "Tribunal Regional do Trabalho da 22ª Região",
    tipo: "trabalhista",
    sede: "Teresina",
    sistema: "PJe (Justiça do Trabalho)",
    prazo: "3 a 10 dias úteis",
    abrangencia: "Piauí",
    comarcas: ["Teresina"],
    resumo: "Certidão de Objeto e Pé de reclamações trabalhistas no TRT22, que abrange Piauí. Os processos tramitam no PJe da Justiça do Trabalho e o pedido é feito 100% online.",
  },
  {
    slug: "trt23",
    sigla: "TRT23",
    nome: "Tribunal Regional do Trabalho da 23ª Região",
    tipo: "trabalhista",
    sede: "Cuiabá",
    sistema: "PJe (Justiça do Trabalho)",
    prazo: "3 a 10 dias úteis",
    abrangencia: "Mato Grosso",
    comarcas: ["Cuiabá"],
    resumo: "Certidão de Objeto e Pé de reclamações trabalhistas no TRT23, que abrange Mato Grosso. Os processos tramitam no PJe da Justiça do Trabalho e o pedido é feito 100% online.",
  },
  {
    slug: "trt24",
    sigla: "TRT24",
    nome: "Tribunal Regional do Trabalho da 24ª Região",
    tipo: "trabalhista",
    sede: "Campo Grande",
    sistema: "PJe (Justiça do Trabalho)",
    prazo: "3 a 10 dias úteis",
    abrangencia: "Mato Grosso do Sul",
    comarcas: ["Campo Grande"],
    resumo: "Certidão de Objeto e Pé de reclamações trabalhistas no TRT24, que abrange Mato Grosso do Sul. Os processos tramitam no PJe da Justiça do Trabalho e o pedido é feito 100% online.",
  },
  {
    slug: "stf",
    sigla: "STF",
    nome: "Supremo Tribunal Federal",
    tipo: "superior",
    sede: "Brasília",
    sistema: "Peticionamento eletrônico STF",
    prazo: "5 a 15 dias úteis",
    abrangencia: "Todo o Brasil",
    comarcas: ["Brasília"],
    resumo: "Certidão de Objeto e Pé de processos no STF (Supremo Tribunal Federal), competente para controle de constitucionalidade, habeas corpus e recursos extraordinários. Solicitação online com acompanhamento até a emissão.",
  },
  {
    slug: "stj",
    sigla: "STJ",
    nome: "Superior Tribunal de Justiça",
    tipo: "superior",
    sede: "Brasília",
    sistema: "Peticionamento eletrônico STJ",
    prazo: "5 a 15 dias úteis",
    abrangencia: "Todo o Brasil",
    comarcas: ["Brasília"],
    resumo: "Certidão de Objeto e Pé de processos no STJ (Superior Tribunal de Justiça), competente para recursos especiais, habeas corpus e conflitos de competência. Solicitação online com acompanhamento até a emissão.",
  },
  {
    slug: "tst",
    sigla: "TST",
    nome: "Tribunal Superior do Trabalho",
    tipo: "superior",
    sede: "Brasília",
    sistema: "PJe",
    prazo: "5 a 15 dias úteis",
    abrangencia: "Todo o Brasil",
    comarcas: ["Brasília"],
    resumo: "Certidão de Objeto e Pé de processos no TST (Tribunal Superior do Trabalho), competente para recursos de revista e dissídios coletivos trabalhistas. Solicitação online com acompanhamento até a emissão.",
  },
  {
    slug: "stm",
    sigla: "STM",
    nome: "Superior Tribunal Militar",
    tipo: "superior",
    sede: "Brasília",
    sistema: "e-Proc STM",
    prazo: "5 a 15 dias úteis",
    abrangencia: "Todo o Brasil",
    comarcas: ["Brasília"],
    resumo: "Certidão de Objeto e Pé de processos no STM (Superior Tribunal Militar), competente para processos da Justiça Militar da União. Solicitação online com acompanhamento até a emissão.",
  },
  {
    slug: "tse",
    sigla: "TSE",
    nome: "Tribunal Superior Eleitoral",
    tipo: "superior",
    sede: "Brasília",
    sistema: "PJe eleitoral",
    prazo: "5 a 15 dias úteis",
    abrangencia: "Todo o Brasil",
    comarcas: ["Brasília"],
    resumo: "Certidão de Objeto e Pé de processos no TSE (Tribunal Superior Eleitoral), competente para processos eleitorais, registros de candidatura e prestação de contas. Solicitação online com acompanhamento até a emissão.",
  },
];

export const tribunalPorSlug = (slug: string) =>
  TRIBUNAIS.find((t) => t.slug === slug.toLowerCase());

export const tribunaisPorTipo = (tipo: TipoTribunal) =>
  TRIBUNAIS.filter((t) => t.tipo === tipo);
