-- Códigos de origem (OOOO) publicados nos seletores oficiais de foro do e-SAJ (TJSP e TJAC), coletados em 2026-09-28.
-- Idempotente: não altera nem apaga registros existentes.
INSERT INTO public.cnj_comarcas (tribunal_id, codigo_origem, nome, cidade, uf, foro, fonte_url, fonte_atualizada_em)
SELECT t.id, v.codigo, v.nome, v.cidade, v.uf, v.foro, v.fonte, DATE '2026-09-28'
FROM (VALUES
('TJSP','0053','Foro Central - Fazenda Pública/Acidentes','São Paulo','SP','Foro Central - Fazenda Pública/Acidentes','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0017','Foro Central - Protocolo Cível','São Paulo','SP','Foro Central - Protocolo Cível','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0100','Foro Central Cível','São Paulo','SP','Foro Central Cível','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0013','Foro Central Civel Palácio Mauá','São Paulo','SP','Foro Central Civel Palácio Mauá','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0052','Foro Central Criminal - Juri','São Paulo','SP','Foro Central Criminal - Juri','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0050','Foro Central Criminal Barra Funda','São Paulo','SP','Foro Central Criminal Barra Funda','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0018','Foro Central II - PROCON','São Paulo','SP','Foro Central II - PROCON','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0016','Foro Central Juizados Especiais Cíveis','São Paulo','SP','Foro Central Juizados Especiais Cíveis','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0258','Foro da Casa da Mulher Brasileira',NULL,'SP','Foro da Casa da Mulher Brasileira','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0800','Foro da Comissão Processante Permanente',NULL,'SP','Foro da Comissão Processante Permanente','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0014','Foro das Execuções Fiscais Estaduais',NULL,'SP','Foro das Execuções Fiscais Estaduais','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0090','Foro das Execuções Fiscais Municipais',NULL,'SP','Foro das Execuções Fiscais Municipais','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0081','Foro de Adamantina','Adamantina','SP','Foro de Adamantina','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0083','Foro de Aguaí','Aguaí','SP','Foro de Aguaí','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0035','Foro de Águas de Lindoia','Águas de Lindoia','SP','Foro de Águas de Lindoia','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0058','Foro de Agudos','Agudos','SP','Foro de Agudos','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0042','Foro de Altinópolis','Altinópolis','SP','Foro de Altinópolis','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0019','Foro de Americana','Americana','SP','Foro de Americana','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0040','Foro de Américo Brasiliense','Américo Brasiliense','SP','Foro de Américo Brasiliense','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0022','Foro de Amparo','Amparo','SP','Foro de Amparo','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0024','Foro de Andradina','Andradina','SP','Foro de Andradina','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0025','Foro de Angatuba','Angatuba','SP','Foro de Angatuba','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0028','Foro de Aparecida','Aparecida','SP','Foro de Aparecida','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0030','Foro de Apiaí','Apiaí','SP','Foro de Apiaí','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0032','Foro de Araçatuba','Araçatuba','SP','Foro de Araçatuba','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0037','Foro de Araraquara','Araraquara','SP','Foro de Araraquara','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0038','Foro de Araras','Araras','SP','Foro de Araras','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0666','Foro de Artur Nogueira','Artur Nogueira','SP','Foro de Artur Nogueira','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0045','Foro de Arujá','Arujá','SP','Foro de Arujá','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0705','Foro de Aspásia','Aspásia','SP','Foro de Aspásia','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0047','Foro de Assis','Assis','SP','Foro de Assis','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0460','Foro de Atendimento Itinerante à Mulher','Atendimento Itinerante à Mulher','SP','Foro de Atendimento Itinerante à Mulher','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0048','Foro de Atibaia','Atibaia','SP','Foro de Atibaia','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0060','Foro de Auriflama','Auriflama','SP','Foro de Auriflama','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0073','Foro de Avaré','Avaré','SP','Foro de Avaré','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0059','Foro de Bananal','Bananal','SP','Foro de Bananal','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0062','Foro de Bariri','Bariri','SP','Foro de Bariri','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0063','Foro de Barra Bonita','Barra Bonita','SP','Foro de Barra Bonita','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0066','Foro de Barretos','Barretos','SP','Foro de Barretos','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0068','Foro de Barueri','Barueri','SP','Foro de Barueri','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0069','Foro de Bastos','Bastos','SP','Foro de Bastos','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0070','Foro de Batatais','Batatais','SP','Foro de Batatais','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0071','Foro de Bauru','Bauru','SP','Foro de Bauru','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0072','Foro de Bebedouro','Bebedouro','SP','Foro de Bebedouro','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0706','Foro de Bernardino de Campos','Bernardino de Campos','SP','Foro de Bernardino de Campos','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0075','Foro de Bertioga','Bertioga','SP','Foro de Bertioga','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0076','Foro de Bilac','Bilac','SP','Foro de Bilac','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0077','Foro de Birigui','Birigui','SP','Foro de Birigui','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0082','Foro de Boituva','Boituva','SP','Foro de Boituva','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0067','Foro de Borborema','Borborema','SP','Foro de Borborema','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0079','Foro de Botucatu','Botucatu','SP','Foro de Botucatu','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0099','Foro de Bragança Paulista','Bragança Paulista','SP','Foro de Bragança Paulista','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0094','Foro de Brodowski','Brodowski','SP','Foro de Brodowski','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0095','Foro de Brotas','Brotas','SP','Foro de Brotas','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0691','Foro de Buri','Buri','SP','Foro de Buri','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0097','Foro de Buritama','Buritama','SP','Foro de Buritama','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0080','Foro de Cabreúva','Cabreúva','SP','Foro de Cabreúva','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0101','Foro de Caçapava','Caçapava','SP','Foro de Caçapava','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0102','Foro de Cachoeira Paulista','Cachoeira Paulista','SP','Foro de Cachoeira Paulista','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0103','Foro de Caconde','Caconde','SP','Foro de Caconde','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0104','Foro de Cafelândia','Cafelândia','SP','Foro de Cafelândia','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0106','Foro de Caieiras','Caieiras','SP','Foro de Caieiras','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0108','Foro de Cajamar','Cajamar','SP','Foro de Cajamar','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0111','Foro de Cajuru','Cajuru','SP','Foro de Cajuru','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0114','Foro de Campinas','Campinas','SP','Foro de Campinas','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0115','Foro de Campo Limpo Paulista','Campo Limpo Paulista','SP','Foro de Campo Limpo Paulista','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0116','Foro de Campos do Jordão','Campos do Jordão','SP','Foro de Campos do Jordão','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0118','Foro de Cananéia','Cananéia','SP','Foro de Cananéia','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0120','Foro de Cândido Mota','Cândido Mota','SP','Foro de Cândido Mota','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0123','Foro de Capão Bonito','Capão Bonito','SP','Foro de Capão Bonito','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0125','Foro de Capivari','Capivari','SP','Foro de Capivari','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0126','Foro de Caraguatatuba','Caraguatatuba','SP','Foro de Caraguatatuba','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0127','Foro de Carapicuíba','Carapicuíba','SP','Foro de Carapicuíba','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0128','Foro de Cardoso','Cardoso','SP','Foro de Cardoso','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0129','Foro de Casa Branca','Casa Branca','SP','Foro de Casa Branca','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0132','Foro de Catanduva','Catanduva','SP','Foro de Catanduva','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0136','Foro de Cerqueira César','Cerqueira César','SP','Foro de Cerqueira César','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0137','Foro de Cerquilho','Cerquilho','SP','Foro de Cerquilho','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0232','Foro de Cesário Lange','Cesário Lange','SP','Foro de Cesário Lange','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0527','Foro de Cesário Lange','Cesário Lange','SP','Foro de Cesário Lange','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0140','Foro de Chavantes','Chavantes','SP','Foro de Chavantes','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0142','Foro de Colina','Colina','SP','Foro de Colina','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0144','Foro de Conchal','Conchal','SP','Foro de Conchal','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0145','Foro de Conchas','Conchas','SP','Foro de Conchas','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0146','Foro de Cordeirópolis','Cordeirópolis','SP','Foro de Cordeirópolis','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0150','Foro de Cosmópolis','Cosmópolis','SP','Foro de Cosmópolis','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0152','Foro de Cotia','Cotia','SP','Foro de Cotia','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0153','Foro de Cravinhos','Cravinhos','SP','Foro de Cravinhos','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0156','Foro de Cruzeiro','Cruzeiro','SP','Foro de Cruzeiro','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0157','Foro de Cubatão','Cubatão','SP','Foro de Cubatão','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0159','Foro de Cunha','Cunha','SP','Foro de Cunha','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0160','Foro de Descalvado','Descalvado','SP','Foro de Descalvado','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0161','Foro de Diadema','Diadema','SP','Foro de Diadema','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0165','Foro de Dois Córregos','Dois Córregos','SP','Foro de Dois Córregos','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0168','Foro de Dracena','Dracena','SP','Foro de Dracena','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0169','Foro de Duartina','Duartina','SP','Foro de Duartina','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0172','Foro de Eldorado Paulista','Eldorado Paulista','SP','Foro de Eldorado Paulista','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0176','Foro de Embu das Artes','Embu das Artes','SP','Foro de Embu das Artes','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0177','Foro de Embu-Guaçu','Embu-Guaçu','SP','Foro de Embu-Guaçu','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0180','Foro de Espírito Santo do Pinhal','Espírito Santo do Pinhal','SP','Foro de Espírito Santo do Pinhal','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0185','Foro de Estrela D\u0027Oeste','Estrela D\u0027Oeste','SP','Foro de Estrela D\u0027Oeste','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0187','Foro de Fartura','Fartura','SP','Foro de Fartura','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0189','Foro de Fernandópolis','Fernandópolis','SP','Foro de Fernandópolis','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0191','Foro de Ferraz de Vasconcelos','Ferraz de Vasconcelos','SP','Foro de Ferraz de Vasconcelos','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0673','Foro de Flórida Paulista','Flórida Paulista','SP','Foro de Flórida Paulista','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0196','Foro de Franca','Franca','SP','Foro de Franca','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0197','Foro de Francisco Morato','Francisco Morato','SP','Foro de Francisco Morato','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0198','Foro de Franco da Rocha','Franco da Rocha','SP','Foro de Franco da Rocha','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0200','Foro de Gália','Gália','SP','Foro de Gália','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0201','Foro de Garça','Garça','SP','Foro de Garça','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0204','Foro de General Salgado','General Salgado','SP','Foro de General Salgado','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0205','Foro de Getulina','Getulina','SP','Foro de Getulina','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0210','Foro de Guaíra','Guaíra','SP','Foro de Guaíra','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0213','Foro de Guará','Guará','SP','Foro de Guará','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0218','Foro de Guararapes','Guararapes','SP','Foro de Guararapes','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0219','Foro de Guararema','Guararema','SP','Foro de Guararema','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0220','Foro de Guaratinguetá','Guaratinguetá','SP','Foro de Guaratinguetá','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0222','Foro de Guariba','Guariba','SP','Foro de Guariba','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0223','Foro de Guarujá','Guarujá','SP','Foro de Guarujá','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0224','Foro de Guarulhos','Guarulhos','SP','Foro de Guarulhos','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0229','Foro de Hortolândia','Hortolândia','SP','Foro de Hortolândia','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0027','Foro de Iacanga','Iacanga','SP','Foro de Iacanga','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0233','Foro de Ibaté','Ibaté','SP','Foro de Ibaté','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0236','Foro de Ibitinga','Ibitinga','SP','Foro de Ibitinga','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0238','Foro de Ibiúna','Ibiúna','SP','Foro de Ibiúna','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0240','Foro de Iepê','Iepê','SP','Foro de Iepê','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0242','Foro de Igarapava','Igarapava','SP','Foro de Igarapava','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0244','Foro de Iguape','Iguape','SP','Foro de Iguape','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0246','Foro de Ilha Solteira','Ilha Solteira','SP','Foro de Ilha Solteira','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0247','Foro de Ilhabela','Ilhabela','SP','Foro de Ilhabela','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0248','Foro de Indaiatuba','Indaiatuba','SP','Foro de Indaiatuba','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0252','Foro de Ipaussu','Ipaussu','SP','Foro de Ipaussu','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0257','Foro de Ipuã','Ipuã','SP','Foro de Ipuã','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0262','Foro de Itaberá','Itaberá','SP','Foro de Itaberá','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0263','Foro de Itaí','Itaí','SP','Foro de Itaí','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0264','Foro de Itajobi','Itajobi','SP','Foro de Itajobi','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0266','Foro de Itanhaém','Itanhaém','SP','Foro de Itanhaém','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0268','Foro de Itapecerica da Serra','Itapecerica da Serra','SP','Foro de Itapecerica da Serra','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0269','Foro de Itapetininga','Itapetininga','SP','Foro de Itapetininga','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0270','Foro de Itapeva','Itapeva','SP','Foro de Itapeva','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0271','Foro de Itapevi','Itapevi','SP','Foro de Itapevi','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0272','Foro de Itapira','Itapira','SP','Foro de Itapira','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0274','Foro de Itápolis','Itápolis','SP','Foro de Itápolis','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0275','Foro de Itaporanga','Itaporanga','SP','Foro de Itaporanga','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0278','Foro de Itaquaquecetuba','Itaquaquecetuba','SP','Foro de Itaquaquecetuba','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0279','Foro de Itararé','Itararé','SP','Foro de Itararé','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0280','Foro de Itariri','Itariri','SP','Foro de Itariri','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0281','Foro de Itatiba','Itatiba','SP','Foro de Itatiba','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0282','Foro de Itatinga','Itatinga','SP','Foro de Itatinga','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0283','Foro de Itirapina','Itirapina','SP','Foro de Itirapina','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0286','Foro de Itu','Itu','SP','Foro de Itu','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0514','Foro de Itupeva','Itupeva','SP','Foro de Itupeva','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0288','Foro de Ituverava','Ituverava','SP','Foro de Ituverava','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0291','Foro de Jaboticabal','Jaboticabal','SP','Foro de Jaboticabal','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0292','Foro de Jacareí','Jacareí','SP','Foro de Jacareí','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0294','Foro de Jacupiranga','Jacupiranga','SP','Foro de Jacupiranga','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0296','Foro de Jaguariúna','Jaguariúna','SP','Foro de Jaguariúna','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0297','Foro de Jales','Jales','SP','Foro de Jales','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0299','Foro de Jandira','Jandira','SP','Foro de Jandira','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0300','Foro de Jardinópolis','Jardinópolis','SP','Foro de Jardinópolis','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0301','Foro de Jarinu','Jarinu','SP','Foro de Jarinu','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0302','Foro de Jaú','Jaú','SP','Foro de Jaú','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0306','Foro de José Bonifácio','José Bonifácio','SP','Foro de José Bonifácio','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0309','Foro de Jundiaí','Jundiaí','SP','Foro de Jundiaí','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0311','Foro de Junqueirópolis','Junqueirópolis','SP','Foro de Junqueirópolis','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0312','Foro de Juquiá','Juquiá','SP','Foro de Juquiá','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0315','Foro de Laranjal Paulista','Laranjal Paulista','SP','Foro de Laranjal Paulista','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0318','Foro de Leme','Leme','SP','Foro de Leme','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0319','Foro de Lençóis Paulista','Lençóis Paulista','SP','Foro de Lençóis Paulista','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0320','Foro de Limeira','Limeira','SP','Foro de Limeira','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0322','Foro de Lins','Lins','SP','Foro de Lins','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0323','Foro de Lorena','Lorena','SP','Foro de Lorena','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0681','Foro de Louveira','Louveira','SP','Foro de Louveira','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0326','Foro de Lucélia','Lucélia','SP','Foro de Lucélia','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0333','Foro de Macatuba','Macatuba','SP','Foro de Macatuba','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0334','Foro de Macaubal','Macaubal','SP','Foro de Macaubal','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0337','Foro de Mairinque','Mairinque','SP','Foro de Mairinque','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0338','Foro de Mairiporã','Mairiporã','SP','Foro de Mairiporã','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0341','Foro de Maracaí','Maracaí','SP','Foro de Maracaí','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0344','Foro de Marília','Marília','SP','Foro de Marília','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0346','Foro de Martinópolis','Martinópolis','SP','Foro de Martinópolis','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0347','Foro de Matão','Matão','SP','Foro de Matão','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0348','Foro de Mauá','Mauá','SP','Foro de Mauá','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0352','Foro de Miguelópolis','Miguelópolis','SP','Foro de Miguelópolis','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0355','Foro de Miracatu','Miracatu','SP','Foro de Miracatu','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0356','Foro de Mirandópolis','Mirandópolis','SP','Foro de Mirandópolis','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0357','Foro de Mirante do Paranapanema','Mirante do Paranapanema','SP','Foro de Mirante do Paranapanema','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0358','Foro de Mirassol','Mirassol','SP','Foro de Mirassol','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0360','Foro de Mococa','Mococa','SP','Foro de Mococa','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0361','Foro de Mogi das Cruzes','Mogi das Cruzes','SP','Foro de Mogi das Cruzes','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0362','Foro de Mogi Guaçu','Mogi Guaçu','SP','Foro de Mogi Guaçu','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0363','Foro de Mogi Mirim','Mogi Mirim','SP','Foro de Mogi Mirim','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0366','Foro de Mongaguá','Mongaguá','SP','Foro de Mongaguá','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0368','Foro de Monte Alto','Monte Alto','SP','Foro de Monte Alto','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0369','Foro de Monte Aprazível','Monte Aprazível','SP','Foro de Monte Aprazível','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0370','Foro de Monte Azul Paulista','Monte Azul Paulista','SP','Foro de Monte Azul Paulista','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0372','Foro de Monte Mor','Monte Mor','SP','Foro de Monte Mor','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0374','Foro de Morro Agudo','Morro Agudo','SP','Foro de Morro Agudo','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0695','Foro de Nazaré Paulista','Nazaré Paulista','SP','Foro de Nazaré Paulista','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0382','Foro de Neves Paulista','Neves Paulista','SP','Foro de Neves Paulista','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0383','Foro de Nhandeara','Nhandeara','SP','Foro de Nhandeara','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0390','Foro de Nova Granada','Nova Granada','SP','Foro de Nova Granada','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0394','Foro de Nova Odessa','Nova Odessa','SP','Foro de Nova Odessa','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0396','Foro de Novo Horizonte','Novo Horizonte','SP','Foro de Novo Horizonte','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0397','Foro de Nuporanga','Nuporanga','SP','Foro de Nuporanga','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0400','Foro de Olímpia','Olímpia','SP','Foro de Olímpia','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0404','Foro de Orlândia','Orlândia','SP','Foro de Orlândia','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0405','Foro de Osasco','Osasco','SP','Foro de Osasco','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0407','Foro de Osvaldo Cruz','Osvaldo Cruz','SP','Foro de Osvaldo Cruz','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0408','Foro de Ourinhos','Ourinhos','SP','Foro de Ourinhos','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0696','Foro de Ouroeste','Ouroeste','SP','Foro de Ouroeste','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0411','Foro de Pacaembu','Pacaembu','SP','Foro de Pacaembu','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0412','Foro de Palestina','Palestina','SP','Foro de Palestina','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0414','Foro de Palmeira D\u0027Oeste','Palmeira D\u0027Oeste','SP','Foro de Palmeira D\u0027Oeste','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0415','Foro de Palmital','Palmital','SP','Foro de Palmital','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0416','Foro de Panorama','Panorama','SP','Foro de Panorama','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0417','Foro de Paraguaçu Paulista','Paraguaçu Paulista','SP','Foro de Paraguaçu Paulista','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0418','Foro de Paraibuna','Paraibuna','SP','Foro de Paraibuna','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0420','Foro de Paranapanema','Paranapanema','SP','Foro de Paranapanema','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0424','Foro de Pariquera-Açu','Pariquera-Açu','SP','Foro de Pariquera-Açu','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0426','Foro de Patrocínio Paulista','Patrocínio Paulista','SP','Foro de Patrocínio Paulista','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0428','Foro de Paulínia','Paulínia','SP','Foro de Paulínia','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0430','Foro de Paulo de Faria','Paulo de Faria','SP','Foro de Paulo de Faria','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0431','Foro de Pederneiras','Pederneiras','SP','Foro de Pederneiras','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0434','Foro de Pedregulho','Pedregulho','SP','Foro de Pedregulho','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0435','Foro de Pedreira','Pedreira','SP','Foro de Pedreira','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0438','Foro de Penápolis','Penápolis','SP','Foro de Penápolis','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0439','Foro de Pereira Barreto','Pereira Barreto','SP','Foro de Pereira Barreto','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0441','Foro de Peruíbe','Peruíbe','SP','Foro de Peruíbe','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0443','Foro de Piedade','Piedade','SP','Foro de Piedade','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0444','Foro de Pilar do Sul','Pilar do Sul','SP','Foro de Pilar do Sul','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0445','Foro de Pindamonhangaba','Pindamonhangaba','SP','Foro de Pindamonhangaba','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0707','Foro de Pindorama','Pindorama','SP','Foro de Pindorama','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0447','Foro de Pinhalzinho','Pinhalzinho','SP','Foro de Pinhalzinho','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0449','Foro de Piquete','Piquete','SP','Foro de Piquete','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0450','Foro de Piracaia','Piracaia','SP','Foro de Piracaia','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0451','Foro de Piracicaba','Piracicaba','SP','Foro de Piracicaba','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0452','Foro de Piraju','Piraju','SP','Foro de Piraju','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0453','Foro de Pirajuí','Pirajuí','SP','Foro de Pirajuí','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0698','Foro de Pirangi','Pirangi','SP','Foro de Pirangi','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0456','Foro de Pirapozinho','Pirapozinho','SP','Foro de Pirapozinho','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0457','Foro de Pirassununga','Pirassununga','SP','Foro de Pirassununga','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0458','Foro de Piratininga','Piratininga','SP','Foro de Piratininga','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0459','Foro de Pitangueiras','Pitangueiras','SP','Foro de Pitangueiras','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0462','Foro de Poá','Poá','SP','Foro de Poá','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0464','Foro de Pompéia','Pompéia','SP','Foro de Pompéia','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0466','Foro de Pontal','Pontal','SP','Foro de Pontal','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0470','Foro de Porangaba','Porangaba','SP','Foro de Porangaba','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0471','Foro de Porto Feliz','Porto Feliz','SP','Foro de Porto Feliz','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0472','Foro de Porto Ferreira','Porto Ferreira','SP','Foro de Porto Ferreira','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0474','Foro de Potirendaba','Potirendaba','SP','Foro de Potirendaba','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0477','Foro de Praia Grande','Praia Grande','SP','Foro de Praia Grande','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0480','Foro de Presidente Bernardes','Presidente Bernardes','SP','Foro de Presidente Bernardes','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0481','Foro de Presidente Epitácio','Presidente Epitácio','SP','Foro de Presidente Epitácio','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0482','Foro de Presidente Prudente','Presidente Prudente','SP','Foro de Presidente Prudente','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0483','Foro de Presidente Venceslau','Presidente Venceslau','SP','Foro de Presidente Venceslau','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0484','Foro de Promissão','Promissão','SP','Foro de Promissão','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0486','Foro de Quatá','Quatá','SP','Foro de Quatá','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0488','Foro de Queluz','Queluz','SP','Foro de Queluz','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0491','Foro de Rancharia','Rancharia','SP','Foro de Rancharia','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0493','Foro de Regente Feijó','Regente Feijó','SP','Foro de Regente Feijó','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0495','Foro de Registro','Registro','SP','Foro de Registro','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0498','Foro de Ribeirão Bonito','Ribeirão Bonito','SP','Foro de Ribeirão Bonito','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0505','Foro de Ribeirão Pires','Ribeirão Pires','SP','Foro de Ribeirão Pires','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0506','Foro de Ribeirão Preto','Ribeirão Preto','SP','Foro de Ribeirão Preto','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0510','Foro de Rio Claro','Rio Claro','SP','Foro de Rio Claro','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0511','Foro de Rio das Pedras','Rio das Pedras','SP','Foro de Rio das Pedras','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0512','Foro de Rio Grande da Serra','Rio Grande da Serra','SP','Foro de Rio Grande da Serra','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0515','Foro de Rosana','Rosana','SP','Foro de Rosana','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0516','Foro de Roseira','Roseira','SP','Foro de Roseira','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0523','Foro de Salesópolis','Salesópolis','SP','Foro de Salesópolis','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0526','Foro de Salto','Salto','SP','Foro de Salto','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0699','Foro de Salto de Pirapora','Salto de Pirapora','SP','Foro de Salto de Pirapora','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0531','Foro de Santa Adélia','Santa Adélia','SP','Foro de Santa Adélia','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0533','Foro de Santa Bárbara d\u0027Oeste','Santa Bárbara d\u0027Oeste','SP','Foro de Santa Bárbara d\u0027Oeste','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0534','Foro de Santa Branca','Santa Branca','SP','Foro de Santa Branca','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0538','Foro de Santa Cruz das Palmeiras','Santa Cruz das Palmeiras','SP','Foro de Santa Cruz das Palmeiras','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0539','Foro de Santa Cruz do Rio Pardo','Santa Cruz do Rio Pardo','SP','Foro de Santa Cruz do Rio Pardo','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0541','Foro de Santa Fé do Sul','Santa Fé do Sul','SP','Foro de Santa Fé do Sul','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0543','Foro de Santa Isabel','Santa Isabel','SP','Foro de Santa Isabel','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0547','Foro de Santa Rita do Passa Quatro','Santa Rita do Passa Quatro','SP','Foro de Santa Rita do Passa Quatro','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0549','Foro de Santa Rosa de Viterbo','Santa Rosa de Viterbo','SP','Foro de Santa Rosa de Viterbo','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0708','Foro de Santa Salete','Santa Salete','SP','Foro de Santa Salete','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0529','Foro de Santana de Parnaíba','Santana de Parnaíba','SP','Foro de Santana de Parnaíba','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0553','Foro de Santo Anastácio','Santo Anastácio','SP','Foro de Santo Anastácio','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0554','Foro de Santo André','Santo André','SP','Foro de Santo André','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0562','Foro de Santos','Santos','SP','Foro de Santos','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0563','Foro de São Bento do Sapucaí','São Bento do Sapucaí','SP','Foro de São Bento do Sapucaí','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0564','Foro de São Bernardo do Campo','São Bernardo do Campo','SP','Foro de São Bernardo do Campo','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0565','Foro de São Caetano do Sul','São Caetano do Sul','SP','Foro de São Caetano do Sul','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0566','Foro de São Carlos','São Carlos','SP','Foro de São Carlos','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0568','Foro de São João da Boa Vista','São João da Boa Vista','SP','Foro de São João da Boa Vista','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0572','Foro de São Joaquim da Barra','São Joaquim da Barra','SP','Foro de São Joaquim da Barra','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0575','Foro de São José do Rio Pardo','São José do Rio Pardo','SP','Foro de São José do Rio Pardo','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0576','Foro de São José do Rio Preto','São José do Rio Preto','SP','Foro de São José do Rio Preto','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0577','Foro de São José dos Campos','São José dos Campos','SP','Foro de São José dos Campos','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0579','Foro de São Luiz do Paraitinga','São Luiz do Paraitinga','SP','Foro de São Luiz do Paraitinga','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0581','Foro de São Manuel','São Manuel','SP','Foro de São Manuel','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0582','Foro de São Miguel Arcanjo','São Miguel Arcanjo','SP','Foro de São Miguel Arcanjo','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0584','Foro de São Pedro','São Pedro','SP','Foro de São Pedro','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0586','Foro de São Roque','São Roque','SP','Foro de São Roque','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0587','Foro de São Sebastião','São Sebastião','SP','Foro de São Sebastião','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0588','Foro de São Sebastião da Grama','São Sebastião da Grama','SP','Foro de São Sebastião da Grama','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0589','Foro de São Simão','São Simão','SP','Foro de São Simão','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0590','Foro de São Vicente','São Vicente','SP','Foro de São Vicente','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0595','Foro de Serra Negra','Serra Negra','SP','Foro de Serra Negra','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0596','Foro de Serrana','Serrana','SP','Foro de Serrana','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0597','Foro de Sertãozinho','Sertãozinho','SP','Foro de Sertãozinho','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0601','Foro de Socorro','Socorro','SP','Foro de Socorro','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0602','Foro de Sorocaba','Sorocaba','SP','Foro de Sorocaba','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0604','Foro de Sumaré','Sumaré','SP','Foro de Sumaré','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0606','Foro de Suzano','Suzano','SP','Foro de Suzano','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0607','Foro de Tabapuã','Tabapuã','SP','Foro de Tabapuã','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0609','Foro de Taboão da Serra','Taboão da Serra','SP','Foro de Taboão da Serra','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0614','Foro de Tambaú','Tambaú','SP','Foro de Tambaú','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0615','Foro de Tanabi','Tanabi','SP','Foro de Tanabi','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0619','Foro de Taquaritinga','Taquaritinga','SP','Foro de Taquaritinga','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0620','Foro de Taquarituba','Taquarituba','SP','Foro de Taquarituba','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0624','Foro de Tatuí','Tatuí','SP','Foro de Tatuí','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0625','Foro de Taubaté','Taubaté','SP','Foro de Taubaté','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0627','Foro de Teodoro Sampaio','Teodoro Sampaio','SP','Foro de Teodoro Sampaio','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0629','Foro de Tietê','Tietê','SP','Foro de Tietê','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0634','Foro de Tremembé','Tremembé','SP','Foro de Tremembé','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0637','Foro de Tupã','Tupã','SP','Foro de Tupã','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0638','Foro de Tupi Paulista','Tupi Paulista','SP','Foro de Tupi Paulista','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0642','Foro de Ubatuba','Ubatuba','SP','Foro de Ubatuba','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0646','Foro de Urânia','Urânia','SP','Foro de Urânia','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0648','Foro de Urupês','Urupês','SP','Foro de Urupês','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0650','Foro de Valinhos','Valinhos','SP','Foro de Valinhos','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0651','Foro de Valparaíso','Valparaíso','SP','Foro de Valparaíso','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0653','Foro de Vargem Grande do Sul','Vargem Grande do Sul','SP','Foro de Vargem Grande do Sul','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0654','Foro de Vargem Grande Paulista','Vargem Grande Paulista','SP','Foro de Vargem Grande Paulista','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0655','Foro de Várzea Paulista','Várzea Paulista','SP','Foro de Várzea Paulista','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0659','Foro de Vinhedo','Vinhedo','SP','Foro de Vinhedo','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0660','Foro de Viradouro','Viradouro','SP','Foro de Viradouro','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0663','Foro de Votorantim','Votorantim','SP','Foro de Votorantim','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0664','Foro de Votuporanga','Votuporanga','SP','Foro de Votuporanga','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0085','Foro Distrital Casa Verde',NULL,'SP','Foro Distrital Casa Verde','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0667','Foro Distrital de Barra do Turvo','Barra do Turvo','SP','Foro Distrital de Barra do Turvo','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0668','Foro Distrital de Barrinha','Barrinha','SP','Foro Distrital de Barrinha','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0669','Foro Distrital de Bofete','Bofete','SP','Foro Distrital de Bofete','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0674','Foro Distrital de Florínia','Florínia','SP','Foro Distrital de Florínia','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0676','Foro Distrital de Guaraçaí','Guaraçaí','SP','Foro Distrital de Guaraçaí','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0677','Foro Distrital de Iacanga','Iacanga','SP','Foro Distrital de Iacanga','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0679','Foro Distrital de Itupeva','Itupeva','SP','Foro Distrital de Itupeva','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0012','Foro Distrital de Parelheiros','Parelheiros','SP','Foro Distrital de Parelheiros','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0710','Foro Distrital de Perus','Perus','SP','Foro Distrital de Perus','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0684','Foro Distrital de São José do Barreiro','São José do Barreiro','SP','Foro Distrital de São José do Barreiro','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0998','Foro Distrital de Tabatinga','Tabatinga','SP','Foro Distrital de Tabatinga','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0688','Foro Distrital de Tarumã','Tarumã','SP','Foro Distrital de Tarumã','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0093','Foro Distrital de Vicente de Carvalho','Vicente de Carvalho','SP','Foro Distrital de Vicente de Carvalho','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0087','Foro Distrital Ibirapuera',NULL,'SP','Foro Distrital Ibirapuera','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0088','Foro Distrital Saúde',NULL,'SP','Foro Distrital Saúde','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0086','Foro Distrital Tucuruvi',NULL,'SP','Foro Distrital Tucuruvi','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0089','Foro Distrital Vila Maria',NULL,'SP','Foro Distrital Vila Maria','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0848','FORO REG C.VERDE','São Paulo','SP','FORO REG C.VERDE','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0846','FORO REG TUCURUVI','São Paulo','SP','FORO REG TUCURUVI','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0847','FORO REG V.MARIA','São Paulo','SP','FORO REG V.MARIA','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0084','Foro Regional de Vila Mimosa','São Paulo','SP','Foro Regional de Vila Mimosa','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0001','Foro Regional I - Santana','São Paulo','SP','Foro Regional I - Santana','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0002','Foro Regional II - Santo Amaro','São Paulo','SP','Foro Regional II - Santo Amaro','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0003','Foro Regional III - Jabaquara','São Paulo','SP','Foro Regional III - Jabaquara','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0004','Foro Regional IV - Lapa','São Paulo','SP','Foro Regional IV - Lapa','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0009','Foro Regional IX - Vila Prudente','São Paulo','SP','Foro Regional IX - Vila Prudente','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0005','Foro Regional V - São Miguel Paulista','São Paulo','SP','Foro Regional V - São Miguel Paulista','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0006','Foro Regional VI - Penha de França','São Paulo','SP','Foro Regional VI - Penha de França','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0007','Foro Regional VII - Itaquera','São Paulo','SP','Foro Regional VII - Itaquera','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0008','Foro Regional VIII - Tatuapé','São Paulo','SP','Foro Regional VIII - Tatuapé','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0010','Foro Regional X - Ipiranga','São Paulo','SP','Foro Regional X - Ipiranga','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0011','Foro Regional XI - Pinheiros','São Paulo','SP','Foro Regional XI - Pinheiros','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0020','Foro Regional XII - Nossa Senhora do Ó','São Paulo','SP','Foro Regional XII - Nossa Senhora do Ó','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0702','Foro Regional XIII - Ermelino Matarazzo','São Paulo','SP','Foro Regional XIII - Ermelino Matarazzo','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0703','Foro Regional XIV - São Mateus','São Paulo','SP','Foro Regional XIV - São Mateus','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJSP','0704','Foro Regional XV - Butantã','São Paulo','SP','Foro Regional XV - Butantã','https://esaj.tjsp.jus.br/cpopg/open.do'),
('TJAC','0006','Comarca de Acrelândia','Acrelândia','AC',NULL,'https://esaj.tjac.jus.br/cpopg/open.do'),
('TJAC','0016','Comarca de Assis Brasil','Assis Brasil','AC',NULL,'https://esaj.tjac.jus.br/cpopg/open.do'),
('TJAC','0003','Comarca de Brasileia','Brasileia','AC',NULL,'https://esaj.tjac.jus.br/cpopg/open.do'),
('TJAC','0010','Comarca de Bujari','Bujari','AC',NULL,'https://esaj.tjac.jus.br/cpopg/open.do'),
('TJAC','0005','Comarca de Capixaba','Capixaba','AC',NULL,'https://esaj.tjac.jus.br/cpopg/open.do'),
('TJAC','0002','Comarca de Cruzeiro do Sul','Cruzeiro do Sul','AC',NULL,'https://esaj.tjac.jus.br/cpopg/open.do'),
('TJAC','0004','Comarca de Epitaciolândia','Epitaciolândia','AC',NULL,'https://esaj.tjac.jus.br/cpopg/open.do'),
('TJAC','0013','Comarca de Feijó','Feijó','AC',NULL,'https://esaj.tjac.jus.br/cpopg/open.do'),
('TJAC','0015','Comarca de Mâncio Lima','Mâncio Lima','AC',NULL,'https://esaj.tjac.jus.br/cpopg/open.do'),
('TJAC','0012','Comarca de Manoel Urbano','Manoel Urbano','AC',NULL,'https://esaj.tjac.jus.br/cpopg/open.do'),
('TJAC','0008','Comarca de Plácido de Castro','Plácido de Castro','AC',NULL,'https://esaj.tjac.jus.br/cpopg/open.do'),
('TJAC','0022','Comarca de Porto Acre','Porto Acre','AC',NULL,'https://esaj.tjac.jus.br/cpopg/open.do'),
('TJAC','0001','Comarca de Rio Branco','Rio Branco','AC',NULL,'https://esaj.tjac.jus.br/cpopg/open.do'),
('TJAC','0081','Rio Branco - Infância e Juventude','Rio Branco','AC',NULL,'https://esaj.tjac.jus.br/cpopg/open.do'),
('TJAC','0070','Rio Branco - Juizados Especiais','Rio Branco','AC',NULL,'https://esaj.tjac.jus.br/cpopg/open.do'),
('TJAC','0017','Comarca de Rodrigues Alves','Rodrigues Alves','AC',NULL,'https://esaj.tjac.jus.br/cpopg/open.do'),
('TJAC','0011','Comarca de Sena Madureira','Sena Madureira','AC',NULL,'https://esaj.tjac.jus.br/cpopg/open.do'),
('TJAC','0009','Comarca de Senador Guiomard','Senador Guiomard','AC',NULL,'https://esaj.tjac.jus.br/cpopg/open.do'),
('TJAC','0014','Comarca de Tarauacá','Tarauacá','AC',NULL,'https://esaj.tjac.jus.br/cpopg/open.do'),
('TJAC','0007','Comarca de Xapuri','Xapuri','AC',NULL,'https://esaj.tjac.jus.br/cpopg/open.do')
) AS v(sigla, codigo, nome, cidade, uf, foro, fonte)
JOIN public.cnj_tribunais t ON t.sigla = v.sigla
ON CONFLICT (tribunal_id, codigo_origem) DO NOTHING;
