-- Códigos OOOO oficiais: TJMG (lista oficial de comarcas com código, tjmg.jus.br) e TJPR (Relação de Unidades de Origem, Sistema de Numeração Única do TJPR). Coletado em 2026-09-28.
-- TJMG 0000 = competência originária do tribunal (Resolução CNJ 65/2008, art. 1º, § 6º).
-- Idempotente: não altera nem apaga registros existentes. cidade fica NULL (não é inferida).
INSERT INTO public.cnj_comarcas (tribunal_id, codigo_origem, nome, cidade, uf, foro, fonte_url, fonte_atualizada_em)
SELECT t.id, v.codigo, v.nome, NULL, v.uf, v.foro, v.fonte, DATE '2026-09-28'
FROM (VALUES
('TJMG','0002','Abaeté','MG','Abaeté','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0003','Abre-Campo','MG','Abre-Campo','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0005','Açucena','MG','Açucena','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0009','Águas Formosas','MG','Águas Formosas','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0011','Aimorés','MG','Aimorés','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0012','Aiuruoca','MG','Aiuruoca','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0015','Além Paraíba','MG','Além Paraíba','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0016','Alfenas','MG','Alfenas','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0017','Almenara','MG','Almenara','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0019','Alpinópolis','MG','Alpinópolis','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0021','Alto Rio Doce','MG','Alto Rio Doce','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0023','Alvinópolis','MG','Alvinópolis','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0026','Andradas','MG','Andradas','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0028','Andrelândia','MG','Andrelândia','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0034','Araçuaí','MG','Araçuaí','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0035','Araguari','MG','Araguari','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0040','Araxá','MG','Araxá','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0042','Arcos','MG','Arcos','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0043','Areado','MG','Areado','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0778','Arinos','MG','Arinos','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0049','Baependi','MG','Baependi','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0051','Bambuí','MG','Bambuí','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0054','Barão de Cocais','MG','Barão de Cocais','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0056','Barbacena','MG','Barbacena','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0059','Barroso','MG','Barroso','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0024','Belo Horizonte','MG','Belo Horizonte','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0064','Belo Vale','MG','Belo Vale','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0027','Betim','MG','Betim','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0069','Bicas','MG','Bicas','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0071','Boa Esperança','MG','Boa Esperança','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0073','Bocaiúva','MG','Bocaiúva','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0074','Bom Despacho','MG','Bom Despacho','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0080','Bom Sucesso','MG','Bom Sucesso','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0081','Bonfim','MG','Bonfim','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0082','Bonfinópolis de Minas','MG','Bonfinópolis de Minas','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0083','Borda da Mata','MG','Borda da Mata','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0084','Botelhos','MG','Botelhos','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0086','Brasília de Minas','MG','Brasília de Minas','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0089','Brazópolis','MG','Brazópolis','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0090','Brumadinho','MG','Brumadinho','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0091','Bueno Brandão','MG','Bueno Brandão','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0092','Buenópolis','MG','Buenópolis','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0093','Buritis','MG','Buritis','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0095','Cabo Verde','MG','Cabo Verde','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0097','Cachoeira de Minas','MG','Cachoeira de Minas','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0045','Caeté','MG','Caeté','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0103','Caldas','MG','Caldas','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0878','Camanducaia','MG','Camanducaia','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0106','Cambué','MG','Cambué','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0107','Cambuquira','MG','Cambuquira','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0109','Campanha','MG','Campanha','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0110','Campestre','MG','Campestre','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0111','Campina Verde','MG','Campina Verde','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0112','Campo Belo','MG','Campo Belo','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0115','Campos Altos','MG','Campos Altos','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0116','Campos Gerais','MG','Campos Gerais','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0118','Canápolis','MG','Canápolis','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0120','Candeias','MG','Candeias','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0123','Capelinha','MG','Capelinha','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0126','Capinópolis','MG','Capinópolis','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0132','Carandaí','MG','Carandaí','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0133','Carangola','MG','Carangola','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0134','Caratinga','MG','Caratinga','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0137','Carlos Chagas','MG','Carlos Chagas','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0140','Carmo da Mata','MG','Carmo da Mata','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0141','Carmo de Minas','MG','Carmo de Minas','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0142','Carmo do Cajuru','MG','Carmo do Cajuru','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0143','Carmo do Paranaíba','MG','Carmo do Paranaíba','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0144','Carmo do Rio Claro','MG','Carmo do Rio Claro','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0879','Carmópolis de Minas','MG','Carmópolis de Minas','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0151','Cássia','MG','Cássia','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0153','Cataguases','MG','Cataguases','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0155','Caxambu','MG','Caxambu','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0166','Cláudio','MG','Cláudio','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0172','Conceição das Alagoas','MG','Conceição das Alagoas','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0175','Conceição do Mato Dentro','MG','Conceição do Mato Dentro','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0177','Concei��o do Rio Verde','MG','Concei��o do Rio Verde','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0180','Congonhas','MG','Congonhas','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0182','Conquista','MG','Conquista','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0183','Conselheiro Lafaiete','MG','Conselheiro Lafaiete','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0184','Conselheiro Pena','MG','Conselheiro Pena','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0079','Contagem','MG','Contagem','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0775','Coração de Jesus','MG','Coração de Jesus','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0191','Corinto','MG','Corinto','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0193','Coromandel','MG','Coromandel','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0194','Coronel Fabriciano','MG','Coronel Fabriciano','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0205','Cristina','MG','Cristina','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0208','Cruzília','MG','Cruzília','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0209','Curvelo','MG','Curvelo','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0216','Diamantina','MG','Diamantina','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0220','Divino','MG','Divino','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0223','Divinópolis','MG','Divinópolis','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0232','Dores do Indaiá','MG','Dores do Indaiá','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0236','El�i Mendes','MG','El�i Mendes','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0239','Entre-Rios de Minas','MG','Entre-Rios de Minas','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0240','Ervália','MG','Ervália','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0241','Esmeraldas','MG','Esmeraldas','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0242','Espera Feliz','MG','Espera Feliz','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0243','Espinosa','MG','Espinosa','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0248','Estrela do Sul','MG','Estrela do Sul','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0249','Eugenópolis','MG','Eugenópolis','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0251','Extrema','MG','Extrema','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0259','Ferros','MG','Ferros','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0261','Formiga','MG','Formiga','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0267','Francisco Sá','MG','Francisco Sá','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0271','Frutal','MG','Frutal','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0273','Galiléia','MG','Galiléia','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0105','Governador Valadares','MG','Governador Valadares','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0278','Grão-Mogol','MG','Grão-Mogol','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0280','Guanhães','MG','Guanhães','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0281','Guapé','MG','Guapé','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0283','Guaranésia','MG','Guaranésia','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0284','Guarani','MG','Guarani','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0287','Guaxupé','MG','Guaxupé','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0295','Ibiá','MG','Ibiá','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0297','Ibiraci','MG','Ibiraci','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0114','Ibirité','MG','Ibirité','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0301','Igarapé','MG','Igarapé','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0303','Iguatama','MG','Iguatama','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0309','Inhapim','MG','Inhapim','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0312','Ipanema','MG','Ipanema','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0313','Ipatinga','MG','Ipatinga','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0317','Itabira','MG','Itabira','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0319','Itabirito','MG','Itabirito','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0322','Itaguara','MG','Itaguara','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0324','Itajubá','MG','Itajubá','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0325','Itamarandiba','MG','Itamarandiba','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0327','Itambacuri','MG','Itambacuri','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0329','Itamoji','MG','Itamoji','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0330','Itamonte','MG','Itamonte','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0331','Itanhandu','MG','Itanhandu','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0332','Itanhomi','MG','Itanhomi','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0334','Itapajipe','MG','Itapajipe','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0335','Itapecerica','MG','Itapecerica','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0338','Itaúna','MG','Itaúna','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0342','Ituiutaba','MG','Ituiutaba','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0343','Itumirim','MG','Itumirim','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0344','Iturama','MG','Iturama','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0346','Jaboticatubas','MG','Jaboticatubas','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0347','Jacinto','MG','Jacinto','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0348','Jacuí','MG','Jacuí','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0349','Jacutinga','MG','Jacutinga','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0738','Jaíba','MG','Jaíba','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0351','Janaúba','MG','Janaúba','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0252','Januária','MG','Januária','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0355','Jequeri','MG','Jequeri','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0358','Jequitinhonha','MG','Jequitinhonha','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0362','João Monlevade','MG','João Monlevade','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0363','João Pinheiro','MG','João Pinheiro','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0740','Juatuba','MG','Juatuba','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0145','Juiz de Fora','MG','Juiz de Fora','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0372','Lagoa da Prata','MG','Lagoa da Prata','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0148','Lagoa Santa','MG','Lagoa Santa','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0377','Lajinha','MG','Lajinha','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0378','Lambari','MG','Lambari','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0382','Lavras','MG','Lavras','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0384','Leopoldina','MG','Leopoldina','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0386','Lima Duarte','MG','Lima Duarte','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0388','Luz','MG','Luz','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0390','Machado','MG','Machado','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0392','Malacacheta','MG','Malacacheta','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0393','Manga','MG','Manga','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0394','Manhuaçu','MG','Manhuaçu','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0395','Manhumirim','MG','Manhumirim','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0396','Mantena','MG','Mantena','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0398','Mar de Espanha','MG','Mar de Espanha','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0400','Mariana','MG','Mariana','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0405','Martinho Campos','MG','Martinho Campos','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0407','Mateus Leme','MG','Mateus Leme','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0408','Matias Barbosa','MG','Matias Barbosa','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0411','Matozinhos','MG','Matozinhos','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0414','Medina','MG','Medina','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0416','Mercês','MG','Mercês','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0417','Mesquita','MG','Mesquita','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0418','Minas Novas','MG','Minas Novas','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0421','Miradouro','MG','Miradouro','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0422','Miraí','MG','Miraí','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0427','Montalvânia','MG','Montalvânia','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0428','Monte Alegre de Minas','MG','Monte Alegre de Minas','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0429','Monte Azul','MG','Monte Azul','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0430','Monte Belo','MG','Monte Belo','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0431','Monte Carmelo','MG','Monte Carmelo','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0432','Monte Santo de Minas','MG','Monte Santo de Minas','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0434','Monte Sião','MG','Monte Sião','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0433','Montes Claros','MG','Montes Claros','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0435','Morada Nova de Minas','MG','Morada Nova de Minas','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0439','Muriaé','MG','Muriaé','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0440','Mutum','MG','Mutum','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0441','Muzambinho','MG','Muzambinho','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0443','Nanuque','MG','Nanuque','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0444','Natércia','MG','Natércia','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0446','Nepomuceno','MG','Nepomuceno','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0447','Nova Era','MG','Nova Era','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0188','Nova Lima','MG','Nova Lima','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0450','Nova Ponte','MG','Nova Ponte','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0451','Nova Resende','MG','Nova Resende','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0452','Nova Serrana','MG','Nova Serrana','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0453','Novo Cruzeiro','MG','Novo Cruzeiro','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0456','Oliveira','MG','Oliveira','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0459','Ouro Branco','MG','Ouro Branco','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0460','Ouro Fino','MG','Ouro Fino','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0461','Ouro Preto','MG','Ouro Preto','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0467','Palma','MG','Palma','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0471','Pará de Minas','MG','Pará de Minas','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0470','Paracatu','MG','Paracatu','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0472','Paraguaçu','MG','Paraguaçu','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0473','Paraisópolis','MG','Paraisópolis','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0474','Paraopeba','MG','Paraopeba','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0476','Passa-Quatro','MG','Passa-Quatro','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0477','Passa-Tempo','MG','Passa-Tempo','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0479','Passos','MG','Passos','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0480','Patos de Minas','MG','Patos de Minas','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0481','Patrocínio','MG','Patrocínio','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0486','Peçanha','MG','Peçanha','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0487','Pedra Azul','MG','Pedra Azul','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0491','Pedralva','MG','Pedralva','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0210','Pedro Leopoldo','MG','Pedro Leopoldo','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0498','Perdizes','MG','Perdizes','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0499','Perdões','MG','Perdões','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0508','Piranga','MG','Piranga','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0511','Pirapetinga','MG','Pirapetinga','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0512','Pirapora','MG','Pirapora','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0514','Pitangui','MG','Pitangui','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0515','Piumhi','MG','Piumhi','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0517','Poço Fundo','MG','Poço Fundo','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0518','Poços de Caldas','MG','Poços de Caldas','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0520','Pompéu','MG','Pompéu','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0521','Ponte Nova','MG','Ponte Nova','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0522','Porteirinha','MG','Porteirinha','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0525','Pouso Alegre','MG','Pouso Alegre','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0527','Prados','MG','Prados','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0528','Prata','MG','Prata','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0529','Pratápolis','MG','Pratápolis','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0534','Presidente Olegário','MG','Presidente Olegário','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0540','Raul Soares','MG','Raul Soares','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0542','Resende Costa','MG','Resende Costa','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0543','Resplendor','MG','Resplendor','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0231','Ribeirão das Neves','MG','Ribeirão das Neves','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0549','Rio Casca','MG','Rio Casca','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0554','Rio Novo','MG','Rio Novo','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0555','Rio Paranaíba','MG','Rio Paranaíba','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0556','Rio Pardo de Minas','MG','Rio Pardo de Minas','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0557','Rio Piracicaba','MG','Rio Piracicaba','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0558','Rio Pomba','MG','Rio Pomba','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0559','Rio Preto','MG','Rio Preto','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0560','Rio Vermelho','MG','Rio Vermelho','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0567','Sabará','MG','Sabará','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0568','Sabinópolis','MG','Sabinópolis','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0569','Sacramento','MG','Sacramento','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0570','Salinas','MG','Salinas','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0572','Santa Bárbara','MG','Santa Bárbara','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0245','Santa Luzia','MG','Santa Luzia','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0582','Santa Maria do Suaçuí','MG','Santa Maria do Suaçuí','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0592','Santa Rita de Caldas','MG','Santa Rita de Caldas','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0596','Santa Rita do Sapucaí','MG','Santa Rita do Sapucaí','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0598','Santa Vitória','MG','Santa Vitória','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0604','Santo Antônio do Monte','MG','Santo Antônio do Monte','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0607','Santos Dumont','MG','Santos Dumont','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0610','São Domingos do Prata','MG','São Domingos do Prata','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0611','São Francisco','MG','São Francisco','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0620','São Gonçalo do Sapucaí','MG','São Gonçalo do Sapucaí','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0621','São Gotardo','MG','São Gotardo','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0624','São João da Ponte','MG','São João da Ponte','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0625','São João Del-Rei','MG','São João Del-Rei','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0627','São João do Paraíso','MG','São João do Paraíso','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0628','São João Evangelista','MG','São João Evangelista','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0629','São João Nepomuceno','MG','São João Nepomuceno','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0637','São Lourenço','MG','São Lourenço','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0642','São Romão','MG','São Romão','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0643','São Roque de Minas','MG','São Roque de Minas','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0647','São Sebastião do Paraíso','MG','São Sebastião do Paraíso','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0657','Senador Firmino','MG','Senador Firmino','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0671','Serro','MG','Serro','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0672','Sete Lagoas','MG','Sete Lagoas','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0674','Silvianópolis','MG','Silvianópolis','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0680','Taiobeiras','MG','Taiobeiras','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0684','Tarumirim','MG','Tarumirim','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0685','Teixeiras','MG','Teixeiras','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0686','Teófilo Otôni','MG','Teófilo Otôni','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0687','Timóteo','MG','Timóteo','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0689','Tiros','MG','Tiros','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0692','Tombos','MG','Tombos','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0693','Três Corações','MG','Três Corações','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0058','Três Marias','MG','Três Marias','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0694','Três Pontas','MG','Três Pontas','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0696','Tupaciguara','MG','Tupaciguara','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0697','Turmalina','MG','Turmalina','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0699','Ubá','MG','Ubá','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0701','Uberaba','MG','Uberaba','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0702','Uberlândia','MG','Uberlândia','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0704','Unaí','MG','Unaí','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0707','Varginha','MG','Varginha','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0708','Várzea da Palma','MG','Várzea da Palma','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0710','Vazante','MG','Vazante','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0290','Vespasiano','MG','Vespasiano','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0713','Viçosa','MG','Viçosa','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0718','Virginópolis','MG','Virginópolis','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0720','Visconde do Rio Branco','MG','Visconde do Rio Branco','https://www8.tjmg.jus.br/juridico/comarcas.html'),
('TJMG','0000','Tribunal de Justiça - 2º grau (competência originária)','MG','Tribunal de Justiça - 2º grau','https://atos.cnj.jus.br/atos/detalhar/119'),
('TJPR','0000','2º GRAU','PR','2º GRAU','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0001','FÓRUM CÍVEL DE CURITIBA - CÂNDIDO DE ABREU','PR','FÓRUM CÍVEL DE CURITIBA - CÂNDIDO DE ABREU','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0002','VARAS DE FAMÍLIA DE CURITIBA','PR','VARAS DE FAMÍLIA DE CURITIBA','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0003','FÓRUM DA VARA DE ADOLESCENTES INFRATORES DE CURITIBA','PR','FÓRUM DA VARA DE ADOLESCENTES INFRATORES DE CURITIBA','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0004','FÓRUM DAS VARAS DA FAZENDA PÚBLICA DE CURITIBA','PR','FÓRUM DAS VARAS DA FAZENDA PÚBLICA DE CURITIBA','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0005','JUIZADOS ESPECIAIS CRIMINAIS DE CURITIBA','PR','JUIZADOS ESPECIAIS CRIMINAIS DE CURITIBA','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0006','FÓRUM DAS VARAS PRIVATIVAS DO TRIBUNAL DO JÚRI DE CURITIBA','PR','FÓRUM DAS VARAS PRIVATIVAS DO TRIBUNAL DO JÚRI DE CURITIBA','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0007','FÓRUM DA VARA DE INFRAÇÕES PENAIS CONTRA CRIANÇAS, ADOLESCENTES E IDOSOS DE CURITIBA','PR','FÓRUM DA VARA DE INFRAÇÕES PENAIS CONTRA CRIANÇAS, ADOLESCENTES E IDOSOS DE CURITIBA','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0008','VARAS DE DELITOS DE TRÂNSITO DE CURITIBA','PR','VARAS DE DELITOS DE TRÂNSITO DE CURITIBA','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0009','FÓRUM DAS VARAS DE EXECUÇÕES PENAIS E CORREGEDORIA DOS PRESÍDIOS DE CURITIBA','PR','FÓRUM DAS VARAS DE EXECUÇÕES PENAIS E CORREGEDORIA DOS PRESÍDIOS DE CURITIBA','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0010','JUIZADOS ESPECIAIS CÍVEL E CRIMINAL DE CURITIBA','PR','JUIZADOS ESPECIAIS CÍVEL E CRIMINAL DE CURITIBA','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0011','FÓRUM DO JUIZADO DE VIOLÊNCIA DOMÉSTICA CONTRA A MULHER DE CURITIBA','PR','FÓRUM DO JUIZADO DE VIOLÊNCIA DOMÉSTICA CONTRA A MULHER DE CURITIBA','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0012','JUIZADOS ESPECIAIS CÍVEIS DE CURITIBA','PR','JUIZADOS ESPECIAIS CÍVEIS DE CURITIBA','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0013','FÓRUM CRIMINAL DE CURITIBA','PR','FÓRUM CRIMINAL DE CURITIBA','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0014','FÓRUM CÍVEL E CRIMINAL DE LONDRINA','PR','FÓRUM CÍVEL E CRIMINAL DE LONDRINA','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0015','VARA DE EXECUÇÕES PENAIS E CORREGEDORIA DOS PRESÍDIOS DE LONDRINA','PR','VARA DE EXECUÇÕES PENAIS E CORREGEDORIA DOS PRESÍDIOS DE LONDRINA','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0016','JUIZADOS ESPECIAIS CRIMINAIS DE LONDRINA','PR','JUIZADOS ESPECIAIS CRIMINAIS DE LONDRINA','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0017','FÓRUM CÍVEL E CRIMINAL DE MARINGÁ','PR','FÓRUM CÍVEL E CRIMINAL DE MARINGÁ','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0018','FÓRUM DOS JUIZADOS ESPECIAIS DE MARINGÁ','PR','FÓRUM DOS JUIZADOS ESPECIAIS DE MARINGÁ','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0019','FÓRUM CÍVEL E CRIMINAL DE PONTA GROSSA','PR','FÓRUM CÍVEL E CRIMINAL DE PONTA GROSSA','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0020','JUIZADOS ESPECIAIS CRIMINAIS DE PONTA GROSSA','PR','JUIZADOS ESPECIAIS CRIMINAIS DE PONTA GROSSA','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0021','FÓRUM CÍVEL E CRIMINAL DE CASCAVEL','PR','FÓRUM CÍVEL E CRIMINAL DE CASCAVEL','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0022','FÓRUM CÍVEL DE ALMIRANTE TAMANDARÉ','PR','FÓRUM CÍVEL DE ALMIRANTE TAMANDARÉ','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0023','FÓRUM CRIMINAL DE ALMIRANTE TAMANDARÉ','PR','FÓRUM CRIMINAL DE ALMIRANTE TAMANDARÉ','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0024','FÓRUM DE ALMIRANTE TAMANDARÉ','PR','FÓRUM DE ALMIRANTE TAMANDARÉ','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0025','FÓRUM CÍVEL E CRIMINAL DE ARAUCÁRIA','PR','FÓRUM CÍVEL E CRIMINAL DE ARAUCÁRIA','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0026','FÓRUM CÍVEL E CRIMINAL DE CAMPO LARGO','PR','FÓRUM CÍVEL E CRIMINAL DE CAMPO LARGO','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0027','JUIZADOS ESPECIAIS CÍVEL E CRIMINAL DE CAMPO LARGO','PR','JUIZADOS ESPECIAIS CÍVEL E CRIMINAL DE CAMPO LARGO','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0028','FÓRUM CRIMINAL, FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE, ACIDENTES DO TRABALHO, REGISTROS PÚBLICOS E CORREGEDORIA DO FORO EXTRAJUDICIAL DE COLOMBO','PR','FÓRUM CRIMINAL, FAMÍLIA E SUCESSÕES, INFÂNCIA E JUVENTUDE, ACIDENTES DO TRABALHO, REGISTROS PÚBLICOS E CORREGEDORIA DO FORO EXTRAJUDICIAL DE COLOMBO','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0029','FÓRUM DOS JUIZADOS ESPECIAIS DE COLOMBO','PR','FÓRUM DOS JUIZADOS ESPECIAIS DE COLOMBO','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0030','FÓRUM CÍVEL E CRIMINAL DE FOZ DO IGUAÇU','PR','FÓRUM CÍVEL E CRIMINAL DE FOZ DO IGUAÇU','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0031','FÓRUM CÍVEL E CRIMINAL DE GUARAPUAVA','PR','FÓRUM CÍVEL E CRIMINAL DE GUARAPUAVA','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0032','FÓRUM CÍVEL E CRIMINAL DE GUARAPUAVA (2ª VARA CRIMINAL)','PR','FÓRUM CÍVEL E CRIMINAL DE GUARAPUAVA (2ª VARA CRIMINAL)','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0033','FÓRUM CÍVEL E CRIMINAL DE PINHAIS','PR','FÓRUM CÍVEL E CRIMINAL DE PINHAIS','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0034','FÓRUM CÍVEL E CRIMINAL DE PIRAQUARA','PR','FÓRUM CÍVEL E CRIMINAL DE PIRAQUARA','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0035','FÓRUM CÍVEL E CRIMINAL DE SÃO JOSÉ DOS PINHAIS','PR','FÓRUM CÍVEL E CRIMINAL DE SÃO JOSÉ DOS PINHAIS','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0036','FÓRUM DO 3º JUIZADO ESPECIAL CÍVEL, CRIMINAL E DA FAZENDA PÚBLICA - FORO REGIONAL DE SÃO JOSÉ DOS PINHAIS','PR','FÓRUM DO 3º JUIZADO ESPECIAL CÍVEL, CRIMINAL E DA FAZENDA PÚBLICA - FORO REGIONAL DE SÃO JOSÉ DOS PINHAIS','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0037','FÓRUM CÍVEL E CRIMINAL DE CAMPINA GRANDE DO SUL','PR','FÓRUM CÍVEL E CRIMINAL DE CAMPINA GRANDE DO SUL','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0038','FÓRUM CÍVEL E CRIMINAL DE FAZENDA RIO GRANDE','PR','FÓRUM CÍVEL E CRIMINAL DE FAZENDA RIO GRANDE','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0039','FÓRUM DE ANDIRÁ','PR','FÓRUM DE ANDIRÁ','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0040','FÓRUM DE ALTÔNIA','PR','FÓRUM DE ALTÔNIA','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0041','FÓRUM DE ALTO PARANÁ','PR','FÓRUM DE ALTO PARANÁ','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0042','FÓRUM DE ALTO PIQUIRI','PR','FÓRUM DE ALTO PIQUIRI','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0043','FÓRUM DE ANTONINA','PR','FÓRUM DE ANTONINA','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0044','FÓRUM DE APUCARANA','PR','FÓRUM DE APUCARANA','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0045','FÓRUM DE ARAPONGAS','PR','FÓRUM DE ARAPONGAS','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0046','FÓRUM DE ARAPOTI','PR','FÓRUM DE ARAPOTI','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0047','FÓRUM DE ASSAÍ','PR','FÓRUM DE ASSAÍ','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0048','FÓRUM DE ASSIS CHATEAUBRIAND','PR','FÓRUM DE ASSIS CHATEAUBRIAND','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0049','FÓRUM DE ASTORGA','PR','FÓRUM DE ASTORGA','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0050','FÓRUM DE BANDEIRANTES','PR','FÓRUM DE BANDEIRANTES','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0051','FÓRUM DE BARBOSA FERRAZ','PR','FÓRUM DE BARBOSA FERRAZ','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0052','FÓRUM DE BARRACÃO','PR','FÓRUM DE BARRACÃO','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0053','FÓRUM DE BELA VISTA DO PARAÍSO','PR','FÓRUM DE BELA VISTA DO PARAÍSO','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0054','FÓRUM DE BOCAIÚVA DO SUL','PR','FÓRUM DE BOCAIÚVA DO SUL','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0055','FÓRUM DE CAMBARÁ','PR','FÓRUM DE CAMBARÁ','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0056','FÓRUM DE CAMBÉ','PR','FÓRUM DE CAMBÉ','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0057','FÓRUM DE CAMPINA DA LAGOA','PR','FÓRUM DE CAMPINA DA LAGOA','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0058','FÓRUM DE CAMPO MOURÃO','PR','FÓRUM DE CAMPO MOURÃO','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0059','FÓRUM DE CÂNDIDO DE ABREU','PR','FÓRUM DE CÂNDIDO DE ABREU','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0060','FÓRUM DE CANTAGALO','PR','FÓRUM DE CANTAGALO','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0061','FÓRUM DE CAPANEMA','PR','FÓRUM DE CAPANEMA','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0062','FÓRUM DE CAPITÃO LEÔNIDAS MARQUES','PR','FÓRUM DE CAPITÃO LEÔNIDAS MARQUES','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0063','FÓRUM DE CARLÓPOLIS','PR','FÓRUM DE CARLÓPOLIS','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0064','FÓRUM DE CASTRO','PR','FÓRUM DE CASTRO','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0065','FÓRUM DE CATANDUVAS','PR','FÓRUM DE CATANDUVAS','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0066','FÓRUM DE CENTENÁRIO DO SUL','PR','FÓRUM DE CENTENÁRIO DO SUL','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0067','FÓRUM DE CERRO AZUL','PR','FÓRUM DE CERRO AZUL','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0068','FÓRUM DE CHOPINZINHO','PR','FÓRUM DE CHOPINZINHO','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0069','FÓRUM DE CIANORTE','PR','FÓRUM DE CIANORTE','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0070','FÓRUM DE CIDADE GAÚCHA','PR','FÓRUM DE CIDADE GAÚCHA','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0071','FÓRUM DE CLEVELÂNDIA','PR','FÓRUM DE CLEVELÂNDIA','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0072','FÓRUM DE COLORADO','PR','FÓRUM DE COLORADO','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0073','FÓRUM DE CONGONHINHAS','PR','FÓRUM DE CONGONHINHAS','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0074','FÓRUM DE CORBÉLIA','PR','FÓRUM DE CORBÉLIA','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0075','FÓRUM DE CORNÉLIO PROCÓPIO','PR','FÓRUM DE CORNÉLIO PROCÓPIO','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0076','FÓRUM DE CORONEL VIVIDA','PR','FÓRUM DE CORONEL VIVIDA','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0077','FÓRUM DE CRUZEIRO DO OESTE','PR','FÓRUM DE CRUZEIRO DO OESTE','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0078','FÓRUM DE CURIÚVA','PR','FÓRUM DE CURIÚVA','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0079','FÓRUM DE DOIS VIZINHOS','PR','FÓRUM DE DOIS VIZINHOS','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0080','FÓRUM DE ENGENHEIRO BELTRÃO','PR','FÓRUM DE ENGENHEIRO BELTRÃO','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0081','FÓRUM DE FAXINAL','PR','FÓRUM DE FAXINAL','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0082','FÓRUM DE FORMOSA DO OESTE','PR','FÓRUM DE FORMOSA DO OESTE','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0083','FÓRUM DE FRANCISCO BELTRÃO','PR','FÓRUM DE FRANCISCO BELTRÃO','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0084','FÓRUM DE GOIOERÊ','PR','FÓRUM DE GOIOERÊ','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0085','FÓRUM DE GRANDES RIOS','PR','FÓRUM DE GRANDES RIOS','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0086','FÓRUM DE GUAÍRA','PR','FÓRUM DE GUAÍRA','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0087','FÓRUM DE GUARANIAÇU','PR','FÓRUM DE GUARANIAÇU','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0088','FÓRUM DE GUARATUBA','PR','FÓRUM DE GUARATUBA','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0089','FÓRUM DE IBAITI','PR','FÓRUM DE IBAITI','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0090','FÓRUM DE IBIPORÃ','PR','FÓRUM DE IBIPORÃ','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0091','FÓRUM DE ICARAÍMA','PR','FÓRUM DE ICARAÍMA','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0092','FÓRUM DE IMBITUVA','PR','FÓRUM DE IMBITUVA','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0093','FÓRUM DE IPIRANGA','PR','FÓRUM DE IPIRANGA','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0094','FÓRUM DE IPORÃ','PR','FÓRUM DE IPORÃ','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0095','FÓRUM DA 1º VARA CÍVEL E DA VARA CRIMINAL DE IRATI','PR','FÓRUM DA 1º VARA CÍVEL E DA VARA CRIMINAL DE IRATI','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0096','FÓRUM DE IRETAMA','PR','FÓRUM DE IRETAMA','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0097','FÓRUM DE IVAIPORÃ','PR','FÓRUM DE IVAIPORÃ','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0098','FÓRUM DE JACAREZINHO','PR','FÓRUM DE JACAREZINHO','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0099','FÓRUM DE JAGUAPITÃ','PR','FÓRUM DE JAGUAPITÃ','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0100','FÓRUM DE JAGUARIAÍVA','PR','FÓRUM DE JAGUARIAÍVA','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0101','FÓRUM DE JANDAIA DO SUL','PR','FÓRUM DE JANDAIA DO SUL','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0102','FÓRUM DE JOAQUIM TÁVORA','PR','FÓRUM DE JOAQUIM TÁVORA','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0103','FÓRUM DE LAPA','PR','FÓRUM DE LAPA','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0104','FÓRUM DE LARANJEIRAS DO SUL','PR','FÓRUM DE LARANJEIRAS DO SUL','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0105','FÓRUM DE LOANDA','PR','FÓRUM DE LOANDA','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0106','FÓRUM DE MALLET','PR','FÓRUM DE MALLET','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0107','FÓRUM DE MAMBORÊ','PR','FÓRUM DE MAMBORÊ','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0108','FÓRUM DE MANDAGUAÇU','PR','FÓRUM DE MANDAGUAÇU','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0109','FÓRUM DE MANDAGUARI','PR','FÓRUM DE MANDAGUARI','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0110','FÓRUM DE MANGUEIRINHA','PR','FÓRUM DE MANGUEIRINHA','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0111','FÓRUM DE MANOEL RIBAS','PR','FÓRUM DE MANOEL RIBAS','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0112','FÓRUM DE MARECHAL CÂNDIDO RONDON','PR','FÓRUM DE MARECHAL CÂNDIDO RONDON','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0113','FÓRUM DE MARIALVA','PR','FÓRUM DE MARIALVA','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0114','FÓRUM DE MARILÂNDIA DO SUL','PR','FÓRUM DE MARILÂNDIA DO SUL','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0115','FÓRUM DE MATELÂNDIA','PR','FÓRUM DE MATELÂNDIA','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0116','FÓRUM DE MATINHOS','PR','FÓRUM DE MATINHOS','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0117','FÓRUM DE MEDIANEIRA','PR','FÓRUM DE MEDIANEIRA','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0118','FÓRUM DE MORRETES','PR','FÓRUM DE MORRETES','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0119','FÓRUM DE NOVA ESPERANÇA','PR','FÓRUM DE NOVA ESPERANÇA','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0120','FÓRUM DE NOVA FÁTIMA','PR','FÓRUM DE NOVA FÁTIMA','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0121','FÓRUM DE NOVA LONDRINA','PR','FÓRUM DE NOVA LONDRINA','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0122','FÓRUM DE ORTIGUEIRA','PR','FÓRUM DE ORTIGUEIRA','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0123','FÓRUM DE PALMAS','PR','FÓRUM DE PALMAS','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0124','FÓRUM DE PALMEIRA','PR','FÓRUM DE PALMEIRA','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0125','FÓRUM DE PALMITAL','PR','FÓRUM DE PALMITAL','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0126','FÓRUM DE PALOTINA','PR','FÓRUM DE PALOTINA','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0127','FÓRUM DE PARAÍSO DO NORTE','PR','FÓRUM DE PARAÍSO DO NORTE','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0128','FÓRUM DE PARANACITY','PR','FÓRUM DE PARANACITY','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0129','FÓRUM DE PARANAGUÁ','PR','FÓRUM DE PARANAGUÁ','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0130','FÓRUM DE PARANAVAÍ','PR','FÓRUM DE PARANAVAÍ','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0131','FÓRUM DE PATO BRANCO','PR','FÓRUM DE PATO BRANCO','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0132','FÓRUM DE PEABIRU','PR','FÓRUM DE PEABIRU','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0133','FÓRUM DE PÉROLA','PR','FÓRUM DE PÉROLA','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0134','FÓRUM DE PINHÃO','PR','FÓRUM DE PINHÃO','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0135','FÓRUM DE PIRAÍ DO SUL','PR','FÓRUM DE PIRAÍ DO SUL','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0136','FÓRUM DE PITANGA','PR','FÓRUM DE PITANGA','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0137','FÓRUM DE PORECATU','PR','FÓRUM DE PORECATU','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0138','FÓRUM DE PRIMEIRO DE MAIO','PR','FÓRUM DE PRIMEIRO DE MAIO','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0139','FÓRUM DE PRUDENTÓPOLIS','PR','FÓRUM DE PRUDENTÓPOLIS','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0140','FÓRUM DE QUEDAS DO IGUAÇU','PR','FÓRUM DE QUEDAS DO IGUAÇU','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0141','FÓRUM DE REALEZA','PR','FÓRUM DE REALEZA','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0142','FÓRUM DE REBOUÇAS','PR','FÓRUM DE REBOUÇAS','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0143','FÓRUM DE RESERVA','PR','FÓRUM DE RESERVA','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0144','FÓRUM DE RIBEIRÃO CLARO','PR','FÓRUM DE RIBEIRÃO CLARO','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0145','FÓRUM DE RIBEIRÃO DO PINHAL','PR','FÓRUM DE RIBEIRÃO DO PINHAL','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0146','FÓRUM DE RIO NEGRO','PR','FÓRUM DE RIO NEGRO','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0147','FÓRUM DE RIO BRANCO DO SUL','PR','FÓRUM DE RIO BRANCO DO SUL','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0148','FÓRUM DE ROLÂNDIA','PR','FÓRUM DE ROLÂNDIA','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0149','FÓRUM DE SALTO DO LONTRA','PR','FÓRUM DE SALTO DO LONTRA','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0150','FÓRUM DE SANTA HELENA','PR','FÓRUM DE SANTA HELENA','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0151','FÓRUM DE SANTA ISABEL DO IVAÍ','PR','FÓRUM DE SANTA ISABEL DO IVAÍ','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0152','FÓRUM DE SANTA MARIANA','PR','FÓRUM DE SANTA MARIANA','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0153','FÓRUM DE SANTO ANTÔNIO DA PLATINA','PR','FÓRUM DE SANTO ANTÔNIO DA PLATINA','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0154','FÓRUM DE SANTO ANTÔNIO DO SUDOESTE','PR','FÓRUM DE SANTO ANTÔNIO DO SUDOESTE','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0155','FÓRUM DE SÃO JERÔNIMO DA SERRA','PR','FÓRUM DE SÃO JERÔNIMO DA SERRA','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0156','FÓRUM DE SÃO JOÃO DO IVAÍ','PR','FÓRUM DE SÃO JOÃO DO IVAÍ','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0157','FÓRUM DE SÃO JOÃO DO TRIUNFO','PR','FÓRUM DE SÃO JOÃO DO TRIUNFO','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0158','FÓRUM DE SÃO MATEUS DO SUL','PR','FÓRUM DE SÃO MATEUS DO SUL','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0159','FÓRUM DE SÃO MIGUEL DO IGUAÇU','PR','FÓRUM DE SÃO MIGUEL DO IGUAÇU','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0160','FÓRUM DE SARANDI','PR','FÓRUM DE SARANDI','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0161','FÓRUM DE SENGÉS','PR','FÓRUM DE SENGÉS','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0162','FÓRUM DE SERTANÓPOLIS','PR','FÓRUM DE SERTANÓPOLIS','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0163','FÓRUM DE SIQUEIRA CAMPOS','PR','FÓRUM DE SIQUEIRA CAMPOS','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0164','FÓRUM DE TEIXEIRA SOARES','PR','FÓRUM DE TEIXEIRA SOARES','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0165','FÓRUM DE TELÊMACO BORBA','PR','FÓRUM DE TELÊMACO BORBA','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0166','FÓRUM DE TERRA BOA','PR','FÓRUM DE TERRA BOA','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0167','FÓRUM DE TERRA RICA','PR','FÓRUM DE TERRA RICA','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0168','FÓRUM DE TERRA ROXA','PR','FÓRUM DE TERRA ROXA','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0169','FÓRUM DE TIBAGI','PR','FÓRUM DE TIBAGI','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0170','FÓRUM DE TOLEDO','PR','FÓRUM DE TOLEDO','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0171','FÓRUM DE TOMAZINA','PR','FÓRUM DE TOMAZINA','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0172','FÓRUM DE UBIRATÃ','PR','FÓRUM DE UBIRATÃ','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0173','FÓRUM DE UMUARAMA','PR','FÓRUM DE UMUARAMA','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0174','FÓRUM DE UNIÃO DA VITÓRIA','PR','FÓRUM DE UNIÃO DA VITÓRIA','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0175','FÓRUM DE URAÍ','PR','FÓRUM DE URAÍ','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0176','FÓRUM DE WENCESLAU BRAZ','PR','FÓRUM DE WENCESLAU BRAZ','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0177','FÓRUM DE XAMBRÊ','PR','FÓRUM DE XAMBRÊ','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0178','FÓRUM DO JUIZADO ESPECIAL DO SÍTIO CERCADO DA COMARCA DE CURITIBA','PR','FÓRUM DO JUIZADO ESPECIAL DO SÍTIO CERCADO DA COMARCA DE CURITIBA','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0179','VARAS CÍVEIS E DA FAZENDA PÚBLICA DE CURITIBA','PR','VARAS CÍVEIS E DA FAZENDA PÚBLICA DE CURITIBA','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0180','FÓRUM DE SANTA FÉ','PR','FÓRUM DE SANTA FÉ','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0181','FÓRUM DE MARMELEIRO','PR','FÓRUM DE MARMELEIRO','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0182','FÓRUM DOS JUIZADOS ESPECIAIS DE CURITIBA','PR','FÓRUM DOS JUIZADOS ESPECIAIS DE CURITIBA','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0183','FÓRUM DE SÃO JOÃO','PR','FÓRUM DE SÃO JOÃO','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0184','FÓRUM DESCENTRALIZADO DE SANTA FELICIDADE DA COMARCA DE CURITIBA','PR','FÓRUM DESCENTRALIZADO DE SANTA FELICIDADE DA COMARCA DE CURITIBA','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0185','FÓRUM DAS VARAS DE FALÊNCIAS E RECUPERAÇÂO JUDICIAL, EXECUÇÕES FISCAIS MUNICIPAIS E ESTADUAIS DO FORO CENTRAL DE CURITIBA','PR','FÓRUM DAS VARAS DE FALÊNCIAS E RECUPERAÇÂO JUDICIAL, EXECUÇÕES FISCAIS MUNICIPAIS E ESTADUAIS DO FORO CENTRAL DE CURITIBA','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0186','FÓRUM DE AMPÉRE','PR','FÓRUM DE AMPÉRE','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0187','FÓRUM DESCENTRALIZADO DA CIDADE INDUSTRIAL DA COMARCA DE CURITIBA','PR','FÓRUM DESCENTRALIZADO DA CIDADE INDUSTRIAL DA COMARCA DE CURITIBA','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0188','FÓRUM DA FAMÍLIA, DA INFÂNCIA E DO ADOLESCENTE DE CURITIBA','PR','FÓRUM DA FAMÍLIA, DA INFÂNCIA E DO ADOLESCENTE DE CURITIBA','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0189','FÓRUM DE PONTAL DO PARANÁ','PR','FÓRUM DE PONTAL DO PARANÁ','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0190','FÓRUM DAS VARAS DA FAZENDA PÚBLICA, CRIMINAL E EXECUÇÃO DE PENAS E MEDIDAS ALTERNATIVAS DE MARINGÁ','PR','FÓRUM DAS VARAS DA FAZENDA PÚBLICA, CRIMINAL E EXECUÇÃO DE PENAS E MEDIDAS ALTERNATIVAS DE MARINGÁ','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0191','FÓRUM DESCENTRALIZADO DO PINHEIRINHO DA COMARCA DE CURITIBA','PR','FÓRUM DESCENTRALIZADO DO PINHEIRINHO DA COMARCA DE CURITIBA','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0192','FÓRUM DE NOVA AURORA','PR','FÓRUM DE NOVA AURORA','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0193','FÓRUM CÍVEL DE COLOMBO','PR','FÓRUM CÍVEL DE COLOMBO','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0194','FÓRUM CÍVEL DE CURITIBA - MATEUS LEME','PR','FÓRUM CÍVEL DE CURITIBA - MATEUS LEME','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0195','FÓRUM DESCENTRALIZADO DO BOQUEIRÃO DA COMARCA DE CURITIBA','PR','FÓRUM DESCENTRALIZADO DO BOQUEIRÃO DA COMARCA DE CURITIBA','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0196','CENTRO JUDICIÁRIO DE CURITIBA - AHÚ','PR','CENTRO JUDICIÁRIO DE CURITIBA - AHÚ','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0197','FÓRUM CÍVEL DE MARINGÁ','PR','FÓRUM CÍVEL DE MARINGÁ','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0198','FÓRUM DO JUIZADO DE VIOLÊNCIA DOMÉSTICA E FAMILIAR CONTRA A MULHER E VEPMA DE MARINGÁ','PR','FÓRUM DO JUIZADO DE VIOLÊNCIA DOMÉSTICA E FAMILIAR CONTRA A MULHER E VEPMA DE MARINGÁ','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0199','FÓRUM DAS VARAS CRIMINAIS, FAMÍLIA, INFÂNCIA E JUVENTUDE E EXECUÇÕES PENAIS DE MARINGÁ','PR','FÓRUM DAS VARAS CRIMINAIS, FAMÍLIA, INFÂNCIA E JUVENTUDE E EXECUÇÕES PENAIS DE MARINGÁ','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0200','FÓRUM DESCENTRALIZADO DO BAIRRO NOVO DA COMARCA DE CURITIBA','PR','FÓRUM DESCENTRALIZADO DO BAIRRO NOVO DA COMARCA DE CURITIBA','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0201','TRIBUNAL DE JUSTIÇA - PRÉDIO MAUÁ','PR','TRIBUNAL DE JUSTIÇA - PRÉDIO MAUÁ','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0202','FÓRUM DA VARA DA FAZENDA PÚBLICA - FORO REGIONAL DE SÃO JOSÉ DOS PINHAIS','PR','FÓRUM DA VARA DA FAZENDA PÚBLICA - FORO REGIONAL DE SÃO JOSÉ DOS PINHAIS','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0203','FÓRUM DO JUIZADO DE VIOLÊNCIA DOMÉSTICA E FAMILIAR CONTRA A MULHER E DA VARA DA INFÂNCIA E JUVENTUDE - FORO REGIONAL DE SÃO JOSÉ DOS PINHAIS','PR','FÓRUM DO JUIZADO DE VIOLÊNCIA DOMÉSTICA E FAMILIAR CONTRA A MULHER E DA VARA DA INFÂNCIA E JUVENTUDE - FORO REGIONAL DE SÃO JOSÉ DOS PINHAIS','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0204','FÓRUM DO JUIZADO ESPECIAL PUC-CAJURU - CURITIBA','PR','FÓRUM DO JUIZADO ESPECIAL PUC-CAJURU - CURITIBA','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0205','FÓRUM DOS JUIZADO ESPECIAIS DE IRATI','PR','FÓRUM DOS JUIZADO ESPECIAIS DE IRATI','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0206','FÓRUM DA 2ª VARA CÍVEL DE IRATI','PR','FÓRUM DA 2ª VARA CÍVEL DE IRATI','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0207','FÓRUM DA VARA DE FAMÍLIA E SUCESSÕES DE UNIÃO DA VITÓRIA','PR','FÓRUM DA VARA DE FAMÍLIA E SUCESSÕES DE UNIÃO DA VITÓRIA','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0208','FÓRUM DA VARA DE FAMÍLIA E SUCESSÕES DE PARANAGUÁ','PR','FÓRUM DA VARA DE FAMÍLIA E SUCESSÕES DE PARANAGUÁ','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0209','FÓRUM DOS JUIZADOS ESPECIAIS DE FRANCISCO BELTRÃO','PR','FÓRUM DOS JUIZADOS ESPECIAIS DE FRANCISCO BELTRÃO','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0210','FÓRUM DE PAIÇANDU','PR','FÓRUM DE PAIÇANDU','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','0211','FÓRUM DE QUATRO BARRAS','PR','FÓRUM DE QUATRO BARRAS','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','6000','SISTEMA ELETRÔNICO DE INFORMAÇÕES - SEI','PR','SISTEMA ELETRÔNICO DE INFORMAÇÕES - SEI','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','7000','TRIBUNAL DE JUSTIÇA','PR','TRIBUNAL DE JUSTIÇA','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree'),
('TJPR','9000','TURMA RECURSAL ÚNICA','PR','TURMA RECURSAL ÚNICA','https://portal.tjpr.jus.br/snu/internet/inicio.do?actionType=visualizarTree')
) AS v(sigla, codigo, nome, uf, foro, fonte)
JOIN public.cnj_tribunais t ON t.sigla = v.sigla
ON CONFLICT (tribunal_id, codigo_origem) DO NOTHING;
