import type { Post } from "./tipos";

const CTA = "Solicite a Certidão de Objeto e Pé com nossa equipe: informe apenas o número do processo, o nome completo e o CPF da parte. Cuidamos do protocolo no tribunal correto e enviamos o documento digital.";

export const POSTS_CONCEITO: Post[] = [
  {
    slug: "o-que-e-certidao-de-objeto-e-pe",
    categoria: "conceito",
    titulo: "O que é Certidão de Objeto e Pé e para que serve",
    h1: "O que é Certidão de Objeto e Pé e para que serve",
    descricao:
      "O que é, o que consta, para que serve, quem pode pedir, prazo e custo da Certidão de Objeto e Pé — o documento do tribunal que descreve o processo e a fase atual.",
    resumo:
      "O documento judicial que resume do que trata um processo e em que fase ele está — explicado do zero, com os 10 usos mais cobrados na prática.",
    atualizado: "2026-09-03",
    leitura: 9,

    blocos: [
      { t: "p", x: "A Certidão de Objeto e Pé é o documento oficial expedido pelo Poder Judiciário que descreve, em um único texto, duas informações sobre um processo: o objeto (do que se trata a ação, quem são as partes e o que se pede) e o pé (a fase atual do andamento, ou seja, em que ponto o processo está hoje)." },
      { t: "p", x: "Ela é emitida pela própria unidade judiciária onde o processo tramita ou tramitou — vara estadual, federal, do trabalho ou tribunal superior — e traz código de autenticidade que permite conferir o documento no portal do tribunal." },
      { t: "h", x: "O que consta na Certidão de Objeto e Pé" },
      { t: "ul", items: [
        "Número do processo no padrão CNJ e a classe processual (execução, procedimento comum, reclamação trabalhista etc.).",
        "Vara, foro ou comarca responsável e o juízo em que o feito tramita.",
        "Nome e qualificação das partes: autor/exequente/reclamante e réu/executado/reclamado.",
        "Objeto: descrição resumida do que se discute, com o valor da causa quando aplicável.",
        "Data da distribuição e histórico das principais movimentações.",
        "Pé: situação atual — em instrução, com sentença, em grau de recurso, em execução, suspenso, arquivado, extinto ou transitado em julgado.",
        "Data de expedição, assinatura do servidor responsável e código de validação.",
      ] },
      { t: "h", x: "Por que esse nome estranho?" },
      { t: "p", x: "A expressão vem da linguagem forense tradicional. \"Objeto\" é a matéria discutida; \"pé\" é o pé do processo, isto é, o ponto em que ele se encontra — como quem pergunta \"em que pé está isso?\". Por isso a certidão também aparece com os nomes certidão narratória, certidão de andamento processual ou certidão circunstanciada, dependendo do tribunal." },
      { t: "h", x: "Para que serve a Certidão de Objeto e Pé" },
      { t: "p", x: "A certidão é pedida sempre que alguém precisa entender um processo sem ler o processo inteiro. Ela transforma centenas de páginas em um resumo oficial e assinado pelo tribunal. Estes são os usos mais frequentes:" },
      { t: "ul", items: [
        "Análise de crédito e financiamento: o banco quer saber se o processo é uma cobrança milionária ou uma ação sem impacto patrimonial.",
        "Gerenciadora de risco e motoristas: transportadoras exigem a certidão para liberar cadastro quando surge apontamento criminal ou cível.",
        "Compra e venda de imóveis: mostra se há penhora, se a ação é patrimonial e em que fase está, afastando risco de fraude à execução.",
        "Licitações e cadastro de fornecedores: esclarece ações que constem em certidões positivas com efeito de negativa.",
        "Concursos públicos e posse em cargo: na investigação social, comprova se o processo criminal está arquivado, absolvido ou em curso.",
        "Vistos, cidadania e imigração: consulados aceitam a certidão, muitas vezes com tradução juramentada e apostila de Haia.",
        "Admissão e compliance: programas de integridade pedem o documento em contratações sensíveis e due diligence de sócios.",
        "Seguros: seguradoras avaliam sinistros e riscos pela fase real do processo.",
        "Instrução de outro processo: advogados juntam a certidão para comprovar litispendência, prevenção, conexão ou o teor de uma decisão.",
        "Regularização pessoal: descobrir exatamente o que aconteceu em um processo antigo e se ainda há algo pendente.",
      ] },
      { t: "h", x: "Quem pode solicitar" },
      { t: "p", x: "Qualquer pessoa física ou jurídica pode pedir a certidão de processo público, mesmo sem ser parte e sem advogado, porque a publicidade dos atos processuais é regra constitucional. A exceção são os processos em segredo de justiça, restritos às partes e a seus procuradores." },
      { t: "h", x: "Quanto tempo demora e quanto custa" },
      { t: "tabela", head: ["Ramo", "Prazo médio", "Observação"], rows: [
        ["Justiça Estadual", "1 a 5 dias úteis, conforme a comarca e o tribunal emissor", "Varia conforme a comarca e o tribunal"],
        ["Justiça Federal", "1 a 5 dias úteis, conforme a comarca e o tribunal emissor", "Varia conforme a seção judiciária e o tribunal"],
        ["Justiça do Trabalho", "1 a 5 dias úteis, conforme a comarca e o tribunal emissor", "Varia conforme a unidade emissora"],
        ["Tribunais superiores", "1 a 5 dias úteis, conforme a comarca e o tribunal emissor", "Varia conforme o tribunal emissor"],
      ] },
      { t: "p", x: "Alguns tribunais cobram taxa ou custas de expedição; outros emitem gratuitamente pela internet quando o processo é eletrônico e público. O custo do serviço de assessoria é separado das custas e cobre a identificação da vara, o protocolo do requerimento, o acompanhamento e a entrega digital." },
      { t: "nota", x: "A certidão não remove nem altera o processo. Ela apenas documenta oficialmente o que está lá — e é justamente essa transparência que costuma resolver a exigência de quem pediu o documento." },
      { t: "cta", x: CTA },
    ],
    faq: [
      { q: "O que é Certidão de Objeto e Pé?", a: "É a certidão oficial emitida pelo Poder Judiciário que descreve o objeto do processo (do que se trata, partes e pedido) e o pé (a fase atual do andamento), com código de autenticidade conferível no portal do tribunal." },
      { q: "Para que serve a Certidão de Objeto e Pé?", a: "Serve para explicar oficialmente um processo a quem exigiu o documento: bancos, gerenciadoras de risco, cartórios e compradores de imóvel, órgãos de licitação, bancas de concurso, consulados e departamentos de compliance." },
      { q: "Qualquer pessoa pode pedir?", a: "Sim, para processos públicos, mesmo sem ser parte e sem advogado. Processos em segredo de justiça só podem ser certificados às partes e a seus advogados constituídos." },
      { q: "A certidão apaga o processo do meu nome?", a: "Não. Ela apenas descreve oficialmente o processo e sua fase atual. Nenhuma certidão exclui ou altera um processo judicial." },
      { q: "Preciso de uma certidão por processo?", a: "Sim. Cada certidão se refere a um processo específico. Se houver mais de um, é preciso uma para cada." },
      { q: "Quanto tempo demora para sair?", a: "De 1 a 5 dias úteis, conforme a comarca e o tribunal emissor." },
    ],
  },

  {
    slug: "diferenca-objeto-e-pe-e-inteiro-teor",
    categoria: "conceito",
    titulo: "Objeto e Pé x Inteiro Teor: qual a diferença e qual pedir",
    h1: "Diferença entre Certidão de Objeto e Pé e Certidão de Inteiro Teor",
    descricao:
      "Objeto e Pé resume o processo em poucas páginas; inteiro teor reproduz peças na íntegra. Entenda qual documento pedir em cada situação.",
    resumo: "Dois documentos frequentemente confundidos — e a regra simples para escolher o certo.",
    atualizado: "2026-08-26",
    leitura: 5,
    blocos: [
      { t: "p", x: "A dúvida é comum porque as duas certidões saem do mesmo lugar e falam do mesmo processo. A diferença está na profundidade." },
      { t: "tabela", head: ["Critério", "Objeto e Pé", "Inteiro teor"], rows: [
        ["Conteúdo", "Resumo oficial: partes, objeto e fase atual", "Reprodução integral de peças ou de todo o processo"],
        ["Tamanho", "1 a 5 páginas", "Dezenas a milhares de páginas"],
        ["Prazo", "Mais rápido", "Mais demorado, sobretudo em processo físico"],
        ["Custo", "Menor", "Maior, geralmente por página"],
        ["Uso típico", "Bancos, gerenciadoras, licitações, concursos", "Perícia, recursos, defesa técnica, prova documental"],
      ] },
      { t: "h", x: "Regra prática para escolher" },
      { t: "ol", items: [
        "Se pediram para você 'explicar' um processo que apareceu no seu nome: Objeto e Pé.",
        "Se pediram a sentença, o acórdão ou uma peça específica: inteiro teor daquela peça.",
        "Se um advogado precisa analisar toda a prova: inteiro teor do processo.",
        "Se a exigência não é clara, comece pela Objeto e Pé — é mais rápida e barata e resolve a maioria dos casos.",
      ] },
      { t: "nota", x: "É possível pedir as duas: a Objeto e Pé para entregar rapidamente a quem exigiu e o inteiro teor de uma peça específica quando o conteúdo da decisão precisa ser comprovado." },
      { t: "cta", x: CTA },
    ],
    faq: [
      { q: "Objeto e pé e inteiro teor são a mesma coisa?", a: "Não. A Objeto e Pé é um resumo oficial do processo e de sua fase; o inteiro teor reproduz peças processuais na íntegra." },
      { q: "Qual é mais aceita por bancos e gerenciadoras?", a: "Na prática, a Certidão de Objeto e Pé, porque descreve objetivamente o objeto e a situação do processo." },
      { q: "O inteiro teor substitui a objeto e pé?", a: "Nem sempre. Muitos órgãos exigem expressamente a certidão de objeto e pé, com a fase atual certificada pelo cartório." },
    ],
  },
  {
    slug: "o-que-e-certidao-narratoria",
    categoria: "conceito",
    titulo: "O que é Certidão Narratória e como pedir (guia 2026)",
    h1: "O que é Certidão Narratória",
    descricao:
      "Certidão narratória é o documento em que o tribunal narra os atos de um processo. Veja o que consta, para que serve, diferenças para a Certidão de Objeto e Pé, prazo e como solicitar online.",
    resumo:
      "Guia completo da certidão narratória: o que é, o que aparece no documento, quando ela é exigida e por que, na maioria dos tribunais, ela equivale à Certidão de Objeto e Pé.",
    atualizado: "2026-09-22",
    leitura: 7,
    blocos: [
      { t: "p", x: "Certidão narratória é o documento oficial em que a unidade judiciária narra, em texto corrido, os atos e fatos relevantes de um processo: quem são as partes, do que se trata a ação, quando foi distribuída, quais decisões foram proferidas e qual é a situação atual do feito. O nome vem justamente do verbo narrar — o servidor conta a história do processo em um documento assinado e com código de autenticidade." },
      { t: "p", x: "Na prática forense brasileira, certidão narratória e Certidão de Objeto e Pé costumam ser tratadas como o mesmo documento. Cada tribunal adota a nomenclatura que consta no seu regimento ou no menu de requerimentos do sistema eletrônico: em alguns aparece \"objeto e pé\", em outros \"narratória\", \"circunstanciada\" ou \"de andamento processual\"." },
      { t: "h", x: "O que consta em uma certidão narratória" },
      { t: "ul", items: [
        "Número do processo no padrão CNJ, classe e assunto.",
        "Vara, foro, comarca ou seção judiciária onde o feito tramita.",
        "Nome e qualificação das partes e dos advogados constituídos.",
        "Objeto: resumo do que se discute e o valor da causa, quando houver.",
        "Data da distribuição e narrativa das principais movimentações.",
        "Situação atual: em instrução, com sentença, em grau de recurso, em execução, suspenso, arquivado ou transitado em julgado.",
        "Data de expedição, identificação do servidor e código de validação conferível no portal do tribunal.",
      ] },
      { t: "h", x: "Certidão narratória e Certidão de Objeto e Pé: qual a diferença" },
      { t: "p", x: "As duas são expedidas pela mesma unidade judiciária, têm o mesmo valor oficial e servem ao mesmo propósito: explicar oficialmente um processo a quem não tem acesso aos autos. A diferença, quando existe, é de ênfase." },
      { t: "tabela", head: ["Aspecto", "Certidão narratória", "Certidão de Objeto e Pé"], rows: [
        ["Foco principal", "Narrativa cronológica dos atos praticados", "Objeto do processo e fase atual (o \"pé\")"],
        ["Formato", "Texto corrido, mais descritivo", "Estrutura mais padronizada por tribunal"],
        ["Valor oficial", "Documento judicial com código de autenticidade", "Documento judicial com código de autenticidade"],
        ["Disponibilidade", "Nem todo tribunal usa esse nome no requerimento", "Nomenclatura mais difundida nos tribunais estaduais"],
      ] },
      { t: "p", x: "Por isso, quando a empresa, o órgão ou o consulado pede \"certidão narratória\" sem mais detalhes, o caminho seguro é requerer a certidão com objeto, partes, fase atual e histórico das movimentações — conteúdo que atende às duas exigências." },
      { t: "h", x: "Para que a certidão narratória costuma ser exigida" },
      { t: "p", x: "A certidão pode ser solicitada por qualquer interessado e é útil sempre que alguém precisa entender oficialmente um processo sem ler os autos inteiros. Entre as situações mais comuns:" },
      { t: "ul", items: [
        "Análise cadastral e de crédito, quando surge um processo em consulta de nome ou CPF.",
        "Cadastro de motoristas e transportadores em plataformas de gestão de risco.",
        "Compra e venda de imóveis e due diligence, para verificar penhora ou ação patrimonial.",
        "Licitações e cadastro de fornecedores, esclarecendo certidões positivas.",
        "Concursos públicos e investigação social, para demonstrar a fase real de um processo criminal.",
        "Vistos, cidadania e processos de imigração, muitas vezes com tradução juramentada.",
        "Instrução de outro processo judicial, para comprovar conexão, prevenção ou teor de decisão.",
      ] },
      { t: "nota", x: "Confirme sempre com a empresa ou o órgão que fez a exigência qual documento exatamente é aceito e se há prazo de validade. A certidão narratória descreve o processo — ela não remove, cancela nem limpa qualquer processo judicial." },
      { t: "h", x: "Quem pode pedir e o que é necessário" },
      { t: "p", x: "Processos públicos podem ser certificados a qualquer pessoa, mesmo sem ser parte e sem advogado, porque a publicidade dos atos processuais é regra constitucional. Processos em segredo de justiça são restritos às partes e a seus procuradores. Para o requerimento, normalmente basta o número do processo no padrão CNJ, o nome completo e o CPF ou CNPJ da parte." },
      { t: "h", x: "Consulta pública não substitui a certidão" },
      { t: "p", x: "O andamento que aparece na consulta pública do site do tribunal é informativo: não tem assinatura, não é documento oficial e costuma ser recusado por quem exige comprovação. A certidão narratória, ao contrário, é expedida pela unidade judiciária, é assinada e pode ser conferida pelo código de autenticidade." },
      { t: "h", x: "Prazo e como solicitar online" },
      { t: "p", x: "O prazo usual é de 1 a 5 dias úteis, conforme a comarca e o tribunal emissor. Pela internet, o requerimento é protocolado na unidade correta a partir do número do processo, acompanhado até a expedição e entregue em arquivo digital, com protocolo de acompanhamento." },
      { t: "cta", x: CTA },
    ],
    faq: [
      { q: "O que é certidão narratória?", a: "É o documento oficial em que o tribunal narra os atos e fatos de um processo: partes, objeto, distribuição, principais movimentações e situação atual, com código de autenticidade conferível no portal do tribunal." },
      { q: "Certidão narratória é a mesma coisa que Certidão de Objeto e Pé?", a: "Na maioria dos tribunais, sim: são nomes diferentes para a certidão que descreve o processo e sua fase. Em alguns, a narratória detalha mais a cronologia dos atos." },
      { q: "Qual devo pedir se a empresa não especificou?", a: "Peça a Certidão de Objeto e Pé com histórico de movimentações — esse conteúdo costuma atender às duas exigências. Confirme com quem pediu se há alguma especificação adicional." },
      { q: "Preciso de advogado para pedir?", a: "Não, quando o processo é público. Em processos sob segredo de justiça, apenas as partes e seus advogados constituídos podem obter a certidão." },
      { q: "Quanto tempo demora?", a: "De 1 a 5 dias úteis, conforme a comarca e o tribunal emissor." },
      { q: "O print do andamento do site do tribunal serve?", a: "Normalmente não. A consulta pública é informativa e não tem assinatura nem código de autenticidade; a certidão é o documento oficial." },
    ],
  },
  {
    slug: "certidao-objeto-e-pe-x-nada-consta",
    categoria: "conceito",
    titulo: "Objeto e Pé x Nada Consta (negativa): entenda a diferença",
    h1: "Certidão de Objeto e Pé x Certidão Negativa (nada consta)",
    descricao:
      "A negativa diz se existe processo; a objeto e pé explica o processo que existe. Saiba quando cada uma é exigida e como se complementam.",
    resumo: "Quando a negativa vem 'positiva', a objeto e pé é o passo seguinte.",
    atualizado: "2026-09-03",
    leitura: 6,
    blocos: [
      { t: "p", x: "A certidão negativa (ou 'nada consta') responde a uma pergunta binária: existe processo em nome desta pessoa ou empresa? A Certidão de Objeto e Pé responde a outra: o que é e em que fase está este processo específico?" },
      { t: "tabela", head: ["Aspecto", "Certidão negativa", "Objeto e Pé"], rows: [
        ["Pergunta que responde", "Existe processo em nome desta pessoa?", "Do que trata e em que fase está este processo?"],
        ["Pedido por", "Nome e CPF/CNPJ", "Número do processo"],
        ["Resultado possível", "Negativa ou positiva", "Descrição detalhada do processo"],
        ["Emissão", "Automática, em minutos", "Expedida pela vara, com prazo"],
        ["Uso típico", "Triagem inicial", "Esclarecer o apontamento"],
      ] },
      { t: "h", x: "Qual documento apresentar em cada situação" },
      { t: "tabela", head: ["Situação", "Documento indicado"], rows: [
        ["Comprovar que não há processos", "Certidão negativa (nada consta)"],
        ["A negativa saiu positiva e pediram esclarecimento", "Certidão de Objeto e Pé de cada processo"],
        ["Comprovar arquivamento ou absolvição", "Certidão de Objeto e Pé"],
        ["Habilitação em licitação com ação em curso", "Negativa + Objeto e Pé das ações apontadas"],
      ] },
      { t: "h", x: "Por que a negativa costuma vir 'positiva'" },
      { t: "p", x: "A busca é feita por nome e CPF/CNPJ. Homônimos, processos antigos, ações em que a pessoa foi apenas testemunha ou terceiro interessado e feitos já arquivados podem aparecer. A objeto e pé é exatamente o documento que esclarece cada apontamento." },
      { t: "p", x: "O fluxo natural é: pede-se a negativa; se ela sai positiva, pede-se a Certidão de Objeto e Pé de cada processo listado para explicar o apontamento." },
      { t: "cta", x: CTA },
    ],
    faq: [
      { q: "Minha certidão negativa veio com processos. E agora?", a: "Solicite a Certidão de Objeto e Pé de cada processo apontado: ela descreve o objeto e a fase, o que normalmente basta para o banco, a gerenciadora ou o órgão público." },
      { q: "Posso apresentar só a negativa positiva?", a: "Não resolve. Quem exige o documento quer saber o conteúdo e a fase do processo, e isso só a Certidão de Objeto e Pé informa." },
      { q: "Posso pedir as duas ao mesmo tempo?", a: "Sim, e é o mais comum em licitações e processos de admissão: a negativa mostra o panorama e a objeto e pé explica cada apontamento." },
    ],

  },
  {
    slug: "validade-certidao-de-objeto-e-pe",
    categoria: "conceito",
    titulo: "Validade da Certidão de Objeto e Pé: quanto tempo vale",
    h1: "Qual a validade da Certidão de Objeto e Pé",
    descricao:
      "A certidão não tem prazo de validade legal fixo: quem exige o documento define o período aceito, normalmente de 30 a 90 dias. Entenda.",
    resumo: "Não existe prazo legal único — existe o prazo que o destinatário aceita.",
    atualizado: "2026-08-26",
    leitura: 4,
    blocos: [
      { t: "p", x: "A Certidão de Objeto e Pé retrata o processo na data da expedição. Como o andamento muda, quem exige o documento estabelece um prazo de aceitação." },
      { t: "tabela", head: ["Quem exige", "Prazo aceito na prática"], rows: [
        ["Bancos e financeiras", "30 a 60 dias"],
        ["Gerenciadoras de risco", "30 dias"],
        ["Licitações e órgãos públicos", "60 a 90 dias, conforme o edital"],
        ["Consulados e imigração", "90 dias, às vezes com apostila"],
        ["Cartórios e negócios imobiliários", "30 a 90 dias"],
      ] },
      { t: "nota", x: "Antes de pedir, confirme o prazo exigido no edital, no contrato ou no e-mail de exigência. Isso evita ter de repetir a solicitação." },
      { t: "cta", x: CTA },
    ],
    faq: [
      { q: "A Certidão de Objeto e Pé tem validade de 30 dias?", a: "Não há prazo legal fixo. Na prática, os destinatários costumam aceitar certidões expedidas nos últimos 30 a 90 dias." },
      { q: "Preciso emitir de novo se o processo não mudou?", a: "Sim, se o destinatário exigir data recente. A validade é definida por quem recebe o documento, não pelo tribunal." },
    ],
  },
  {
    slug: "como-ler-certidao-de-objeto-e-pe",
    categoria: "conceito",
    titulo: "Como ler a Certidão de Objeto e Pé campo por campo",
    h1: "Como ler e interpretar a Certidão de Objeto e Pé",
    descricao:
      "Entenda cada campo da certidão: classe processual, valor da causa, partes, movimentações, trânsito em julgado e situação do processo.",
    resumo: "Um guia de leitura para quem recebeu a certidão e não sabe o que os termos significam.",
    atualizado: "2026-08-26",
    leitura: 6,
    blocos: [
      { t: "h", x: "Cabeçalho e identificação" },
      { t: "p", x: "Traz o tribunal, a comarca/seção, a vara e o número CNJ. Os 20 dígitos do número indicam sequencial, dígito verificador, ano, segmento da Justiça, tribunal e unidade de origem." },
      { t: "h", x: "Classe e assunto" },
      { t: "p", x: "A classe indica o tipo de ação (procedimento comum, execução de título extrajudicial, ação penal, reclamação trabalhista). O assunto detalha a matéria (inadimplemento, dano moral, furto, verbas rescisórias)." },
      { t: "h", x: "Partes" },
      { t: "p", x: "Verifique em qual polo a pessoa aparece. Ser réu ou executado é diferente de ser autor, testemunha ou terceiro interessado — e essa distinção muitas vezes resolve a exigência." },
      { t: "h", x: "Termos que aparecem no 'pé'" },
      { t: "tabela", head: ["Termo", "Significa"], rows: [
        ["Concluso para decisão", "Aguardando análise do juiz"],
        ["Em instrução", "Fase de provas e audiências"],
        ["Sentenciado", "Já há sentença, possivelmente com recurso pendente"],
        ["Trânsito em julgado", "Não cabe mais recurso"],
        ["Em fase de execução / cumprimento de sentença", "Cobrança do que foi decidido"],
        ["Suspenso / sobrestado", "Parado por decisão ou por lei"],
        ["Arquivado definitivamente", "Encerrado, sem pendências no juízo"],
        ["Baixa definitiva", "Registro encerrado no tribunal"],
      ] },
      { t: "h", x: "Autenticidade" },
      { t: "p", x: "No rodapé há o código de validação. Ele pode ser conferido no portal do tribunal, que reproduz o documento original — é assim que o destinatário confirma que a certidão é verdadeira." },
      { t: "cta", x: CTA },
    ],
    faq: [
      { q: "O que significa 'arquivado' na certidão?", a: "Que o processo foi encerrado naquele juízo. A certidão indica se o arquivamento é provisório (pode ser retomado) ou definitivo." },
      { q: "Como sei se ainda posso ser cobrado?", a: "Verifique se há fase de execução ou cumprimento de sentença em curso. Se houver trânsito em julgado e arquivamento definitivo, não há cobrança pendente naquele processo." },
    ],
  },
  {
    slug: "certidao-objeto-e-pe-e-legalizada",
    categoria: "conceito",
    titulo: "A Certidão de Objeto e Pé é documento oficial? Base legal",
    h1: "Base legal e valor oficial da Certidão de Objeto e Pé",
    descricao:
      "A certidão tem fundamento na Constituição e no CPC: publicidade dos atos processuais e direito de obter certidões em repartições públicas.",
    resumo: "Por que o tribunal é obrigado a fornecer a certidão e qual o valor jurídico do documento.",
    atualizado: "2026-08-26",
    leitura: 5,
    blocos: [
      { t: "p", x: "O direito de obter a certidão nasce da Constituição Federal, que assegura a todos, independentemente de taxas, a obtenção de certidões em repartições públicas para defesa de direitos e esclarecimento de situações de interesse pessoal (art. 5º, XXXIV, 'b'), e determina a publicidade dos atos processuais (art. 5º, LX, e art. 93, IX)." },
      { t: "p", x: "O Código de Processo Civil complementa ao prever que os autos são públicos, salvo segredo de justiça, e que terceiros podem requerer certidão do dispositivo da sentença e do inventário e partilha nos casos previstos em lei (arts. 11 e 189)." },
      { t: "h", x: "Consequências práticas" },
      { t: "ul", items: [
        "O cartório não pode negar a certidão de processo público sem fundamento legal.",
        "Em segredo de justiça, apenas partes e advogados constituídos obtêm a certidão completa.",
        "O documento é público e faz prova da situação processual perante qualquer órgão.",
        "A assinatura eletrônica do servidor e o código de autenticidade garantem a integridade.",
      ] },
      { t: "cta", x: CTA },
    ],
    faq: [
      { q: "O tribunal pode recusar a certidão?", a: "Somente com fundamento legal, como segredo de justiça ou sigilo determinado por decisão judicial. Processos públicos devem ser certificados." },
      { q: "A certidão digital tem o mesmo valor da impressa?", a: "Sim. A versão eletrônica assinada digitalmente, com código de autenticidade, tem o mesmo valor jurídico." },
    ],
  },
];
