import type { Post } from "./tipos";

const CTA = "Não quer lidar com sistemas de tribunal? Envie o número do processo, o nome e o CPF da parte: identificamos a vara correta, protocolamos o requerimento e entregamos a certidão digital.";

export const POSTS_TRIBUNAIS: Post[] = [
  {
    slug: "como-emitir-certidao-de-objeto-e-pe",
    categoria: "tribunais",
    titulo: "Como emitir Certidão de Objeto e Pé: passo a passo 2026",
    h1: "Como emitir a Certidão de Objeto e Pé passo a passo",
    descricao:
      "Passo a passo para emitir a Certidão de Objeto e Pé em qualquer tribunal: identificar a vara, protocolar o requerimento, pagar custas e retirar o documento.",
    resumo: "O caminho completo, do número do processo à certidão assinada, em qualquer tribunal do país.",
    atualizado: "2026-08-26",
    leitura: 7,
    blocos: [
      { t: "p", x: "Emitir a Certidão de Objeto e Pé é sempre a mesma lógica, independentemente do tribunal: descobrir onde o processo está, requerer a certidão àquela unidade, pagar as custas quando houver e retirar o documento assinado." },
      { t: "h", x: "Passo 1 — Reúna as informações mínimas" },
      { t: "ul", items: [
        "Número do processo no padrão CNJ (20 dígitos).",
        "Nome completo da parte envolvida.",
        "CPF ou CNPJ da parte.",
        "Se possível, comarca/foro e vara.",
      ] },
      { t: "p", x: "Sem o número do processo ainda é possível localizar o feito por nome e CPF nas consultas públicas dos tribunais, mas o resultado depende de o tribunal permitir busca por parte." },
      { t: "h", x: "Passo 2 — Identifique o tribunal e o sistema" },
      { t: "p", x: "Os dígitos 14 a 16 do número CNJ indicam o segmento e o tribunal. Justiça Estadual usa o segmento 8, Justiça Federal o 4, Justiça do Trabalho o 5, Justiça Eleitoral o 6 e Justiça Militar da União o 7. Cada tribunal opera em um sistema: e-SAJ, PJe, Projudi ou eproc." },
      { t: "h", x: "Passo 3 — Requeira a certidão" },
      { t: "ol", items: [
        "Processo eletrônico e público: peticionamento eletrônico ou formulário de requerimento de certidão no portal do tribunal.",
        "Processo físico ou arquivado: requerimento dirigido ao cartório da vara, muitas vezes com pedido de desarquivamento.",
        "Processo em segredo de justiça: apenas parte ou advogado constituído, com procuração.",
      ] },
      { t: "h", x: "Passo 4 — Custas" },
      { t: "p", x: "Alguns tribunais emitem gratuitamente, outros cobram taxa de expedição por página ou por certidão, com guia própria. O recolhimento incorreto é a causa mais frequente de indeferimento." },
      { t: "h", x: "Passo 5 — Retirada e conferência" },
      { t: "p", x: "A certidão sai em PDF assinado com código de autenticidade. Confira o número do processo, o nome da parte, o objeto e, principalmente, se o 'pé' descreve a fase atual — é isso que o destinatário vai ler." },
      { t: "h", x: "Erros que mais atrasam" },
      { t: "ul", items: [
        "Número CNJ digitado incompleto ou com dígito errado.",
        "Requerimento enviado à vara errada após redistribuição do processo.",
        "Pedido genérico, sem indicar que se quer objeto e fase atual.",
        "Falta de recolhimento de custas ou guia vencida.",
        "Processo físico antigo sem pedido de desarquivamento.",
      ] },
      { t: "cta", x: CTA },
    ],
    faq: [
      { q: "Preciso de advogado para emitir?", a: "Não, em processos públicos. Só é necessário advogado ou procuração em processos que tramitam em segredo de justiça." },
      { q: "Dá para emitir sem o número do processo?", a: "É possível localizar o processo por nome e CPF nas consultas públicas de muitos tribunais, mas o pedido da certidão sempre se refere a um processo identificado." },
      { q: "Quanto tempo leva?", a: "De 1 a 5 dias úteis, conforme a comarca e o tribunal emissor." },
    ],
  },
  {
    slug: "certidao-de-objeto-e-pe-esaj",
    categoria: "tribunais",
    titulo: "Certidão de Objeto e Pé no e-SAJ: Como Pedir Passo a Passo",
    h1: "Como pedir a Certidão de Objeto e Pé no e-SAJ",
    descricao:
      "Veja como pedir a Certidão de Objeto e Pé no e-SAJ (TJSP, TJMS, TJAL e outros): consulta do processo, requerimento, custas e validação. Ou solicite online.",
    resumo: "Guia do sistema e-SAJ, adotado por vários tribunais estaduais.",
    atualizado: "2026-08-26",
    leitura: 5,
    blocos: [
      { t: "p", x: "O e-SAJ (Sistema de Automação da Justiça) é a plataforma usada por tribunais como TJSP, TJMS e TJAL, entre outros, para consulta processual, peticionamento e emissão de certidões." },
      { t: "h", x: "Como funciona o pedido" },
      { t: "ol", items: [
        "Consulta processual de 1º grau pelo número CNJ, para confirmar foro e vara.",
        "Acesso ao peticionamento eletrônico com certificado digital ou cadastro habilitado.",
        "Escolha do tipo de petição: requerimento de certidão de objeto e pé.",
        "Anexação do requerimento e da guia de custas, quando exigida.",
        "Aguardar a juntada e a expedição pelo cartório da vara.",
      ] },
      { t: "h", x: "Pontos de atenção no e-SAJ" },
      { t: "ul", items: [
        "Processos digitalizados antigos podem estar em 'consulta de processos físicos', com fluxo distinto.",
        "Segredo de justiça bloqueia o peticionamento por terceiros.",
        "O código de autenticidade da certidão é conferido na área de validação de documentos do portal.",
      ] },
      { t: "cta", x: CTA },
    ],
    faq: [
      { q: "Preciso de certificado digital para usar o e-SAJ?", a: "Para peticionar, na maioria dos casos sim, ou um cadastro habilitado no portal. A consulta pública dispensa certificado." },
      { q: "Quais tribunais usam e-SAJ?", a: "Entre outros, TJSP, TJMS e TJAL, além de tribunais que mantêm o sistema em módulos específicos." },
    ],
  },
  {
    slug: "certidao-de-objeto-e-pe-pje",
    categoria: "tribunais",
    titulo: "Certidão de Objeto e Pé no PJe: guia prático",
    h1: "Certidão de Objeto e Pé no PJe",
    descricao:
      "O PJe é o sistema mais usado no Brasil, presente na Justiça do Trabalho, Federal e em vários TJs. Veja como requerer a certidão.",
    resumo: "O sistema mais difundido do Judiciário brasileiro, do pedido à validação.",
    atualizado: "2026-08-26",
    leitura: 5,
    blocos: [
      { t: "p", x: "O PJe (Processo Judicial Eletrônico), desenvolvido pelo CNJ, é usado por toda a Justiça do Trabalho, pela maior parte da Justiça Federal e por dezenas de tribunais estaduais." },
      { t: "h", x: "Caminho do pedido" },
      { t: "ol", items: [
        "Consulta pública do PJe do tribunal para confirmar o órgão julgador.",
        "Acesso ao sistema com certificado digital (ou login gov.br, onde disponível).",
        "Peticionamento avulso ou requerimento dirigido à secretaria da vara.",
        "Indicação expressa de que se requer certidão de objeto e pé, com a fase atual.",
        "Acompanhamento até a juntada da certidão nos autos.",
      ] },
      { t: "h", x: "Particularidades" },
      { t: "ul", items: [
        "Cada tribunal tem sua própria instância do PJe, com endereço e regras de custas distintas.",
        "Processos migrados de sistemas antigos podem ter parte do histórico fora do PJe.",
        "Na Justiça do Trabalho, o PJe concentra praticamente todo o acervo eletrônico.",
      ] },
      { t: "cta", x: CTA },
    ],
    faq: [
      { q: "Quem pode peticionar no PJe?", a: "Advogados e partes habilitadas com certificado digital; terceiros geralmente requerem por protocolo eletrônico avulso ou diretamente à secretaria." },
      { q: "O PJe é igual em todos os tribunais?", a: "A base é a mesma, mas cada tribunal mantém sua instalação, com versões e fluxos ligeiramente diferentes." },
    ],
  },
  {
    slug: "certidao-de-objeto-e-pe-projudi-eproc",
    categoria: "tribunais",
    titulo: "Certidão de Objeto e Pé no Projudi e no eproc",
    h1: "Certidão de Objeto e Pé nos sistemas Projudi e eproc",
    descricao:
      "Projudi (TJPR, TJGO) e eproc (TJRS, TJSC, TJTO, TRF2, TRF4): como localizar o processo e requerer a certidão em cada sistema.",
    resumo: "Dois sistemas com lógica própria, usados em estados de alto volume processual.",
    atualizado: "2026-08-26",
    leitura: 5,
    blocos: [
      { t: "h", x: "Projudi" },
      { t: "p", x: "Adotado por tribunais como TJPR e TJGO, o Projudi tem consulta pública por número do processo e área restrita para partes e advogados. O requerimento de certidão costuma ser feito por petição intermediária dirigida à vara, ou por formulário no portal do tribunal para quem não é parte." },
      { t: "h", x: "eproc" },
      { t: "p", x: "Usado por TJRS, TJSC, TJTO, TJAC, TRF2 e TRF4, o eproc é conhecido pela agilidade. Também aqui a certidão é requerida por petição ou por requerimento eletrônico à unidade em que o processo tramita, com recolhimento de custas quando previsto no regimento de custas do tribunal." },
      { t: "h", x: "Comparativo rápido" },
      { t: "tabela", head: ["Sistema", "Tribunais típicos", "Consulta pública", "Observação"], rows: [
        ["Projudi", "TJPR, TJGO, TJRR, TJAM", "Por número do processo", "Nível de sigilo definido por ato do juízo"],
        ["eproc", "TJRS, TJSC, TJTO, TJAC, TRF2, TRF4", "Por número e por parte", "Fluxo rápido de expedição"],
      ] },
      { t: "cta", x: CTA },
    ],
    faq: [
      { q: "O eproc emite certidão automaticamente?", a: "Algumas certidões são geradas pelo sistema; a de objeto e pé geralmente depende de expedição pela secretaria após requerimento." },
      { q: "Não consigo abrir o processo no Projudi. Por quê?", a: "Provavelmente o processo tem nível de sigilo restrito. Nesse caso, apenas parte ou advogado constituído obtém a certidão." },
    ],
  },
  {
    slug: "certidao-de-objeto-e-pe-justica-estadual",
    categoria: "tribunais",
    titulo: "Certidão de Objeto e Pé na Justiça Estadual: todos os TJs",
    h1: "Certidão de Objeto e Pé na Justiça Estadual",
    descricao:
      "Como funciona a certidão nos 27 Tribunais de Justiça do Brasil, com prazos médios, sistemas usados e o que muda de estado para estado.",
    resumo: "O ramo que concentra a maior parte dos pedidos — e as diferenças entre os 27 tribunais.",
    atualizado: "2026-08-26",
    leitura: 6,
    blocos: [
      { t: "p", x: "A Justiça Estadual julga a maior parte dos processos do país: ações cíveis, de família, sucessões, criminais comuns, execuções e juizados especiais. Cada um dos 27 Tribunais de Justiça tem seu sistema, seu regimento de custas e seu fluxo de expedição de certidões." },
      { t: "h", x: "O que muda de tribunal para tribunal" },
      { t: "ul", items: [
        "Sistema processual: e-SAJ, PJe, Projudi, eproc ou soluções próprias.",
        "Custas: há tribunais que emitem gratuitamente e outros que cobram por página.",
        "Prazo: de 1 a 5 dias úteis, conforme a comarca e o tribunal emissor.",
        "Processos físicos: comarcas do interior ainda mantêm acervo em papel, com desarquivamento.",
      ] },
      { t: "p", x: "Reunimos página por tribunal com sistema, prazo médio e comarcas atendidas no índice de tribunais, e páginas por estado com o contexto local." },
      { t: "cta", x: CTA },
    ],
    faq: [
      { q: "Posso pedir certidão de processo de outro estado?", a: "Sim. O pedido é feito ao tribunal em que o processo tramita, independentemente de onde você mora." },
      { q: "Processo de juizado especial tem certidão?", a: "Sim, expedida pela secretaria do juizado, com a mesma estrutura de objeto e fase." },
    ],
  },
  {
    slug: "certidao-de-objeto-e-pe-justica-federal",
    categoria: "tribunais",
    titulo: "Certidão de Objeto e Pé na Justiça Federal: Como Pedir",
    h1: "Como pedir a Certidão de Objeto e Pé na Justiça Federal",
    descricao:
      "Processo com INSS, Caixa ou União? Saiba como pedir a Certidão de Objeto e Pé na Justiça Federal (TRF1 a TRF6), o que consta e como solicitar online.",
    resumo: "Quando o processo é federal, o caminho passa pela seção judiciária e pelo TRF competente.",
    atualizado: "2026-08-26",
    leitura: 6,
    blocos: [
      { t: "p", x: "A Justiça Federal julga causas em que a União, autarquias (como INSS) e empresas públicas federais (como a Caixa) figuram como parte, além de crimes federais e execuções fiscais da Fazenda Nacional." },
      { t: "h", x: "Estrutura" },
      { t: "tabela", head: ["Tribunal", "Abrangência", "Sistema"], rows: [
        ["TRF1", "AC, AM, AP, BA, DF, GO, MA, MG, MT, PA, PI, RO, RR e TO", "PJe"],
        ["TRF2", "RJ e ES", "eproc"],
        ["TRF3", "SP e MS", "PJe"],
        ["TRF4", "RS, SC e PR", "eproc"],
        ["TRF5", "AL, CE, PB, PE, RN e SE", "PJe"],
        ["TRF6", "MG", "PJe"],
      ] },
      { t: "h", x: "Como pedir" },
      { t: "ol", items: [
        "Confirme se o processo está em 1º grau (subseção judiciária) ou no tribunal (2º grau).",
        "Requeira a certidão à vara federal ou à secretaria do órgão julgador no TRF.",
        "Indique expressamente objeto, partes e fase atual.",
        "Acompanhe a expedição no sistema e valide o código de autenticidade.",
      ] },
      { t: "nota", x: "Processos previdenciários e execuções fiscais federais são os que mais geram pedidos de certidão, sobretudo em análise de crédito e due diligence." },
      { t: "cta", x: CTA },
    ],
    faq: [
      { q: "Como sei se meu processo é federal?", a: "No número CNJ, o dígito do segmento é 4 para a Justiça Federal (5 para trabalhista, 8 para estadual)." },
      { q: "A certidão federal serve para gerenciadora de risco?", a: "Sim. Se o apontamento é de processo federal, a certidão precisa ser da Justiça Federal." },
    ],
  },
  {
    slug: "certidao-de-objeto-e-pe-justica-do-trabalho",
    categoria: "tribunais",
    titulo: "Certidão de Objeto e Pé na Justiça do Trabalho (TRT1 a TRT24)",
    h1: "Certidão de Objeto e Pé na Justiça do Trabalho",
    descricao:
      "Reclamações trabalhistas nos 24 TRTs e no TST: como pedir a certidão, o que ela mostra e por que empresas exigem o documento.",
    resumo: "Do PJe trabalhista à CNDT: o que a certidão resolve em processos do trabalho.",
    atualizado: "2026-08-26",
    leitura: 6,
    blocos: [
      { t: "p", x: "A Justiça do Trabalho é integralmente eletrônica no PJe, o que torna a expedição de certidões relativamente rápida. São 24 Tribunais Regionais do Trabalho, com jurisdição por estado ou por grupo de estados, e o TST em Brasília." },
      { t: "h", x: "O que a certidão trabalhista mostra" },
      { t: "ul", items: [
        "Reclamante e reclamada, com CPF/CNPJ.",
        "Pedidos principais (verbas rescisórias, horas extras, danos morais, vínculo).",
        "Valor da causa e, se houver, valor da condenação.",
        "Fase: instrução, sentença, recurso ordinário, recurso de revista, execução ou arquivamento.",
        "Existência de acordo homologado e seu cumprimento.",
      ] },
      { t: "h", x: "Certidão de objeto e pé x CNDT" },
      { t: "p", x: "A CNDT (Certidão Negativa de Débitos Trabalhistas) informa apenas se há débito inscrito em execução definitiva. Quando a CNDT sai positiva, a Certidão de Objeto e Pé do processo correspondente é o documento que explica a origem e a fase do débito." },
      { t: "cta", x: CTA },
    ],
    faq: [
      { q: "Empresa pode pedir certidão de processo trabalhista de candidato?", a: "A prática existe, mas é juridicamente sensível e pode configurar discriminação. Na dúvida, avalie a exigência com um advogado." },
      { q: "Como descobrir qual TRT julga meu processo?", a: "Pela localidade da prestação de serviços. O índice de tribunais deste site lista a abrangência de cada um dos 24 TRTs." },
    ],
  },
  {
    slug: "certidao-de-objeto-e-pe-tribunais-superiores",
    categoria: "tribunais",
    titulo: "Certidão de Objeto e Pé no STF, STJ, TST, STM e TSE",
    h1: "Certidão de Objeto e Pé nos tribunais superiores",
    descricao:
      "Processos em grau de recurso no STF, STJ, TST, STM e na Justiça Eleitoral: como requerer certidão e quais prazos esperar.",
    resumo: "Quando o processo subiu para Brasília, a certidão muda de endereço.",
    atualizado: "2026-08-26",
    leitura: 5,
    blocos: [
      { t: "p", x: "Se o processo está em grau de recurso especial ou extraordinário, o 'pé' atual pode estar em um tribunal superior — e a certidão de fase deve ser pedida a ele, não à vara de origem." },
      { t: "tabela", head: ["Tribunal", "Competência típica", "Prazo médio"], rows: [
        ["STF", "Recurso extraordinário, HC, ações de controle de constitucionalidade", "1 a 5 dias úteis, conforme a comarca e o tribunal emissor"],
        ["STJ", "Recurso especial, HC, conflitos de competência", "1 a 5 dias úteis, conforme a comarca e o tribunal emissor"],
        ["TST", "Recurso de revista, dissídios coletivos", "1 a 5 dias úteis, conforme a comarca e o tribunal emissor"],
        ["STM", "Processos da Justiça Militar da União", "1 a 5 dias úteis, conforme a comarca e o tribunal emissor"],
        ["TSE", "Registros de candidatura, contas eleitorais, recursos eleitorais", "1 a 5 dias úteis, conforme a comarca e o tribunal emissor"],
      ] },
      { t: "p", x: "Em muitos casos o destinatário aceita a certidão da origem, desde que ela informe que os autos estão em grau de recurso e indique o número no tribunal superior. Quando a exigência é do andamento no próprio superior, o requerimento vai à secretaria do órgão julgador." },
      { t: "cta", x: CTA },
    ],
    faq: [
      { q: "Meu processo subiu ao STJ. Peço certidão onde?", a: "Depende da exigência: a certidão da origem informa que os autos estão no STJ; a certidão do próprio STJ detalha a fase do recurso lá." },
      { q: "Processo eleitoral tem objeto e pé?", a: "Sim, expedida pelo cartório eleitoral, pelo TRE ou pelo TSE, conforme onde o feito tramita." },
    ],
  },
  {
    slug: "como-descobrir-em-qual-tribunal-esta-o-processo",
    categoria: "tribunais",
    titulo: "Como descobrir em qual tribunal está o processo pelo número",
    h1: "Como identificar o tribunal pelo número do processo (CNJ)",
    descricao:
      "O número CNJ de 20 dígitos revela ano, segmento da Justiça, tribunal e unidade de origem. Aprenda a ler e localizar o processo.",
    resumo: "Decifre o número do processo e descubra sozinho onde ele tramita.",
    atualizado: "2026-08-26",
    leitura: 5,
    blocos: [
      { t: "p", x: "O padrão CNJ tem o formato NNNNNNN-DD.AAAA.J.TR.OOOO. Cada bloco significa uma coisa:" },
      { t: "tabela", head: ["Bloco", "Significado"], rows: [
        ["NNNNNNN", "Número sequencial do processo na unidade de origem"],
        ["DD", "Dígito verificador"],
        ["AAAA", "Ano do ajuizamento"],
        ["J", "Segmento da Justiça"],
        ["TR", "Tribunal"],
        ["OOOO", "Unidade de origem (vara, foro, comarca)"],
      ] },
      { t: "h", x: "Tabela do segmento (J)" },
      { t: "tabela", head: ["Código", "Segmento"], rows: [
        ["1", "Supremo Tribunal Federal"],
        ["2", "Conselho Nacional de Justiça"],
        ["3", "Superior Tribunal de Justiça"],
        ["4", "Justiça Federal"],
        ["5", "Justiça do Trabalho"],
        ["6", "Justiça Eleitoral"],
        ["7", "Justiça Militar da União"],
        ["8", "Justiça Estadual"],
        ["9", "Justiça Militar Estadual"],
      ] },
      { t: "p", x: "Exemplo: em 1234567-89.2022.8.26.0100, o 8 indica Justiça Estadual, o 26 indica o TJSP e o 0100 corresponde ao Foro Central Cível da capital paulista." },
      { t: "nota", x: "Processos muito antigos podem não seguir o padrão CNJ. Nesses casos, a localização é feita por nome e CPF na consulta do tribunal ou por pesquisa no arquivo da comarca." },
      { t: "cta", x: CTA },
    ],
    faq: [
      { q: "O que significa o '8.26' no número do processo?", a: "8 é o segmento da Justiça Estadual e 26 é o código do Tribunal de Justiça de São Paulo." },
      { q: "E se o processo não tiver número CNJ?", a: "É um processo antigo. A busca é feita por nome e CPF na consulta do tribunal ou diretamente no arquivo da comarca." },
    ],
  },
];
