import type { Post } from "./tipos";

const CTA = "Solicite a Certidão de Objeto e Pé com nossa equipe: informe apenas o número do processo, o nome completo e o CPF da parte. Cuidamos do protocolo no tribunal correto e enviamos o documento digital.";

export const POSTS_CONCEITO: Post[] = [
  {
    slug: "o-que-e-certidao-de-objeto-e-pe",
    categoria: "conceito",
    titulo: "O que é Certidão de Objeto e Pé? Guia completo 2026",
    h1: "O que é Certidão de Objeto e Pé",
    descricao:
      "Certidão de Objeto e Pé é o documento oficial do tribunal que descreve o objeto do processo e a fase atual em que ele se encontra. Veja o que consta, para que serve e como pedir.",
    resumo:
      "O documento judicial que resume do que trata um processo e em que fase ele está — explicado do zero, com exemplos e casos de uso.",
    atualizado: "2026-08-26",
    leitura: 7,
    blocos: [
      { t: "p", x: "A Certidão de Objeto e Pé é o documento oficial expedido pelo Poder Judiciário que descreve, em um único texto, duas informações sobre um processo: o objeto (do que se trata a ação, quem são as partes e o que se pede) e o pé (a fase atual do andamento, ou seja, em que ponto o processo está hoje)." },
      { t: "p", x: "Ela é emitida pela própria unidade judiciária onde o processo tramita ou tramitou — vara estadual, federal, do trabalho ou tribunal superior — e traz código de autenticidade que permite conferir o documento no portal do tribunal." },
      { t: "h", x: "O que consta na Certidão de Objeto e Pé" },
      { t: "ul", items: [
        "Número do processo no padrão CNJ e a classe processual (execução, procedimento comum, reclamação trabalhista etc.).",
        "Vara, foro ou comarca responsável e o juízo em que o feito tramita.",
        "Nome e qualificação das partes: autor/exequente/reclamante e réu/executado/reclamado.",
        "Objeto: descrição resumida do que se discute, com o valor da causa quando aplicável.",
        "Data da distribuição e histórico das principais movimentações.",
        "Pé: situação atual — em instrução, com sentença, em grau de recurso, em execução, suspenso, arquivado, extinto ou transitado em julgado.",
        "Data de expedição, assinatura do servidor responsável e código de validação.",
      ] },
      { t: "h", x: "Por que esse nome estranho?" },
      { t: "p", x: "A expressão vem da linguagem forense tradicional. \"Objeto\" é a matéria discutida; \"pé\" é o pé do processo, isto é, o ponto em que ele se encontra — como quem pergunta \"em que pé está isso?\". Por isso a certidão também aparece com os nomes certidão narratória, certidão de andamento processual ou certidão circunstanciada, dependendo do tribunal." },
      { t: "h", x: "Para que serve na prática" },
      { t: "ul", items: [
        "Comprovar a existência (ou não) e a situação de um processo perante bancos, seguradoras e financeiras.",
        "Atender exigência de gerenciadoras de risco na habilitação de motoristas e transportadores.",
        "Instruir compra e venda de imóveis, quando aparece um processo no nome do vendedor.",
        "Participar de licitações e habilitar empresas em cadastros de fornecedores.",
        "Comprovar situação processual em concursos públicos, posse em cargo e processos de imigração.",
        "Demonstrar, em outro processo, o que foi decidido ou o que está sendo discutido em um feito paralelo.",
      ] },
      { t: "h", x: "Quem pode solicitar" },
      { t: "p", x: "Qualquer pessoa física ou jurídica pode pedir a certidão de processo público, mesmo sem ser parte e sem advogado, porque a publicidade dos atos processuais é regra constitucional. A exceção são os processos em segredo de justiça, restritos às partes e a seus procuradores." },
      { t: "h", x: "Quanto tempo demora e quanto custa" },
      { t: "tabela", head: ["Ramo", "Prazo médio", "Observação"], rows: [
        ["Justiça Estadual", "1 a 10 dias úteis", "Varia por comarca; processos físicos demoram mais"],
        ["Justiça Federal", "3 a 12 dias úteis", "Depende da seção judiciária e do TRF"],
        ["Justiça do Trabalho", "3 a 10 dias úteis", "Tramitação eletrônica no PJe agiliza"],
        ["Tribunais superiores", "5 a 15 dias úteis", "Volume alto de pedidos"],
      ] },
      { t: "p", x: "Alguns tribunais cobram taxa ou custas de expedição; outros emitem gratuitamente pela internet quando o processo é eletrônico e público. O custo do serviço de assessoria é separado das custas e cobre a identificação da vara, o protocolo do requerimento, o acompanhamento e a entrega digital." },
      { t: "nota", x: "A certidão não remove nem altera o processo. Ela apenas documenta oficialmente o que está lá — e é justamente essa transparência que costuma resolver a exigência de quem pediu o documento." },
      { t: "cta", x: CTA },
    ],
    faq: [
      { q: "O que é Certidão de Objeto e Pé?", a: "É a certidão oficial emitida pelo Poder Judiciário que descreve o objeto do processo (do que se trata, partes e pedido) e o pé (a fase atual do andamento), com código de autenticidade conferível no portal do tribunal." },
      { q: "Qualquer pessoa pode pedir?", a: "Sim, para processos públicos, mesmo sem ser parte e sem advogado. Processos em segredo de justiça só podem ser certificados às partes e a seus advogados constituídos." },
      { q: "A certidão apaga o processo do meu nome?", a: "Não. Ela apenas descreve oficialmente o processo e sua fase atual. Nenhuma certidão exclui ou altera um processo judicial." },
      { q: "Quanto tempo demora para sair?", a: "Em média de 1 a 10 dias úteis na Justiça Estadual e de 3 a 15 dias úteis nos demais ramos, conforme o tribunal e se o processo é eletrônico ou físico." },
    ],
  },
  {
    slug: "para-que-serve-certidao-de-objeto-e-pe",
    categoria: "conceito",
    titulo: "Para que serve a Certidão de Objeto e Pé? 10 usos reais",
    h1: "Para que serve a Certidão de Objeto e Pé",
    descricao:
      "Veja as 10 situações em que a Certidão de Objeto e Pé é exigida: crédito, imóveis, licitação, concurso, gerenciadora de risco, visto e mais.",
    resumo: "As situações concretas em que alguém exige esse documento — e o que a empresa ou o órgão espera ler nele.",
    atualizado: "2026-08-26",
    leitura: 6,
    blocos: [
      { t: "p", x: "A Certidão de Objeto e Pé é pedida sempre que alguém precisa entender um processo sem ler o processo inteiro. Ela transforma centenas de páginas em um resumo oficial e assinado pelo tribunal." },
      { t: "h", x: "1. Análise de crédito e financiamento" },
      { t: "p", x: "Quando aparece um processo no nome do proponente, o banco quer saber se é uma ação de cobrança milionária ou uma ação de família sem impacto patrimonial. A certidão esclarece objeto, valor da causa e fase." },
      { t: "h", x: "2. Gerenciadora de risco e motoristas" },
      { t: "p", x: "Transportadoras e gerenciadoras exigem a certidão para liberar cadastro de motorista quando surge apontamento criminal ou cível. É um dos usos que mais crescem no país." },
      { t: "h", x: "3. Compra e venda de imóveis" },
      { t: "p", x: "Na due diligence, processos em nome do vendedor podem indicar risco de fraude à execução. A certidão mostra se há penhora, se a ação é patrimonial e em que fase está." },
      { t: "h", x: "4. Licitações e cadastro de fornecedores" },
      { t: "p", x: "Órgãos públicos costumam exigir esclarecimento sobre ações judiciais que constem em certidões negativas positivas com efeito de negativa." },
      { t: "h", x: "5. Concursos públicos e posse em cargo" },
      { t: "p", x: "Na fase de investigação social, bancas pedem a certidão para verificar processos criminais e sua situação (arquivado, absolvido, em curso)." },
      { t: "h", x: "6. Vistos, cidadania e imigração" },
      { t: "p", x: "Consulados solicitam a certidão, muitas vezes com tradução juramentada e apostila de Haia, para comprovar a situação de processos apontados em antecedentes." },
      { t: "h", x: "7. Admissão e compliance corporativo" },
      { t: "p", x: "Empresas com programas de integridade pedem o documento em contratações sensíveis e em processos de due diligence de sócios e fornecedores." },
      { t: "h", x: "8. Seguros e resseguros" },
      { t: "p", x: "Seguradoras avaliam sinistros e riscos com base na fase real do processo relacionado ao segurado." },
      { t: "h", x: "9. Instrução de outro processo" },
      { t: "p", x: "Advogados juntam a certidão para comprovar litispendência, prevenção, conexão ou o teor de uma decisão em processo paralelo." },
      { t: "h", x: "10. Regularização de pendências pessoais" },
      { t: "p", x: "Muitas pessoas descobrem processos antigos e usam a certidão para saber exatamente o que aconteceu e se ainda há algo pendente." },
      { t: "cta", x: CTA },
    ],
    faq: [
      { q: "A empresa pediu 'certidão de objeto e pé atualizada' — o que isso significa?", a: "Significa uma certidão expedida recentemente, geralmente nos últimos 30 a 90 dias, porque o pé do processo muda com o tempo." },
      { q: "Serve para tirar o nome de lista de restrição?", a: "A certidão não remove restrições, mas costuma ser o documento aceito para esclarecer a natureza e a fase do processo que gerou o apontamento." },
      { q: "Preciso de uma certidão por processo?", a: "Sim. Cada certidão se refere a um processo específico. Se houver mais de um, é preciso uma para cada." },
    ],
  },
  {
    slug: "diferenca-objeto-e-pe-e-inteiro-teor",
    categoria: "conceito",
    titulo: "Objeto e Pé x Inteiro Teor: qual a diferença e qual pedir",
    h1: "Diferença entre Certidão de Objeto e Pé e Certidão de Inteiro Teor",
    descricao:
      "Objeto e Pé resume o processo em poucas páginas; inteiro teor reproduz peças na íntegra. Entenda qual documento pedir em cada situação.",
    resumo: "Dois documentos frequentemente confundidos — e a regra simples para escolher o certo.",
    atualizado: "2026-08-26",
    leitura: 5,
    blocos: [
      { t: "p", x: "A dúvida é comum porque as duas certidões saem do mesmo lugar e falam do mesmo processo. A diferença está na profundidade." },
      { t: "tabela", head: ["Critério", "Objeto e Pé", "Inteiro teor"], rows: [
        ["Conteúdo", "Resumo oficial: partes, objeto e fase atual", "Reprodução integral de peças ou de todo o processo"],
        ["Tamanho", "1 a 5 páginas", "Dezenas a milhares de páginas"],
        ["Prazo", "Mais rápido", "Mais demorado, sobretudo em processo físico"],
        ["Custo", "Menor", "Maior, geralmente por página"],
        ["Uso típico", "Bancos, gerenciadoras, licitações, concursos", "Perícia, recursos, defesa técnica, prova documental"],
      ] },
      { t: "h", x: "Regra prática para escolher" },
      { t: "ol", items: [
        "Se pediram para você 'explicar' um processo que apareceu no seu nome: Objeto e Pé.",
        "Se pediram a sentença, o acórdão ou uma peça específica: inteiro teor daquela peça.",
        "Se um advogado precisa analisar toda a prova: inteiro teor do processo.",
        "Se a exigência não é clara, comece pela Objeto e Pé — é mais rápida e barata e resolve a maioria dos casos.",
      ] },
      { t: "nota", x: "É possível pedir as duas: a Objeto e Pé para entregar rapidamente a quem exigiu e o inteiro teor de uma peça específica quando o conteúdo da decisão precisa ser comprovado." },
      { t: "cta", x: CTA },
    ],
    faq: [
      { q: "Objeto e pé e inteiro teor são a mesma coisa?", a: "Não. A Objeto e Pé é um resumo oficial do processo e de sua fase; o inteiro teor reproduz peças processuais na íntegra." },
      { q: "Qual é mais aceita por bancos e gerenciadoras?", a: "Na prática, a Certidão de Objeto e Pé, porque descreve objetivamente o objeto e a situação do processo." },
      { q: "O inteiro teor substitui a objeto e pé?", a: "Nem sempre. Muitos órgãos exigem expressamente a certidão de objeto e pé, com a fase atual certificada pelo cartório." },
    ],
  },
  {
    slug: "certidao-narratoria-o-que-e",
    categoria: "conceito",
    titulo: "Certidão Narratória: o que é e diferença para Objeto e Pé",
    h1: "Certidão Narratória: o que é e quando pedir",
    descricao:
      "Certidão narratória narra os fatos e atos de um processo. Veja em que ela se aproxima e em que se diferencia da Certidão de Objeto e Pé.",
    resumo: "Nome alternativo em vários tribunais — mas com nuances que vale conhecer antes de pedir.",
    atualizado: "2026-08-26",
    leitura: 5,
    blocos: [
      { t: "p", x: "Certidão narratória é a certidão em que o servidor narra, em texto corrido, os atos e fatos processuais relevantes. Em boa parte dos tribunais brasileiros ela é tratada como sinônimo de Certidão de Objeto e Pé; em outros, é um documento mais descritivo, que detalha o histórico das movimentações." },
      { t: "h", x: "Semelhanças" },
      { t: "ul", items: [
        "Ambas são expedidas pela unidade judiciária onde o processo tramita.",
        "Ambas trazem número do processo, partes, objeto e situação.",
        "Ambas possuem código de autenticidade e valor oficial.",
      ] },
      { t: "h", x: "Diferenças possíveis" },
      { t: "ul", items: [
        "A narratória tende a detalhar mais a cronologia dos atos praticados.",
        "A objeto e pé enfatiza a fase atual — o 'pé' do processo — em formato mais padronizado.",
        "Alguns tribunais só têm um dos nomes no menu de requerimentos.",
      ] },
      { t: "p", x: "Na dúvida, o pedido deve descrever o que se quer comprovar. No requerimento que protocolamos, especificamos objeto, partes, fase atual e histórico das movimentações — o que atende tanto quem pediu 'narratória' quanto quem pediu 'objeto e pé'." },
      { t: "cta", x: CTA },
    ],
    faq: [
      { q: "Certidão narratória é a mesma coisa que objeto e pé?", a: "Na maioria dos tribunais, sim: são nomes diferentes para a certidão que descreve o processo e sua fase. Em alguns, a narratória é mais detalhada quanto ao histórico dos atos." },
      { q: "Qual devo pedir se a empresa não especificou?", a: "Peça a Certidão de Objeto e Pé com histórico de movimentações — esse conteúdo cobre as duas exigências." },
    ],
  },
  {
    slug: "certidao-objeto-e-pe-x-nada-consta",
    categoria: "conceito",
    titulo: "Objeto e Pé x Nada Consta (negativa): entenda a diferença",
    h1: "Certidão de Objeto e Pé x Certidão Negativa (nada consta)",
    descricao:
      "A negativa diz se existe processo; a objeto e pé explica o processo que existe. Saiba quando cada uma é exigida e como se complementam.",
    resumo: "Quando a negativa vem 'positiva', a objeto e pé é o passo seguinte.",
    atualizado: "2026-08-26",
    leitura: 5,
    blocos: [
      { t: "p", x: "A certidão negativa (ou 'nada consta') responde a uma pergunta binária: existe processo em nome desta pessoa ou empresa? A Certidão de Objeto e Pé responde a outra: o que é e em que fase está este processo específico?" },
      { t: "tabela", head: ["Situação", "Documento indicado"], rows: [
        ["Comprovar que não há processos", "Certidão negativa (nada consta)"],
        ["A negativa saiu positiva e pediram esclarecimento", "Certidão de Objeto e Pé de cada processo"],
        ["Comprovar arquivamento ou absolvição", "Certidão de Objeto e Pé"],
        ["Habilitação em licitação com ação em curso", "Negativa + Objeto e Pé das ações apontadas"],
      ] },
      { t: "h", x: "Por que a negativa costuma vir 'positiva'" },
      { t: "p", x: "A busca é feita por nome e CPF/CNPJ. Homônimos, processos antigos, ações em que a pessoa foi apenas testemunha ou terceiro interessado e feitos já arquivados podem aparecer. A objeto e pé é exatamente o documento que esclarece cada apontamento." },
      { t: "cta", x: CTA },
    ],
    faq: [
      { q: "Minha certidão negativa veio com processos. E agora?", a: "Solicite a Certidão de Objeto e Pé de cada processo apontado: ela descreve o objeto e a fase, o que normalmente basta para o banco, a gerenciadora ou o órgão público." },
      { q: "Posso pedir as duas ao mesmo tempo?", a: "Sim, e é o mais comum em licitações e processos de admissão." },
    ],
  },
  {
    slug: "validade-certidao-de-objeto-e-pe",
    categoria: "conceito",
    titulo: "Validade da Certidão de Objeto e Pé: quanto tempo vale",
    h1: "Qual a validade da Certidão de Objeto e Pé",
    descricao:
      "A certidão não tem prazo de validade legal fixo: quem exige o documento define o período aceito, normalmente de 30 a 90 dias. Entenda.",
    resumo: "Não existe prazo legal único — existe o prazo que o destinatário aceita.",
    atualizado: "2026-08-26",
    leitura: 4,
    blocos: [
      { t: "p", x: "A Certidão de Objeto e Pé retrata o processo na data da expedição. Como o andamento muda, quem exige o documento estabelece um prazo de aceitação." },
      { t: "tabela", head: ["Quem exige", "Prazo aceito na prática"], rows: [
        ["Bancos e financeiras", "30 a 60 dias"],
        ["Gerenciadoras de risco", "30 dias"],
        ["Licitações e órgãos públicos", "60 a 90 dias, conforme o edital"],
        ["Consulados e imigração", "90 dias, às vezes com apostila"],
        ["Cartórios e negócios imobiliários", "30 a 90 dias"],
      ] },
      { t: "nota", x: "Antes de pedir, confirme o prazo exigido no edital, no contrato ou no e-mail de exigência. Isso evita ter de repetir a solicitação." },
      { t: "cta", x: CTA },
    ],
    faq: [
      { q: "A Certidão de Objeto e Pé tem validade de 30 dias?", a: "Não há prazo legal fixo. Na prática, os destinatários costumam aceitar certidões expedidas nos últimos 30 a 90 dias." },
      { q: "Preciso emitir de novo se o processo não mudou?", a: "Sim, se o destinatário exigir data recente. A validade é definida por quem recebe o documento, não pelo tribunal." },
    ],
  },
  {
    slug: "como-ler-certidao-de-objeto-e-pe",
    categoria: "conceito",
    titulo: "Como ler a Certidão de Objeto e Pé campo por campo",
    h1: "Como ler e interpretar a Certidão de Objeto e Pé",
    descricao:
      "Entenda cada campo da certidão: classe processual, valor da causa, partes, movimentações, trânsito em julgado e situação do processo.",
    resumo: "Um guia de leitura para quem recebeu a certidão e não sabe o que os termos significam.",
    atualizado: "2026-08-26",
    leitura: 6,
    blocos: [
      { t: "h", x: "Cabeçalho e identificação" },
      { t: "p", x: "Traz o tribunal, a comarca/seção, a vara e o número CNJ. Os 20 dígitos do número indicam sequencial, dígito verificador, ano, segmento da Justiça, tribunal e unidade de origem." },
      { t: "h", x: "Classe e assunto" },
      { t: "p", x: "A classe indica o tipo de ação (procedimento comum, execução de título extrajudicial, ação penal, reclamação trabalhista). O assunto detalha a matéria (inadimplemento, dano moral, furto, verbas rescisórias)." },
      { t: "h", x: "Partes" },
      { t: "p", x: "Verifique em qual polo a pessoa aparece. Ser réu ou executado é diferente de ser autor, testemunha ou terceiro interessado — e essa distinção muitas vezes resolve a exigência." },
      { t: "h", x: "Termos que aparecem no 'pé'" },
      { t: "tabela", head: ["Termo", "Significa"], rows: [
        ["Concluso para decisão", "Aguardando análise do juiz"],
        ["Em instrução", "Fase de provas e audiências"],
        ["Sentenciado", "Já há sentença, possivelmente com recurso pendente"],
        ["Trânsito em julgado", "Não cabe mais recurso"],
        ["Em fase de execução / cumprimento de sentença", "Cobrança do que foi decidido"],
        ["Suspenso / sobrestado", "Parado por decisão ou por lei"],
        ["Arquivado definitivamente", "Encerrado, sem pendências no juízo"],
        ["Baixa definitiva", "Registro encerrado no tribunal"],
      ] },
      { t: "h", x: "Autenticidade" },
      { t: "p", x: "No rodapé há o código de validação. Ele pode ser conferido no portal do tribunal, que reproduz o documento original — é assim que o destinatário confirma que a certidão é verdadeira." },
      { t: "cta", x: CTA },
    ],
    faq: [
      { q: "O que significa 'arquivado' na certidão?", a: "Que o processo foi encerrado naquele juízo. A certidão indica se o arquivamento é provisório (pode ser retomado) ou definitivo." },
      { q: "Como sei se ainda posso ser cobrado?", a: "Verifique se há fase de execução ou cumprimento de sentença em curso. Se houver trânsito em julgado e arquivamento definitivo, não há cobrança pendente naquele processo." },
    ],
  },
  {
    slug: "certidao-objeto-e-pe-e-legalizada",
    categoria: "conceito",
    titulo: "A Certidão de Objeto e Pé é documento oficial? Base legal",
    h1: "Base legal e valor oficial da Certidão de Objeto e Pé",
    descricao:
      "A certidão tem fundamento na Constituição e no CPC: publicidade dos atos processuais e direito de obter certidões em repartições públicas.",
    resumo: "Por que o tribunal é obrigado a fornecer a certidão e qual o valor jurídico do documento.",
    atualizado: "2026-08-26",
    leitura: 5,
    blocos: [
      { t: "p", x: "O direito de obter a certidão nasce da Constituição Federal, que assegura a todos, independentemente de taxas, a obtenção de certidões em repartições públicas para defesa de direitos e esclarecimento de situações de interesse pessoal (art. 5º, XXXIV, 'b'), e determina a publicidade dos atos processuais (art. 5º, LX, e art. 93, IX)." },
      { t: "p", x: "O Código de Processo Civil complementa ao prever que os autos são públicos, salvo segredo de justiça, e que terceiros podem requerer certidão do dispositivo da sentença e do inventário e partilha nos casos previstos em lei (arts. 11 e 189)." },
      { t: "h", x: "Consequências práticas" },
      { t: "ul", items: [
        "O cartório não pode negar a certidão de processo público sem fundamento legal.",
        "Em segredo de justiça, apenas partes e advogados constituídos obtêm a certidão completa.",
        "O documento é público e faz prova da situação processual perante qualquer órgão.",
        "A assinatura eletrônica do servidor e o código de autenticidade garantem a integridade.",
      ] },
      { t: "cta", x: CTA },
    ],
    faq: [
      { q: "O tribunal pode recusar a certidão?", a: "Somente com fundamento legal, como segredo de justiça ou sigilo determinado por decisão judicial. Processos públicos devem ser certificados." },
      { q: "A certidão digital tem o mesmo valor da impressa?", a: "Sim. A versão eletrônica assinada digitalmente, com código de autenticidade, tem o mesmo valor jurídico." },
    ],
  },
];
