/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CertidaoObjetoEPeTjspRouteImport } from './routes/certidao-objeto-e-pe-tjsp'
import { Route as PoliticaDePrivacidadeRouteImport } from './routes/politica-de-privacidade'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SolicitarRouteImport } from './routes/solicitar'
import { Route as TermosDeUsoRouteImport } from './routes/termos-de-uso'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as CertidaoDeObjetoEPeIndexRouteImport } from './routes/certidao-de-objeto-e-pe.index'
import { Route as CertidaoDeObjetoEPeUfRouteImport } from './routes/certidao-de-objeto-e-pe.$uf'
import { Route as PedidoProtocoloRouteImport } from './routes/pedido.$protocolo'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminProtocoloRouteImport } from './routes/_authenticated/admin.$protocolo'
import { Route as AuthenticatedAdminDocumentosRouteImport } from './routes/_authenticated/admin.documentos'
import { Route as AuthenticatedAdminHistoricoRouteImport } from './routes/_authenticated/admin.historico'
import { Route as BlogCategoriaSlugRouteImport } from './routes/blog.categoria.$slug'
import { Route as ApiPublicWebhooksMercadopagoRouteImport } from './routes/api/public/webhooks/mercadopago'
import { Route as ApiPublicWebhooksPagbankRouteImport } from './routes/api/public/webhooks/pagbank'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CertidaoObjetoEPeTjspRoute = CertidaoObjetoEPeTjspRouteImport.update({
  id: '/certidao-objeto-e-pe-tjsp',
  path: '/certidao-objeto-e-pe-tjsp',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDePrivacidadeRoute = PoliticaDePrivacidadeRouteImport.update({
  id: '/politica-de-privacidade',
  path: '/politica-de-privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SolicitarRoute = SolicitarRouteImport.update({
  id: '/solicitar',
  path: '/solicitar',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosDeUsoRoute = TermosDeUsoRouteImport.update({
  id: '/termos-de-uso',
  path: '/termos-de-uso',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const CertidaoDeObjetoEPeIndexRoute =
  CertidaoDeObjetoEPeIndexRouteImport.update({
    id: '/certidao-de-objeto-e-pe/',
    path: '/certidao-de-objeto-e-pe/',
    getParentRoute: () => rootRouteImport,
  } as any)
const CertidaoDeObjetoEPeUfRoute = CertidaoDeObjetoEPeUfRouteImport.update({
  id: '/certidao-de-objeto-e-pe/$uf',
  path: '/certidao-de-objeto-e-pe/$uf',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidoProtocoloRoute = PedidoProtocoloRouteImport.update({
  id: '/pedido/$protocolo',
  path: '/pedido/$protocolo',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminProtocoloRoute =
  AuthenticatedAdminProtocoloRouteImport.update({
    id: '/admin/$protocolo',
    path: '/admin/$protocolo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminDocumentosRoute =
  AuthenticatedAdminDocumentosRouteImport.update({
    id: '/admin/documentos',
    path: '/admin/documentos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminHistoricoRoute =
  AuthenticatedAdminHistoricoRouteImport.update({
    id: '/admin/historico',
    path: '/admin/historico',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const BlogCategoriaSlugRoute = BlogCategoriaSlugRouteImport.update({
  id: '/blog/categoria/$slug',
  path: '/blog/categoria/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksMercadopagoRoute =
  ApiPublicWebhooksMercadopagoRouteImport.update({
    id: '/api/public/webhooks/mercadopago',
    path: '/api/public/webhooks/mercadopago',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhooksPagbankRoute =
  ApiPublicWebhooksPagbankRouteImport.update({
    id: '/api/public/webhooks/pagbank',
    path: '/api/public/webhooks/pagbank',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/certidao-objeto-e-pe-tjsp': typeof CertidaoObjetoEPeTjspRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/solicitar': typeof SolicitarRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/certidao-de-objeto-e-pe/$uf': typeof CertidaoDeObjetoEPeUfRoute
  '/pedido/$protocolo': typeof PedidoProtocoloRoute
  '/blog/': typeof BlogIndexRoute
  '/certidao-de-objeto-e-pe/': typeof CertidaoDeObjetoEPeIndexRoute
  '/admin/$protocolo': typeof AuthenticatedAdminProtocoloRoute
  '/admin/documentos': typeof AuthenticatedAdminDocumentosRoute
  '/admin/historico': typeof AuthenticatedAdminHistoricoRoute
  '/blog/categoria/$slug': typeof BlogCategoriaSlugRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/api/public/webhooks/mercadopago': typeof ApiPublicWebhooksMercadopagoRoute
  '/api/public/webhooks/pagbank': typeof ApiPublicWebhooksPagbankRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/certidao-objeto-e-pe-tjsp': typeof CertidaoObjetoEPeTjspRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/solicitar': typeof SolicitarRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/certidao-de-objeto-e-pe/$uf': typeof CertidaoDeObjetoEPeUfRoute
  '/pedido/$protocolo': typeof PedidoProtocoloRoute
  '/blog': typeof BlogIndexRoute
  '/certidao-de-objeto-e-pe': typeof CertidaoDeObjetoEPeIndexRoute
  '/admin/$protocolo': typeof AuthenticatedAdminProtocoloRoute
  '/admin/documentos': typeof AuthenticatedAdminDocumentosRoute
  '/admin/historico': typeof AuthenticatedAdminHistoricoRoute
  '/blog/categoria/$slug': typeof BlogCategoriaSlugRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/api/public/webhooks/mercadopago': typeof ApiPublicWebhooksMercadopagoRoute
  '/api/public/webhooks/pagbank': typeof ApiPublicWebhooksPagbankRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/certidao-objeto-e-pe-tjsp': typeof CertidaoObjetoEPeTjspRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/solicitar': typeof SolicitarRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/certidao-de-objeto-e-pe/$uf': typeof CertidaoDeObjetoEPeUfRoute
  '/pedido/$protocolo': typeof PedidoProtocoloRoute
  '/blog/': typeof BlogIndexRoute
  '/certidao-de-objeto-e-pe/': typeof CertidaoDeObjetoEPeIndexRoute
  '/_authenticated/admin/$protocolo': typeof AuthenticatedAdminProtocoloRoute
  '/_authenticated/admin/documentos': typeof AuthenticatedAdminDocumentosRoute
  '/_authenticated/admin/historico': typeof AuthenticatedAdminHistoricoRoute
  '/blog/categoria/$slug': typeof BlogCategoriaSlugRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/api/public/webhooks/mercadopago': typeof ApiPublicWebhooksMercadopagoRoute
  '/api/public/webhooks/pagbank': typeof ApiPublicWebhooksPagbankRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/certidao-objeto-e-pe-tjsp'
    | '/politica-de-privacidade'
    | '/sitemap.xml'
    | '/solicitar'
    | '/termos-de-uso'
    | '/certidao-de-objeto-e-pe/$uf'
    | '/pedido/$protocolo'
    | '/blog/'
    | '/certidao-de-objeto-e-pe/'
    | '/admin/$protocolo'
    | '/admin/documentos'
    | '/admin/historico'
    | '/blog/categoria/$slug'
    | '/admin/'
    | '/api/public/webhooks/mercadopago'
    | '/api/public/webhooks/pagbank'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/certidao-objeto-e-pe-tjsp'
    | '/politica-de-privacidade'
    | '/sitemap.xml'
    | '/solicitar'
    | '/termos-de-uso'
    | '/certidao-de-objeto-e-pe/$uf'
    | '/pedido/$protocolo'
    | '/blog'
    | '/certidao-de-objeto-e-pe'
    | '/admin/$protocolo'
    | '/admin/documentos'
    | '/admin/historico'
    | '/blog/categoria/$slug'
    | '/admin'
    | '/api/public/webhooks/mercadopago'
    | '/api/public/webhooks/pagbank'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/certidao-objeto-e-pe-tjsp'
    | '/politica-de-privacidade'
    | '/sitemap.xml'
    | '/solicitar'
    | '/termos-de-uso'
    | '/certidao-de-objeto-e-pe/$uf'
    | '/pedido/$protocolo'
    | '/blog/'
    | '/certidao-de-objeto-e-pe/'
    | '/_authenticated/admin/$protocolo'
    | '/_authenticated/admin/documentos'
    | '/_authenticated/admin/historico'
    | '/blog/categoria/$slug'
    | '/_authenticated/admin/'
    | '/api/public/webhooks/mercadopago'
    | '/api/public/webhooks/pagbank'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CertidaoObjetoEPeTjspRoute: typeof CertidaoObjetoEPeTjspRoute
  PoliticaDePrivacidadeRoute: typeof PoliticaDePrivacidadeRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SolicitarRoute: typeof SolicitarRoute
  TermosDeUsoRoute: typeof TermosDeUsoRoute
  CertidaoDeObjetoEPeUfRoute: typeof CertidaoDeObjetoEPeUfRoute
  PedidoProtocoloRoute: typeof PedidoProtocoloRoute
  BlogIndexRoute: typeof BlogIndexRoute
  CertidaoDeObjetoEPeIndexRoute: typeof CertidaoDeObjetoEPeIndexRoute
  BlogCategoriaSlugRoute: typeof BlogCategoriaSlugRoute
  ApiPublicWebhooksMercadopagoRoute: typeof ApiPublicWebhooksMercadopagoRoute
  ApiPublicWebhooksPagbankRoute: typeof ApiPublicWebhooksPagbankRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certidao-objeto-e-pe-tjsp': {
      id: '/certidao-objeto-e-pe-tjsp'
      path: '/certidao-objeto-e-pe-tjsp'
      fullPath: '/certidao-objeto-e-pe-tjsp'
      preLoaderRoute: typeof CertidaoObjetoEPeTjspRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-privacidade': {
      id: '/politica-de-privacidade'
      path: '/politica-de-privacidade'
      fullPath: '/politica-de-privacidade'
      preLoaderRoute: typeof PoliticaDePrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solicitar': {
      id: '/solicitar'
      path: '/solicitar'
      fullPath: '/solicitar'
      preLoaderRoute: typeof SolicitarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos-de-uso': {
      id: '/termos-de-uso'
      path: '/termos-de-uso'
      fullPath: '/termos-de-uso'
      preLoaderRoute: typeof TermosDeUsoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certidao-de-objeto-e-pe/': {
      id: '/certidao-de-objeto-e-pe/'
      path: '/certidao-de-objeto-e-pe'
      fullPath: '/certidao-de-objeto-e-pe/'
      preLoaderRoute: typeof CertidaoDeObjetoEPeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certidao-de-objeto-e-pe/$uf': {
      id: '/certidao-de-objeto-e-pe/$uf'
      path: '/certidao-de-objeto-e-pe/$uf'
      fullPath: '/certidao-de-objeto-e-pe/$uf'
      preLoaderRoute: typeof CertidaoDeObjetoEPeUfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedido/$protocolo': {
      id: '/pedido/$protocolo'
      path: '/pedido/$protocolo'
      fullPath: '/pedido/$protocolo'
      preLoaderRoute: typeof PedidoProtocoloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/$protocolo': {
      id: '/_authenticated/admin/$protocolo'
      path: '/admin/$protocolo'
      fullPath: '/admin/$protocolo'
      preLoaderRoute: typeof AuthenticatedAdminProtocoloRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/documentos': {
      id: '/_authenticated/admin/documentos'
      path: '/admin/documentos'
      fullPath: '/admin/documentos'
      preLoaderRoute: typeof AuthenticatedAdminDocumentosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/historico': {
      id: '/_authenticated/admin/historico'
      path: '/admin/historico'
      fullPath: '/admin/historico'
      preLoaderRoute: typeof AuthenticatedAdminHistoricoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/blog/categoria/$slug': {
      id: '/blog/categoria/$slug'
      path: '/blog/categoria/$slug'
      fullPath: '/blog/categoria/$slug'
      preLoaderRoute: typeof BlogCategoriaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/mercadopago': {
      id: '/api/public/webhooks/mercadopago'
      path: '/api/public/webhooks/mercadopago'
      fullPath: '/api/public/webhooks/mercadopago'
      preLoaderRoute: typeof ApiPublicWebhooksMercadopagoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/pagbank': {
      id: '/api/public/webhooks/pagbank'
      path: '/api/public/webhooks/pagbank'
      fullPath: '/api/public/webhooks/pagbank'
      preLoaderRoute: typeof ApiPublicWebhooksPagbankRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminProtocoloRoute: typeof AuthenticatedAdminProtocoloRoute
  AuthenticatedAdminDocumentosRoute: typeof AuthenticatedAdminDocumentosRoute
  AuthenticatedAdminHistoricoRoute: typeof AuthenticatedAdminHistoricoRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminProtocoloRoute: AuthenticatedAdminProtocoloRoute,
  AuthenticatedAdminDocumentosRoute: AuthenticatedAdminDocumentosRoute,
  AuthenticatedAdminHistoricoRoute: AuthenticatedAdminHistoricoRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CertidaoObjetoEPeTjspRoute: CertidaoObjetoEPeTjspRoute,
  PoliticaDePrivacidadeRoute: PoliticaDePrivacidadeRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SolicitarRoute: SolicitarRoute,
  TermosDeUsoRoute: TermosDeUsoRoute,
  CertidaoDeObjetoEPeUfRoute: CertidaoDeObjetoEPeUfRoute,
  PedidoProtocoloRoute: PedidoProtocoloRoute,
  BlogIndexRoute: BlogIndexRoute,
  CertidaoDeObjetoEPeIndexRoute: CertidaoDeObjetoEPeIndexRoute,
  BlogCategoriaSlugRoute: BlogCategoriaSlugRoute,
  ApiPublicWebhooksMercadopagoRoute: ApiPublicWebhooksMercadopagoRoute,
  ApiPublicWebhooksPagbankRoute: ApiPublicWebhooksPagbankRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
